### ISSUE TITLE
${env.JAVA_HOME} in systemPath cannot be recognized by this plugin

### ISSUE THREAD

**Issue by fwhdzh** [microsoft/vscode-maven#1001]
**Describe the bug**
In my pom.xml, I add a dependcy of the tools.jar in jdk
```
<dependency>
      <groupId>jdk.tools</groupId>
      <artifactId>jdk.tools</artifactId>
      <version>1.8</version>
      <scope>system</scope>
      <systemPath>${env.JAVA_HOME}/lib/tools.jar</systemPath>
</dependency>
```
A wave line appears under this dependency. When we move our mouse on it, it will show "Project build error: 'dependencies.dependency.systemPath' for jdk.tools:jdk.tools:jar must specify an absolute path but is ${env.JAVA_HOME}/lib/tools.jar".

However, this dependency is correct. If I use `mvn install` directly in bash terminal, maven will successfully complier the project and install it to local repository. If I set `maven.executable.path`, the `mvn install` can also work in the terminal in VScode. In another word, I think it is just a misinformation in the panel.

**To Reproduce**
1. Download and unzip a jdk whose version is 1.8.
2. Set correctly `JAVA_HOME` environment variable as the directory of jdk installation. Ensure `$JAVA_HOME/lib/tools.jar` exists.
3. Create a new maven project.
4. Add dependency mentioned above.

**Expected behavior**
There should be no error shown in VSCode Panel.

**Environments (please complete the following information as much as possible):**
 - OS: I am using vscode remote. My host machine is Windows 11, and remote is CentOS 7.9.2009
 - VS Code version: July 2022 (version 1.70)
 - Extension version: Language support for Java ™ for Visual Studio Code (v1.15.0) and Maven for Java (v0.40.4)

**Screenshots**

![image](https://github.com/microsoft/vscode-maven/assets/43179325/a7dd3a27-eb57-4831-a6a3-1ee970dc5841)

The wave line shows there is an error.

![image](https://github.com/microsoft/vscode-maven/assets/43179325/15cea9fe-9b59-4f04-ae86-5b4b8c42030a)

The detailed error information.

![image](https://github.com/microsoft/vscode-maven/assets/43179325/f26acc03-4ab7-4a00-ad49-576478a0c9c4)

If we run `mvn install` command in bash terminal, everything is ok.

![image](https://github.com/microsoft/vscode-maven/assets/43179325/22fb412b-48a3-4f72-95f4-096e6a973b28)

Terminal built-in VSCode also works well to handle this dependency.

**Comment by testforstephen** [comment]
This error comes from RedHat Java language support extension. It duplicates with https://github.com/redhat-developer/vscode-java/issues/1551

**Comment by Winson-Huang** [comment]
I find a wired situation, when using {env.JAVA_HOME} in systemPath, now there is no error wave line, but when using {java.home} it still exists. I find it in Linux with OpenJDK 8.
