### ISSUE TITLE
Command-breaking quote usage

### ISSUE THREAD

**Issue by Pixel48** [microsoft/vscode-maven#1011]
**Describe the bug**
Extension wraps build command in double quotes, but it also wraps path to custom mvn fine in double quotes, which breaks overall quote structure and renders any command it produces unusable. Problem is present even with default setting purely because of bad quote usage - reusing command in cmd without wrapping in quotes makes it usable
![image](https://github.com/microsoft/vscode-maven/assets/42846410/8f044dae-5806-4fd9-b563-fe8c32f96499)
> This ss is made on default vscode-maven settings, so it means that even on defaults this extension is unusable just because of quotes 

**To Reproduce**
1. Download apache-maven into C:/.../Java/ directory
![image](https://github.com/microsoft/vscode-maven/assets/42846410/989bf975-983d-4cc0-a91d-174486fe8e2d)
2. Set maven from point 1 in maven.executable.path
![image](https://github.com/microsoft/vscode-maven/assets/42846410/6f4fdb55-0a3b-4657-bfa6-8acfcd65ba6c)
3. Try to create JavaFX project
![image](https://github.com/microsoft/vscode-maven/assets/42846410/25a05967-022b-424d-a2f3-12b1c64c5ab4)
4. Watch how wrapping command in double quotes makes it unexecutable
![image](https://github.com/microsoft/vscode-maven/assets/42846410/b183348d-5d54-4e42-ab64-548acc7e4348)
5. Bonus points if you try to execute command from inside the quotes, to make it work just fine...
![image](https://github.com/microsoft/vscode-maven/assets/42846410/d4a173a8-b226-464e-92ed-286ddd18d7b5)

**Expected behavior**
Building project without making itself unusable by creating doube double-quotes

**Environments (please complete the following information as much as possible):**
 - OS: Win11 Edu
 - VS Code version: 1.84.2
 - Extension version: [e.g. 0.9.0]

**Comment by testforstephen** [comment]
I tried it in Windows 11, it works for me with double quotes.
![image](https://github.com/microsoft/vscode-maven/assets/14052197/13daa178-392e-45ed-a2aa-9f0d83aa5134)
