### ISSUE TITLE
Imports cannot be resolved despite building from command line

### ISSUE THREAD

**Issue by vasba** [microsoft/vscode-maven#1026]
**Describe the bug**
I imported an existing Java project in VS Code but some of the imports are not being resolved. However compiling from command line works. It also works in VS Code on Windows and Linux but not on OS X Sonoma.

**To Reproduce**
Well, just import an existing Maven based Java project

**Expected behavior**
If the build from command line passes then it should work in VS Code too

**Environments (please complete the following information as much as possible):**
 - OS: OS X Sonoma
 - VS Code version: 1.87.2
 - Extension version: 0.44.0 

**Screenshots**

**Additional context**
Not sure what context might be relevant.

**Comment by testforstephen** [comment]
The features provided by this extension is limited to Maven task management, goal execution, and project scaffolding.

The project importing feature is related to https://github.com/redhat-developer/vscode-java/issues, pls create an issue there. It's better to provide a sample project to reproduce the issue.
