### ISSUE TITLE
After opening a working folder, the extension crashed

### ISSUE THREAD

**Issue by ahao0150** [microsoft/vscode-maven#1045]
Type: <b>Bug</b>

I can't describe the specific reproduction steps. I just opened a working folder containing the gradle project and the mvn project, which used to be open normally. But these two days, the plug-in extension crashed. Some information gathered by the following problem reporting program.（PS: machine translation）

Extension version: 0.44.0
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz (24 x 2394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (20.55GB free)|
|Process Argv|--crash-reporter-id e0cd0d9c-9cfb-40db-90eb-a7b6e5b784aa|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
ei213698:31121563
iacca2:31138163

```

</details>

**Comment by testforstephen** [comment]
Could you pls provide a minimum sample project to help reproduce the issue?

**Comment by ahao0150** [comment]
> Could you pls provide a minimum sample project to help reproduce the issue?

Hello,

Thank you for your attention to this issue! Recently, I haven’t been able to reproduce this problem, so it might have been resolved or is no longer appearing in my environment.

Thank you again for your time and assistance!
