### ISSUE TITLE
Downloading artifacts in parallel

### ISSUE THREAD

**Issue by mamilic** [microsoft/vscode-maven#1050]
I could not find a way to set downloading artifacts in parallel. I am wondering if MAVEN_ARGS will be taken into consideration within m2e and vscode-maven? There are some params that can be set to parallelize artifacts downloading.  https://maven.apache.org/resolver/configuration.html

**Comment by testforstephen** [comment]
I believe m2e has already adopted parallel downloading, see the PR https://github.com/redhat-developer/vscode-java/pull/3030. For vscode-maven extension, what feature do you want to enable parallel downloading?

**Comment by mamilic** [comment]
Thanks for the info. If that's the case, we can close this issue.
