### ISSUE TITLE
After opening a Maven project, should first execute mvn clean validate.

### ISSUE THREAD

**Issue by mozhuanzuojing** [microsoft/vscode-maven#1051]
**Describe the bug**
After opening a Maven project, you should first execute mvn clean validate.  
Because some projects have additional dependencies defined in the POM that will be downloaded during the validate phase, and only then can the project be compiled.

**To Reproduce**
1. Git clone https://github.com/eclipse-jdtls/eclipse.jdt.ls.git 
2. open it in vscode
3. waiting vscode-java first build
4. select org.eclipse.jdt.ls.target\org.eclipse.jdt.ls.tp.target . right key exec Reload Target Platform (from plugin  Eclipse PDE support)
5. waiting Eclipse PDE support second build
6. see PROBLEMS output
**Expected behavior**
build seccuss!

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: 1.95
 - Extension version 0.44.0

**Screenshots**
![Image](https://github.com/user-attachments/assets/9a183249-c6ee-46e6-919b-a175fe73b1d1)

**Additional context**

**Comment by testforstephen** [comment]
this extension does not have the direct relationship with the JDT language server. The purpose of this extension is to list basic maven plugins, goals and dependencies, and assist user to execute a goal. It does not make sense to make this extension to auto execute a maven build on first opening a project in workspace. It's the language server itself that should download all dependencies when it imports the project.
