### ISSUE TITLE
Maven view should prioritize displaying the project root directory name at the top.

### ISSUE THREAD

**Issue by mozhuanzuojing** [microsoft/vscode-maven#1052]
## Suggestion

Maven view should prioritize displaying the project root directory name at the top.

## Use Cases

Usually, when opening the Maven view of a project, one would want to first identify the root project, or perform operations on the root project.

## Examples

1. git clone https://github.com/eclipse-jdtls/eclipse.jdt.ls.git
2. build 
3. see Maven view 
![Image](https://github.com/user-attachments/assets/c3e85035-7d15-4268-97d7-03ca25e43810)

**Comment by testforstephen** [comment]
In the flat view, the tree node is displayed by alphabetical order. If you want to show it as the physical structure, please switch to the hierarchical view.

![Image](https://github.com/user-attachments/assets/4f1ccb47-ed0d-43c1-ba7c-a1b87dd8a27a)
