### ISSUE TITLE
User can not find the log after executed a command

### ISSUE THREAD

**Issue by JanusWu** [Microsoft/vscode-maven#111]
**Describe the bug**
User may want to find the logs after executed a command

**Environments:**
 - OS: Windows 10
 - VS Code version: 1.25.1
 - Extension version: #257

**To Reproduce**
1. Clone code from https://github.com/Microsoft/todo-app-java-on-azure.git
2. Open the cloned project in VS Code
3. Make sure "terminal.integrated.shell.windows" is set to PowerShell
4. Right click on the project item and select a command, such as `package`

**Actual behavior**
A new shell pop up to show the log, and it will be closed when the command execute complete.
![image](https://user-images.githubusercontent.com/17060520/43198486-69fa1b92-9041-11e8-9cc1-8aaef0744c83.png)

**Expected behavior**
Use can find the log somewhere after executed the maven command

**Comment by Eskibear** [comment]
Not familiar with PowerShell, after some experiments, I think `cmd /c <command string>` should work better than `& <command string>`.

**Comment by Eskibear** [comment]
![image](https://user-images.githubusercontent.com/2351748/43213243-bc68d108-9068-11e8-8261-1a8c57dd9dc4.png)

**Comment by Eskibear** [comment]
fixed in #112
