### ISSUE TITLE
Regular error "Lifecycle mapping "org.eclipse.m2e.jdt.JarLifecycleMapping" is not available"

### ISSUE THREAD

**Issue by lashchev** [Microsoft/vscode-maven#115]
**Describe the bug**
Very often I get this error: `Lifecycle mapping "org.eclipse.m2e.jdt.JarLifecycleMapping" is not available. To enable full functionality, install the lifecycle mapping and run Maven->Update Project Configuration.`

The strangest thing is that it happens when there were no updates in pom.xml or any other project-level files, when I am just editing *.java files. Sometimes it happens at the same time when "Language Support for Java" extension has issues parsing the files and dumps some errors in the log.

Also, "Maven->Update Project Configuration" (and Shift+Alt+U) works for me only if I have pom.xml open and it's window is active (which is unexpected).

Even "Maven->Update Project Configuration" does not always work for me.

First I typically need to fix all Java compilation issues and then I need to re-open VSCode and let it sit for a few minutes - then "Update Project Configuration" will start working. Sometimes I need to restart VSCode 2 or 3 times to finally make it work though.

Since VSCode restart fixes the issue - the recommendation to "install the lifecycle mapping" is pretty misleading in the message.

**To Reproduce**
It happens randomly, often when opening Java project that has compilation issues, but can appear while editing already opened project.

**Expected behavior**
Error shouldn't happen and if the only fix is to "Update configuration" - then it should be attempted automatically.

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10 v1803
 - VS Code version: 1.25.1
 - Extension version 0.10.0

**Comment by Eskibear** [comment]
It looks this error is reported by m2e integrated in the language server, and here is not the best place for the issue. 
Currently to get you rid of this issue, my personal suggestion is to delete `related WorkspaceStorage folder` where your projects info are cached. (They might be outdated and inconsistent for some reason. I guess that would possibly be a reason.)
The way to find the workspace storage folder:
* Command palette => Java: Open language server log file
* Look for the folder path in the beginning lines of the log file. e.g. for me,
```
Line 6: Command-line arguments:  -data C:\Users\<username>\AppData\Roaming\Code\User\workspaceStorage\<hash value>\redhat.java\jdt_ws
```
Sometimes you are supposed to close VSCode before you delete the `C:\Users\<username>\AppData\Roaming\Code\User\workspaceStorage\<hash value>` folder.
Hope it helps.

I just created a same issue in the "Language Support for Java" extension, so I'm now closing it and you can track this in https://github.com/redhat-developer/vscode-java/issues/603
And I suggest you to provide version of JDK and "Language Support for Java" extension in that issue, so they can know more details.

**Comment by lashchev** [comment]
@Eskibear: I closed VSCode and deleted `C:\Users\lashc\AppData\Roaming\Code\User\workspaceStorage\<hash>` folder and will keep monitoring for the error.
Thanks for creating an issue for Java language server, I added details there.

**Comment by miathedev** [comment]
The problem still exists! Thank you very much  @lashchev deleting it solved it for me.
