### ISSUE TITLE
Option for "mvn validate" called on "git checkout"

### ISSUE THREAD

**Issue by slacaze** [Microsoft/vscode-maven#128]
**Describe the bug**
I don't see this as a bug per say. It seems that whenever I open VS Code, or "git checkout", "mvn validate" is run. Is this expected behavior? If so, is there an option to disable this?

**To Reproduce**
Open VS Code, and see "mvn validate" being called (for example by binding some other plugin goal to validate phase)

**Expected behavior**
I wasn't expecting VS Code to silently call validate.

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: 1.27.2
 - Extension version: 0.10.0

**Additional context**

**Comment by Eskibear** [comment]
I don't think this extension will run "mvn validate" silently. Could you follow steps below and share the result?

1. Disable the extension "Maven for Java".
2. Reload the window to see if the issue still exists.

**Comment by slacaze** [comment]
You're right, it happens anyway if I disable the Maven for Java extension.

I guess maybe there's something trying to workout the JAR required for linting, and that calls "mvn validate" maybe.

**Comment by Eskibear** [comment]
Supposed to be an external issue, I'm closing it.
