### ISSUE TITLE
Project configuration is not up-to-date with pom.xml, requires an update.

### ISSUE THREAD

**Issue by jcastill0** [Microsoft/vscode-maven#132]
**Describe the bug**
Loaded a project (source) that has a pom.xml, VSCode automatically generated a warning message indicating that the the configuration is not up-to-date.

**To Reproduce**

**Expected behavior**

**Environments (please complete the following information as much as possible):**
 - OS: OSX
 - VS Code version: 1.27.2
 - Extension version 0.11

**Screenshots**

**Additional context**
It used to be that in the old Eclipse world, we would just update the project, but such feature does not exist in VS Code.

**Comment by Eskibear** [comment]
I think the warning message is probably generated by the language server, it's beyond this extension's control. 

> we would just update the project, but such feature does not exist in VS Code.

You may find `Update project configuration` by right click on pom.xml in explorer. I think that would help.

**Comment by britho** [comment]
It's possible that your pom.xml is not using the Maven schema. I encountered the same problem when using this block:
```xml
<project>
...
</project>
```
The warning was resolved when I added some [attributes](https://maven.apache.org/pom.html#The_Basics).
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                      http://maven.apache.org/xsd/maven-4.0.0.xsd">
```

**Comment by adiantek** [comment]
![image](https://user-images.githubusercontent.com/13407885/133893793-4379a1aa-b60a-416f-9708-97ae73751e5a.png)
Still unresolved. Tried `mvn clean eclipse:clean eclipse:eclipse compile package`, reload window, etc.

**Comment by Eskibear** [comment]
@adiantek it looks like Java language server workspace was broken for some reason. AFAIK, command “Java: clean language server workspace” can help to clean it.(Similar as what you did to fix it)

@testforstephen  @nickzhums 
From the number of thumb-ups above, it’s common to have “project not up to date with Pom.xml” warning. And many of them don’t find the way to update project configuration until they find this issue. 

I’m thinking that is it possible to directly provide quickfix for this?

**Comment by nickzhums** [comment]
in what scenarios would the language server show such error "project not up to date"

**Comment by cy6erGn0m** [comment]
What a strange thing: in a big multimodule project I have to refresh every single pom file separately to get it analyzed and added to the list of Java projects..

**Comment by humble-barnacle001** [comment]
For those who are a fan of configuration files, set
```json
{
    "java.configuration.updateBuildConfiguration": "automatic"
}
```

in `.vscode/settings.json` shall do the trick.

Other options are `disabled` and `interactive`

**Comment by Aincvy** [comment]
vscode didn't show my projects, I tried `mvn clean eclipse:clean eclipse:eclipse compile package`, then solve my problem.

**Comment by edwinteisman** [comment]
You guys just saved my life.... I could not longer run my Java application. 
After cleaning the Java Language server the problem has magically gone away.
It has taken me hours to figure this out :-(
