### ISSUE TITLE
Help validating version-lens Java support

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode-maven#133]
vscode-contrib/vscode-versionlens#107

In this issue, an author contributed the support for maven POM files and needed some help to validate. Please help.

**Comment by Eskibear** [comment]
versionlens provides code lens for static <dependency> node in pom.xml, and it requires explicit declaration of all groupId, artifactId and version. If `groupId` in inherited from parent pom, it won't work.

**Comment by fcrespo82** [comment]
There is already some improvements over the first version. It now should correctly identify versions set with variables. I think I didn’t take care of parent Pom though. 
https://github.com/vscode-contrib/vscode-versionlens/pull/114
