### ISSUE TITLE
Please use the latest version of vscode-extension-telemetry-wrapper dependency

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-maven#135]
This extension uses version 0.3.1 of `vscode-extension-telemetry-wrapper`  module.

The latest version of `vscode-extension-telemetry-wrapper` module (0.3.2) uses the latest version of `vscode-extension-telemetry` module (0.0.22) which has the fix to prevent unnecessary patching of the require and other 3rd party modules. 

For more details, please see https://github.com/Eskibear/vscode-extension-telemetry-wrapper/issues/20

**Comment by Eskibear** [comment]
Resolved in v0.11.1
