### ISSUE TITLE
Error Extensions

### ISSUE THREAD

**Issue by JoaoVitorViana** [Microsoft/vscode-maven#137]
- Extension Name: vscode-maven
- Extension Version: 0.11.0
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

**Comment by Eskibear** [comment]
Can you provide more details to describe the issue?

**Comment by Eskibear** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. Please reach out if you have or find the answers we need so that we can investigate further.
