### ISSUE TITLE
maven goals fail to execute when using WSL bash for Terminal

### ISSUE THREAD

**Issue by RobertDeRose** [Microsoft/vscode-maven#142]
**Describe the bug**
maven goals fail to execute when using WSL bash for Terminal

**To Reproduce**
1. open a maven based project on windows
2. Have WSL install  (I am using Ubuntu)
3. Set VSCode to use bash.exe
  - "terminal.integrated.shell.windows": "C:\\Windows\\System32\\bash.exe"
  - based on this https://code.visualstudio.com/docs/editor/integrated-terminal#_windows
4. Attempt to use a maven goal by right-clicking on a goal "validate"

**Expected behavior**
To run
mvn validate -f ${project_path}/pom.xml

**Environments (please complete the following information as much as possible):**
* Version: 1.28.2 (user setup)
* Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
* Date: 2018-10-17T00:23:51.859Z
* Electron: 2.0.9
* Chrome: 61.0.3163.100
* Node.js: 8.9.3
* V8: 6.1.534.41
* Architecture: x64
* Maven for Java: 0.11.1

**Screenshots**
![maven_for_maven_wsl_broken](https://user-images.githubusercontent.com/388745/48275327-3638be00-e413-11e8-9ff4-8705a094ae2b.png)

**Additional context**
It seems the code to detect that WSL is being used is very particular, and thus fails to correctly Identify the environment.

**Comment by Eskibear** [comment]
I'm curious about why your `bash.exe` is located in `System32` folder as you have x64 OS. It should be in `Sysnative` folder, and VSCode has the [same logic](https://github.com/Microsoft/vscode/blob/758206be09ddfaac46e941a77375ec34ed928b4b/src/vs/workbench/parts/terminal/electron-browser/terminalService.ts#L218-L238) to identify available terminals.

**Comment by RobertDeRose** [comment]
It was not, it was located in `sysnative` but the docs say to use `System32`.  I've tried both location in the terminal config, and while VS Code starts the terminal without issue using either, this plugin does not find it in either location.  The changes I made remove that issue.

**Comment by RobertDeRose** [comment]
![maven_for_jave_broken_using_sysnative](https://user-images.githubusercontent.com/388745/48296684-f9e37d00-e467-11e8-903c-19048ad5d221.png)


All I know is in the current logic, it checks if it's WIN32, for whatever reason it evaluates to true, and then it asks for the currentshell, then the list doesn't include `C:\\Windows\\sysnative\\bash.exe`, but even using System32, it doesn't work.

The logic seemed overly complex when it could be solved more simply with a few if clauses.
