### ISSUE TITLE
Chinese Language Support

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode-maven#146]
We have lots of Chinese developers. It would be great if we can provide a localized interface. This issue is to track the effort of building the localization story.
Supporting Chinese is a start. Once the solution is working, we can expand the support to other languages.

**Comment by Eskibear** [comment]
static strings in `package.json` have been localized. 
Todo:
* localize string in TS src code.

**Comment by Eskibear** [comment]
localized by package.nls.languageid.json
