### ISSUE TITLE
Windows platform doesn't support Chinese language

### ISSUE THREAD

**Issue by ZhengJun003** [Microsoft/vscode-maven#148]
**Describe the bug**
In Chinese locale, the command name is not translated.

**To Reproduce**
1. Click F1, input “Configure Display Language” and press "Enter"
2. Set `"locale": "zh-CN"` in locale.json
3. Install extension "Chinese (Simplified) Language Pack for Visual Studio Code"
4. Restart VS code.

**Result:**
![image](https://user-images.githubusercontent.com/41051257/48832178-89b3f000-edb3-11e8-9f28-f3d595132b55.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/41051257/48831537-faf2a380-edb1-11e8-95e0-e69da760b2ce.png)

**Environments:**
 - OS: Windows 10
 - VS Code version: 1.29.1
 - Extension version 0.11.1(Build #275)

**Comment by Eskibear** [comment]
Cannot reproduce. I'm using Windows as my development environment.

**Comment by ZhengJun003** [comment]
Sorry, Cannot reproduce this bug both on build 275 and 276 now, so close it.
