### ISSUE TITLE
Unexpected error report when exit "maven.archetype.generate"

### ISSUE THREAD

**Issue by ZhengJun003** [Microsoft/vscode-maven#149]
**Describe the bug**
There will appear an unexpected error when exit "Maven: Generate from Maven Archetype" of Command Palette.

**To Reproduce**
1. Open Command Palette.
2. Click `Maven: Generate from Maven Archetype`
3. Click `Esc`

**Result**
![image](https://user-images.githubusercontent.com/41051257/48833571-a0a81180-edb6-11e8-9512-a204a7f2b4e3.png)

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10/Linux/OS X]
 - VS Code version: 1.29.1
 - Extension version 0.11.1(Build #275))

**Additional context**
This is a regression issue.

**Comment by Eskibear** [comment]
This is a regression issue.

**Comment by Eskibear** [comment]
please verify build 276

**Comment by ZhengJun003** [comment]
I have verified this bug on build 276. It is fixed, so close it.
