### ISSUE TITLE
please support spring-boot:run

### ISSUE THREAD

**Issue by netroby** [Microsoft/vscode-maven#151]
The plugin does not support `maven spring-boot:run`
![spring boot run](https://user-images.githubusercontent.com/278153/48884733-b2de8a00-ee60-11e8-9f02-521d86775576.png)

can not see spring-boot:run at the context menu

**Comment by Eskibear** [comment]
Plan to support plugin specified goals. See #126 

For the moment, you can use the following as a workaround. 
Click `Custom goals ...`  -> "spring-boot:run", and later re-trigger from `History...`

**Comment by netroby** [comment]
ok，waiting for it .now close this issue
