### ISSUE TITLE
[feature request] - dependency tree

### ISSUE THREAD

**Issue by fssrepository** [Microsoft/vscode-maven#161]
There was a nice feature in Eclipse which showed dependency in a Tree (so individually you would be able to expand and collapse), and at the top, there was a filter bar, where you were able to type text in and showed the tree accordingly.

The effective pom simply unreadable. The visual representation like in the case of Netbeans is unusable. Too much info on the screen at the same time and it's slow also.

Can you make a PR on this, pls.? It would be really helpful to see transitive dependencies, which sometimes either on maven or gradle it makes life difficult.

I don't want to reinstall eclipse for that purpose. Another benefit is, that java based environment like NetBeans, especially on Ubuntu, sucks. (scrolling lags)

**Comment by Eskibear** [comment]
Thanks for your suggestion.

> There was a nice feature in Eclipse which showed dependency in a Tree 

 For the dependency view, you may want to see this extension: https://github.com/Microsoft/vscode-java-dependency 

> The effective pom simply unreadable

https://github.com/redhat-developer/vscode-xml I think this extension is what you want. 


And also I'm working on to show available plugins/goals as mentioned in #126  , and it looks like the following. If you have any suggestion for it, please let me know.  
<img width="414" alt="screen shot 2018-12-06 at 1 34 14 pm" src="https://user-images.githubusercontent.com/2351748/49563706-dd9a0980-f95b-11e8-9ed0-0631155d28d2.png">

**Comment by Eskibear** [comment]
@fssrepository Personally I suggest you keep an eye on the [Java Pack](https://github.com/Microsoft/vscode-java-pack), which provides you [latest information](https://github.com/Microsoft/vscode-java-pack/blob/master/release-notes/v0.5.0.md) of Java related extensions on VSCode.

**Comment by fssrepository** [comment]
@Eskibear - discussion continue on #126

**Comment by Eskibear** [comment]
#126 is for plugin specified goals. If you want to discuss about dependencies, it's better to discuss in [vscode-java-dependency](https://github.com/Microsoft/vscode-java-dependency/issues). 

BTW, I don't see a "tag" in my search bar.

**Comment by fssrepository** [comment]
#Eskibear pls. look at my attached image (top right corner - you can see a "tag" next to the common three search option)

**Comment by Eskibear** [comment]
The "tag" you mentioned is not implemented in VSCode I think. And if it's a feature request of VSCode's UI change, it shouldn't be discussed here. BTW, personally I don't think adding such a "tag" in the search bar is a good thing. 

I think you want to filter the item in the tree view. (Correct me if I'm wrong.) If so, you may want to follow [ this issue ](https://github.com/Microsoft/vscode/issues/50062) for the tree view filtering support just as the Outline behaves.

**Comment by fssrepository** [comment]
Thanks, @Eskibar, the @Gruntfuggly who has added a comment, made the Todo Tree, you should try that out, there are several design features, which is very handy in other parts of the vs code also, where handling trees. The tag button itself has been grabbed from it. It has the same functionality, what I said.

The search bar is a different story, although I wanted to filter in a combination of the text and the tree view itself.

**Comment by fssrepository** [comment]
Can we introduce a new menu next to the "effective pom" called the dependency tree?
mvn dependency:tree? I have no idea how to open the output in vs code to close open the generated tree branches, like in the case of javascript/java etc. Any idea on this?

The filter bar can be the search bar (editor panel ctrl+F), so really no additional effort is needed, just somehow the generated file should be opened. So make it simple.

To be honest, I'm developing maven app in the last decade, but never really used effective pom, but many times dependency tree.

**Comment by Eskibear** [comment]
@fssrepository As I mentioned in https://github.com/Microsoft/vscode-maven/issues/126#issuecomment-446102197 , I'm thinking of the dependency tree experience. Let's continue the discussion here for consistency. 

> Can we introduce a new menu next to the "effective pom" called the dependency tree?

> The filter bar can be the search bar (editor panel ctrl+F), so really no additional effort is needed, just somehow the generated file should be opened. So make it simple.

Yes we can, and it's simple, I can use `mvn dependency:tree -DoutputFile=...` to generate the output, and show the content just as what effective-pom does. 

> I have no idea how to open the output in vs code to expand/collapse the generated tree branches

Me neither. After searching "fold" in the extension marketplace, I don't see a popular which looks good. 

> To be honest, I'm developing maven app in the last decade, but never really used effective pom, but many times dependency tree.

Thanks for the info, our next step is all around the dependency related features.


Yes it's feasible to simply open the output, but I don't want to do that for the moment. As you know, adding a feature is easy, but removing one is tough, esp. when users are used to it. I prefer showing it in the explorer, next to the "Plugins", and providing searching support. Any further suggestion about this?

BTW, for now, a workaround for you is to use `custom goals...`, type  "dependency:tree -DoutputFile=./deps.txt", and open the file.

**Comment by Eskibear** [comment]
Dependency tree feature has been added since 0.16.0, please give it a try. Now it simply execute "dependency:tree" and open the output as a new document in VS Code. The expand/collapse UX now leverages VS Code's native "fold by indentation" . Future UI improvement should be tracked in https://github.com/Microsoft/vscode-maven/issues/261

**Comment by panzippd** [comment]
The Dependency tree could view like idea? and it's useful in resolving dependency conflicts.
![image](https://user-images.githubusercontent.com/27764388/82875904-9dbd4c80-9f6a-11ea-8fb9-766008bdddab.png)

**Comment by Eskibear** [comment]
@panzippd
As far as I know, technically vscode's API is able to support such visualization (e.g. webview API), but it's not prioritiezed and we haven't done any investigation on implemention details yet. 

As I mentioned above, we have #261 to track it. If you want to contribute, or have any useful information to share, you are welcomed to join our discussion in #261 .

**Comment by Melody618** [comment]
hi, @fssrepository 

Since 0.32.0, the dependency tree has been visualized in maven explorer. See https://github.com/microsoft/vscode-maven/issues/261#issuecomment-900852595. And you are able to expand and collapse dependencies now.

and @panzippd, we provide two methods to resolve conflict, one is to exclude the dependency [(demo)](https://github.com/microsoft/vscode-maven/pull/651#issue-685005501) and the other is to set the version [(demo).](https://github.com/microsoft/vscode-maven/pull/659#issue-691282982) Maybe you can give it a try. 

Feedbacks, suggestions, and feature requests are welcome.
