### ISSUE TITLE
javadoc Source code issues 不能加载源代码

### ISSUE THREAD

**Issue by 410919244** [Microsoft/vscode-maven#174]
能否提供一个加载源代码的功能？非常迫切的想要这个功能，很多时候都会需要跟进jar中的源码查看，而且源码一般都有javadoc注释。
Can you provide a function to load source code? It's very urgent to get this functionality. Many times, you need to follow up the source code in jar, and the source code usually has Javadoc annotations.

**Comment by 410919244** [comment]
刚发现有这个功能。。。

**Comment by waiaan** [comment]
> 刚发现有这个功能。。。

这个功能在哪？
