### ISSUE TITLE
vs code picking up the wrong version of a maven dependency for compilation

### ISSUE THREAD

**Issue by emmanueltouzery** [Microsoft/vscode-maven#178]
I tried to open our (large, multi-pom) project, which builds correctly in intellij and on the command-line in visual studio code, but VS code fails compiling it. It appears to pick up the wrong version of a dependency.

**To Reproduce**
Unfortunately I can't share the source code of the project on which I'm having the issue. To open the project I started with an empty visual studio code, then used File->Add folder to workspace, and picked the root folder of the project (there is a pom.xml there, and the project contains subfolders with further pom files).

After opening the project there are multiple build errors, and I see many of them are related to VS Code apparently picking up the wrong version of a dependency.

**Environments (please complete the following information as much as possible):**
 - OS: Linux
 - VS Code version: 1.29.1
 - Extension version 0.11.3

**Screenshots**
the "effective pom" display shows the correct version of the dependency, but the "java dependencies" shows the wrong version:
https://www.dropbox.com/s/5cp93jhmtz19ar6/2018-12-13-074728_1766x845_scrot.png?dl=0

i do have multiple versions of that dependency in my .m2 on my disk, as we have upgraded the dependency through time, but VS code should still pick up the correct one from the pom.xml =>
https://www.dropbox.com/s/qtbnetrri07r7vx/2018-12-13-074950_1815x93_scrot.png?dl=0

**Additional context**

The dependency version (as many others in this project) is defined in the root pom.xml and then replaced in the children pom.xml files:

root pom.xml =>
```
<properties>
        <typescript.generator.core.version>1.30.381</typescript.generator.core.version>
</properties>
```
...

child pom.xml =>
```
        <profile>
            <id>compile-ts</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>cz.habarta.typescript-generator</groupId>
                        <artifactId>typescript-generator-maven-plugin</artifactId>
                        <version>${typescript.generator.core.version}</version>
```

**Comment by Eskibear** [comment]
> but VS code fails compiling it. It appears to pick up the wrong version of a dependency.

> the "effective pom" display shows the correct version of the dependency, but the "java dependencies" shows the wrong version:

Effective-pom is generated by mvn command, while the dependencies are resolved by the language server, and then consumed by [the dependency extension](https://github.com/Microsoft/vscode-java-dependency). 
@yaohaizh Would you take a look?

**Comment by yaohaizh** [comment]
@emmanueltouzery Could you help try to open the same project on the eclipse IDE to see whether this issue happens? It might relate to the m2e which VSCode & Eclipse depend on.

**Comment by emmanueltouzery** [comment]
btw I tried with eclipse version "2018-09 (4.9)".

**Comment by Eskibear** [comment]
This issue was moved to eclipse/eclipse.jdt.ls#941
