### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jihoon-yoo** [Microsoft/vscode-maven#179]
- Issue Type: `Performance`
- Extension Name: `vscode-maven`
- Extension Version: `0.11.3`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/jihoonyoo/vscjava.vscode-maven-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Eskibear** [comment]
Can you attach the file `/Users/jihoonyoo/vscjava.vscode-maven-unresponsive.cpuprofile.txt` ?

**Comment by Eskibear** [comment]
Missing profile info, and dup with #192
