### ISSUE TITLE
Show/Add/Remove dependencies

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode-maven#19]
Inside the explorer view, list the dependencies and allow add/upgrade/remove operations.
This is requested by the users while @yaohaizh already had some changes made at language server side. Please check where the best place for such feature is.

**Comment by yaohaizh** [comment]
Tracking items: https://github.com/eclipse/eclipse.jdt.ls/pull/500

**Comment by Eskibear** [comment]
Now we added a command "add a dependency" as a shortcut for users to search and add artifacts from Maven Central.
