### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by universezy** [Microsoft/vscode-maven#192]
- Issue Type: `Performance`
- Extension Name: `vscode-maven`
- Extension Version: `0.12.1`
- OS Version: `Linux x64 4.4.0-140-generic`
- VSCode version: `1.30.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/zengyu/vscjava.vscode-maven-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Eskibear** [comment]
Can you please also attach the file mentioned in the description for us to diagnose?

**Comment by frogfans** [comment]
> Can you please also attach the file mentioned in the description for us to diagnose?

Sorry, my project files have been changed, so I forget what cause the issue.
While I was coding on VSCode, it show a popup window in the lower right corner, then I clicked the button and turn to this webpage, I committed this issue.

**Comment by Eskibear** [comment]
I’m closing it.
If you can find  /home/zengyu/vscjava.vscode-maven-unresponsive.cpuprofile.txt in your machine and are willing to attach it here, please do it and reopen the issue, and we’ll take an investigation.

**Comment by frogfans** [comment]
[vscjava.vscode-maven-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-maven/files/2693548/vscjava.vscode-maven-unresponsive.cpuprofile.txt)
@Eskibear I find it in my trash box

**Comment by Eskibear** [comment]
In v0.14.0, we removed some operations which might have potential risk of high cpu load. I'm closing it now.
