### ISSUE TITLE
Better experience of generating projects

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-maven#20]
When generating projects from archetypes, users have to know exactly what archetype to use. But Maven central does not have a good mechanism for users to discover what's best for their needs. Download numbers are hidden so we cannot tell how popular one package is. The whole experience is frustrating.

Suggest improving the experience by providing a better recommendation mechanism for users to find archetypes. We actually can maintain a list of download numbers initiated from our extension and do recommendation based on that. This is only one way to consider.

The recommendation can also apply to all the scenarios when users look for dependencies.

**Comment by Eskibear** [comment]
currently according to the usage data, top 10 popular archetypes are listed in the first page.
