### ISSUE TITLE
Path to mvn incorrect when wsl.conf changes the root mount

### ISSUE THREAD

**Issue by rdcoe** [Microsoft/vscode-maven#206]
**Describe the bug**
The maven plugin fails to execute if the /etc/wsl.conf changes the root mount point, because the plugin expects /mnt/ as the mount point.

**To Reproduce**
1. edit /etc/wsl.conf and change the root mount:

> [automount]
> root = /
> options = "metadata"

2. save wsl.conf and exit the bash shell
3. reopen the bash shell and confirm the mount point no longer references /mnt:

> $ pwd
> rcoe@SKELETOR:/d/cygwin64/home/rcoe$ pwd
> /d/cygwin64/home/rcoe

4. set the path to mvn in the user/workspace settings:

> Maven › Executable: Path
> Specifies absolute path of your mvn executable. When this value is empty, it tries using 'mvn' or 'mvnw' according to value of 'maven.executeble.preferMavenWapper'. Note that a relative path is not suggested, but if you do specify one, the absolute path will be resolved from your workspace root folder (if exists).
> 
> d:/cygwin64/home/rcoe/apache-maven-3.5.2/bin/mvn
> 
> 

5. execute the maven project plugin, e.g., vertx:run

> rcoe@SKELETOR:/d/cygwin64/home/rcoe/git/linkEd$ "/mnt/d/cygwin64/home/rcoe/apache-maven-3.5.2/bin/mvn" vertx:run -f "/mnt/d/cygwin64/home/rcoe/git/linkEd/chatsrv/pom.xml"
> -bash: /mnt/d/cygwin64/home/rcoe/apache-maven-3.5.2/bin/mvn: No such file or directory
> 

**Expected behavior**
The mvn path should refer to the correct mount point for wsl, i.e., / **not** /mnt/

> rcoe@SKELETOR:/d/cygwin64/home/rcoe/git/linkEd$ which mvn
> /d/cygwin64/home/rcoe/apache-maven-3.5.2/bin/mvn

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: 1.30.1
 - Extension version: 0.12.1

**Comment by Eskibear** [comment]
I didn't know the /etc/wsl.conf feature, and I find it in the [official docs](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#set-wsl-launch-settings). Yes, it makes sense that we should support this. 

What's in my mind now is:
1. read the mount point from /etc/wsl.conf.
  * when? on extension activation or on command execution?
  * how? currently the extension simply sends commands to the integrated terminal, without knowing what's going on in the terminal.
2. transform the path.

**Comment by rdcoe** [comment]
Less elegant but also less work would be to offer another field in the settings to specify the mount point, potentially read-only unless wsl bash is set as the default terminal.  It might even be possible to interrogate that file for the mount setting when the user sets the wsl sets the Code terminal shell to use.  I only offer this as a quick fix, since it's a fragile approach.  But considering the wsl.conf is only available in Insider builds, who knows whether Windows might add support to interrogate it through an SDK in the future.  Plus, it's unlikely a Code user would be using an environment that they haven't configured if the default mount point was changed.  So on seeing a path error when using the plugin, the user should know how to change it, if the plugin error message included the setting.

**Comment by Eskibear** [comment]
**wslpath** is for this, inspired by https://github.com/jdneo/vscode-leetcode/blob/master/src/utils/wslUtils.ts#L12-L17

#### default 
```bash
$ wslpath -u C:\\Windows
/mnt/c/Windows
$ wslpath -w /mnt/c/Windows
C:\Windows
```

#### set the `root = /`
```bash
$ cat /etc/wsl.conf
[automount]
root = /
options = "metadata"
$ wslpath -u C:\\Windows
/c/Windows
$ wslpath -w /c/Windows
C:\Windows
```

**Comment by Eskibear** [comment]
@rdcoe v0.14.0 has been shipped. It should work now.
