### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AbhiY98** [Microsoft/vscode-maven#242]
- Issue Type: `Performance`
- Extension Name: `vscode-maven`
- Extension Version: `0.14.1`
- OS Version: `Linux x64 4.15.0-45-generic`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/abhiy13/vscjava.vscode-maven-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Eskibear** [comment]
duplicate with #241 , and please attach the cpuprofile in that issue. Thanks.
