### ISSUE TITLE
Custom goal from command palette showing error

### ISSUE THREAD

**Issue by DiazBejaranoD** [Microsoft/vscode-maven#243]
**Describe the bug**

If I try to insert a custom goal from right click on sidebar, it works perfectly. However when I try to use the command palette, if says: 
Command "maven.goal.execute" fails. command 'maven.goal.Custom goals ..." not found.

**To Reproduce**

1. Cmd+shift+p
2. maven: Execute commands
3. Select your maven project
4. custom
 - ERROR popup -

**Expected behavior**

Same working behavior as using from side bar

**Environments: **
 - OS: OS X Mojave
- VS Code version: 1.30.2 
 - Extension version 0.14.1

**Screenshots**

![image](https://user-images.githubusercontent.com/5337376/52177598-8bdaf780-27c3-11e9-9cb3-909d208e6ef4.png)

![image](https://user-images.githubusercontent.com/5337376/52177587-63eb9400-27c3-11e9-8b50-c7e26c2e2587.png)

Bad behavior - expected fix:

![image](https://user-images.githubusercontent.com/5337376/52177590-72d24680-27c3-11e9-97fd-5071814dd83f.png)

![image](https://user-images.githubusercontent.com/5337376/52177594-81206280-27c3-11e9-9cb1-9d6453904439.png)

**Comment by Eskibear** [comment]
Confirmed to be a regression bug, will be fixed in #244 .

**Comment by DiazBejaranoD** [comment]
Great to know @Eskibear , thanks!

**Comment by Eskibear** [comment]
@DiazBejaranoD The fix has been shipped with v0.14.2
