### ISSUE TITLE
cannot be resolved ${os.detected.classifier}

### ISSUE THREAD

**Issue by wensioness** [Microsoft/vscode-maven#246]
${os.detected.classifier} cannot be resolved
at eclipse https://github.com/trustin/os-maven-plugin  maybe available

project address:  https://github.com/netty/netty.git

 - OS: [Windows 10]
 - VS Code version: [1.31.0]
 - Extension version [0.14.0]

**Screenshots**
![image](https://user-images.githubusercontent.com/13445935/52623878-57b0b680-2ee8-11e9-9e0a-32684f2d9a18.png)
![image](https://user-images.githubusercontent.com/13445935/52624198-27b5e300-2ee9-11e9-92c1-1de5ac3dfda6.png)

**Comment by Eskibear** [comment]
Redirected to https://github.com/redhat-developer/vscode-java/issues/795
