### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by JRProtheus** [Microsoft/vscode-maven#249]
- Issue Type: `Performance`
- Extension Name: `vscode-maven`
- Extension Version: `0.14.2`
- OS Version: `Linux x64 4.15.0-45-generic`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/jrprotheus/vscjava.vscode-maven-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Eskibear** [comment]
Thanks, let's track it in #241 , please also attach the **cpuprofile** there to provide more information.
