### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by fourpastmidnight** [Microsoft/vscode-maven#251]
[vscjava.vscode-maven-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-maven/files/2870464/vscjava.vscode-maven-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vscode-maven`
- Extension Version: `0.14.2`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.32.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\cshea\vscjava.vscode-maven-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Eskibear** [comment]
Thanks for your information, let's track it together in #241
