### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Liliana99** [Microsoft/vscode-maven#252]
- Issue Type: `Performance`
- Extension Name: `vscode-maven`
- Extension Version: `0.14.2`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/MyDirectory/vscjava.vscode-maven-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Eskibear** [comment]
Could you attach your `/Users/MyDirectory/vscjava.vscode-maven-unresponsive.cpuprofile.txt` for more information? thanks.
