### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by wumwew** [Microsoft/vscode-maven#254]
- Issue Type: `Performance`
- Extension Name: `vscode-maven`
- Extension Version: `0.14.2`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.32.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\suriy\vscjava.vscode-maven-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Eskibear** [comment]
Could you attach your `C:\Users\suriy\vscjava.vscode-maven-unresponsive.cpuprofile.txt` for more information? thanks.
