### ISSUE TITLE
Add "favorites" section for mvn configurations

### ISSUE THREAD

**Issue by andresbm05** [Microsoft/vscode-maven#259]
It would be nice to be able to pre-configure run configurations and have a section where you could execute those run configurations.

The "History" feature works nice but sometimes it's not easy to find out the command you want to launch. Maybe it could be a section similar to Eclipse "run configurations..." where you can define run configurations, set them an alias and easily find them on a single place.

When you have a big project with many subprojects and each with many plugins, finding the proper execution on "Maven projects" section is harder than just typing it once and save it on a "Favorites" section.

**Comment by Eskibear** [comment]
It looks almost the same feature mentioned in #72 , you may take a look at https://github.com/Microsoft/vscode-maven/issues/72#issuecomment-406840720 , see if it's a good experience for you?

**Comment by andresbm05** [comment]
Yes, something like that would work.

**Comment by Eskibear** [comment]
@andresbm05 It has been released. Please try it in v0.15.0
