### ISSUE TITLE
Better visualization of dependency tree

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-maven#261]
It's convenient to for conflict resolving. 

Now I have to execute "mvn dependency:tree -Doutput..." to print the tree to a file, and then open it in VSCode for further analysis. 
I think a better visualization with conflicts highlighted would be very helpful.

**Comment by Eskibear** [comment]
My first thought is to use a "WebView" UI, open in another column

**Comment by Eskibear** [comment]
Now it's only plain text generated by command `dependency:tree`. It's better to define a new file schema, and add intellisense for that, e.g. highlighting conflicts.

**Comment by mukteshkrmishra** [comment]
Any updates on this?

**Comment by Eskibear** [comment]
Not yet, I don't have bandwidth for it recently. BTW, discussion, suggestions and PRs are welcome.

**Comment by mukteshkrmishra** [comment]
I can work on this.

**Comment by Eskibear** [comment]
@mukteshkrmishra Are you able to show dependencies successfully by right clicking the project? I just find a bug that breaks the feature all the time...

**Comment by mukteshkrmishra** [comment]
Not yet successful.

**Comment by Eskibear** [comment]
Got it. And it has been fixed in [#398](https://github.com/microsoft/vscode-maven/pull/398/files#diff-fac897be847e65eb786e16505b0a9711R37-R38) and will be included in the next release.

**Comment by mukteshkrmishra** [comment]
Awesome @Eskibear . Thank You

**Comment by brunovieira97** [comment]
Any progress on this? I noted the menu for this in VS Code removes vertical tree lines (pipes) too...

**Comment by Eskibear** [comment]
Since 0.32.0, dependency tree has been visualized in maven explorer.

**Comment by Melody618** [comment]
hi, @mukteshkrmishra @brunovieira97 

Since 0.32.0, the dependency tree has been visualized in maven explorer. And it looks like below.

![Snipaste_2021-08-18_14-22-36](https://user-images.githubusercontent.com/25446374/129848036-b7770d72-8817-4f10-904b-ff6a86fc8cc6.png)


If you are still interested in dependency visualization, maybe you can give it a try. Feedbacks, suggestions, and feature requests are welcome.
