### ISSUE TITLE
Typo of maven favorite command in TestPlan.md

### ISSUE THREAD

**Issue by ZhengJun003** [Microsoft/vscode-maven#270]
**To Reproduce:**
1. Specify a favorite command in settings, e.g.
```
    {
        "maven.terminal.favorites": [
            {
                "alias": "full-build without tests",
                "value": "clean package -DskipTests"
            }
        ]
    }
```
2. Right-click on project item, click `Favorite ...`
3. Click a favorite commands in a drop-down list.

**Environments:**

 - OS: Windows 10
 - VS Code version: 1.31.1
 - Extension version: Build 9

**Screenshots:**

![image](https://user-images.githubusercontent.com/41051257/53778177-d7093700-3f36-11e9-9299-1f9b54a7d7e6.png)

![image](https://user-images.githubusercontent.com/41051257/53778181-dc668180-3f36-11e9-8343-36b81061f56f.png)

**Comment by ZhengJun003** [comment]
Verify TestPlan.md. the issue was fixed, so close this issue.

**Comment by waltenesjr** [comment]
change value for command

**Comment by RavenBlood7** [comment]
As @waltenesjr suggests, exchange "value" with "command":

`    {
        "maven.terminal.favorites": [
            {
                "alias": "full-build without tests",
                "command": "clean package -DskipTests"
            }
        ]
    }`
