### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by KOUTOUANN** [Microsoft/vscode-maven#272]
- Issue Type: `Performance`
- Extension Name: `vscode-maven`
- Extension Version: `0.15.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\james koutouan\vscjava.vscode-maven-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Eskibear** [comment]
Can you attach the cpuprofile for more information? Thanks.
