### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by LierJeo** [Microsoft/vscode-maven#273]
[vscjava.vscode-maven-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-maven/files/2949569/vscjava.vscode-maven-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vscode-maven`
- Extension Version: `0.15.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.32.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\39621\vscjava.vscode-maven-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load
[vscjava.vscode-maven-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-maven/files/2949571/vscjava.vscode-maven-unresponsive.cpuprofile.txt)

**Comment by Eskibear** [comment]
Can you attach the cpuprofile for more information? Thanks.

**Comment by LierJeo** [comment]
> Can you attach the cpuprofile for more information? Thanks.

   Sorry I use git first time. File has been upload
