### ISSUE TITLE
The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by LeonKwok0** [Microsoft/vscode-maven#277]
**Describe the bug**
i use macOS majove  and maven 3.5.
i met the problem when i try to run the command ``maven.archetype.update`` through cmd+shift+p shortcut. 
it mentioned me ``Command "maven.archetype.update" fails. The "path" argument must be of type string. Received type undefined`` 

similar problem when i run ``maven.archetype.generate``

``Command "maven.archetype.generate" fails. Cannot read property 'length' of undefined`` returned through pop dialog 

**To Reproduce**
i update my maven version. before that this extension works ok. i think it is this update recur problems .   i use brew reinstalled maven. 
but, i am sure that ``mvn``  command works ok in Terminal 

**Expected behavior**

**Environments (please complete the following information as much as possible):**
 - OS: [macOS]
 - VS Code version: [1.32.3]
 - Extension version [0.15.0]

**Comment by Eskibear** [comment]
It looks exactly the same issue with #274 .

Are you running the commands without any workspace or folder open? Open a folder first, see if the issue still exists. If it's gone, I suppose it's because of a potential NPE which is fixed by PR #276 but not released yet.  Please let me know the result.

**Comment by LeonKwok0** [comment]
> It looks exactly the same issue with #274 .
> 
> Are you running the commands without any workspace or folder open? Open a folder first, see if the issue still exists. If it's gone, I suppose it's because of a potential NPE which is fixed by PR #276 but not released yet. Please let me know the result.

thanks for your help. i opened a maven project created before and everything works ok ....

**Comment by Eskibear** [comment]
v0.15.1 has been released with the fix.
