### ISSUE TITLE
cannot create a new maven project from archetype

### ISSUE THREAD

**Issue by shaka0919** [Microsoft/vscode-maven#279]
version of extension: 0.15.1
version of vscode:1.32.3
OS: macOS Mojave 
while i was tring to create a new maven project from archetype 'quickstart'
a message popped up by Maven for java:
"Command "maven.archetype.generate" fails. Cannot read property 'length' of undefined"

could any guys help to resolve this issue?

**Comment by Eskibear** [comment]
Confirmed to be a bug. It's another NPE when there's no open workspace.

We'll fix it soon, and the workaround is to open any folder first, before you create a new Maven project.

**Comment by shaka0919** [comment]
> while i was tring to create a new maven project from archetype 'quickstart'
> a message popped up by Maven for java:
> "Command "maven.archetype.generate" fails. Cannot read property 'length' of undefined"
> 
> could any guys help to resolve this issue?



> What's the version of your Maven extension? See #277 , it should have been fixed in v0.15.1

more info updated.

**Comment by Eskibear** [comment]
The fix for the NPE has been released just now. You can update the extension to v0.15.2.  Let me know if it works for you.

**Comment by shaka0919** [comment]
> Confirmed to be a bug. It's another NPE when there's no open workspace.
> 
> We'll fix it soon, and the workaround is to open any folder first, before you create a new Maven project.

Thanks. it worked!

**Comment by Eskibear** [comment]
Closing as fixed.
