### ISSUE TITLE
Error Couldn't find a compatible version of Maven for Java

### ISSUE THREAD

**Issue by gizdolok** [Microsoft/vscode-maven#28]
When trying to install the plugin, the following message always appears

> 
Couldn't find a compatible version of Maven for Java with this version of Code.
> 

I downgraded my maven from version 3.5.3 to 3.5.2 but didn't help.

Has anyone having the same issue?

**Comment by Eskibear** [comment]
I suppose it has nothing to do with the version of you Maven. 

> Couldn't find a compatible version of Maven for Java with this version of Code.

It's the version of the extension v.s. the version of your VS Code.
Can you share the version of your VS Code? ( in **Help** tab -> **About** )

e.g.
```
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:04:09.886Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32
```

**Comment by sanjaykumar2763** [comment]
I'm facing the same issue.
Maven : 3.1.0
Java : 1.8.0_121

Visual studio code
Version: 1.10.2
Shell: 1.4.6
Renderer: 53.0.2785.143
Node: 6.5.0

I have set maven path in both system environment variables as well as user settings. Still no luck.

**Comment by jeffgbutler** [comment]
That version of VS Code is over a year old at this point.  Try updating to the current version.

This extension requires VS code version 1.18 or higher.

**Comment by Eskibear** [comment]
@gizdolok @sanjaykumar2763 
This extension shows a tree view in sidebar, and the feature is only available on VS Code 1.18.0 or later versions.

May I know the reason why you are still using VS Code with such old versions?

**Comment by sanjaykumar2763** [comment]
@Eskibear i'm using that in my office machine. I have no control over that to update.

**Comment by Eskibear** [comment]
@sanjaykumar2763 Thanks for your information, we've never thought about this scenario before.

I think you might want to convince your IT administrators to upgrade the VS Code to the latest version, there have been lots of fancy features in newer versions.

**Comment by Eskibear** [comment]
Cannot fix here. Simply updating VSCode version should work.
