### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by DarkoR12** [Microsoft/vscode-maven#303]
- Issue Type: `Performance`
- Extension Name: `vscode-maven`
- Extension Version: `0.16.0`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.0`

[vscjava.vscode-maven-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-maven/files/3053582/vscjava.vscode-maven-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Eskibear** [comment]
![image](https://user-images.githubusercontent.com/2351748/55848074-5e714800-5b7e-11e9-8edd-30273e3b339a.png)

Sorry I don't find any useful info in cpuprofile.  And the function `convertCompletionItem` doesn't seem to be related with this extension. Probably it's from another extensions. See more details [here](https://github.com/Microsoft/vscode-java-pack/issues/81#issuecomment-476457431).

If you still suffer from the issue, feel free to re-open with new cpuprofiles attached.
