### ISSUE TITLE
can't import dependency from pom.xml

### ISSUE THREAD

**Issue by bonaluo** [Microsoft/vscode-maven#314]
Issue Type: <b>Bug</b>

i use a spring-boot-starter-security,but vscode didn't import spring-secury-config into project ,when i use package , i open the jar and open the lib folder i can find spring-boot-security in it ,but in the java file,it was an error that can find "org.springframework.security.config.*"

Extension version: 0.16.2
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|11.91GB (1.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Eskibear** [comment]
It looks like a vscode-java/jdtls/m2e issue according to description, @yaohaizh could you take a look?

**Comment by yaohaizh** [comment]
@bonaluo Could you share more info about your project and installed extensions?

**Comment by bonaluo** [comment]
I use the project from https://github.com/spring-guides/gs-securing-web.git, most of my extensions come from the vscode's recommendation and here is the list
![批注 2019-04-26 143642](https://user-images.githubusercontent.com/27731323/56787995-c5eeef00-6830-11e9-9d71-5831985a500c.jpg)
![批注 2019-04-26 143656](https://user-images.githubusercontent.com/27731323/56787996-c5eeef00-6830-11e9-8995-a2070e992c52.jpg)

**Comment by yaohaizh** [comment]
@bonaluo  There are two projects here: intial & complete. The complete has all the dependency declared while the complete doesn't have enough information. You need look at the pom.xml & build.gradle to find the difference. 

Since these two projects have the same name, the language server take it as one project. You need open `initial` or `complete` instead in vscode for the correct behavior.

**Comment by bonaluo** [comment]
i will try ，thank you for your help

**Comment by bonaluo** [comment]
I just found out what the problem is，i haven't used gradle before. When i add a new dependency in pom.xml, i have to add it to build.gradle too.

**Comment by yaohaizh** [comment]
You can disable gradle in the vscode java settings. In VSCode Java, gradle recognized first than maven. 
```json
"java.import.gradle.enabled": false,
```

**Comment by bonaluo** [comment]
Thank you for your kind answer.

**Comment by bonaluo** [comment]
There is another problem,the setting "java.import.gradle.enabled": false doesn't work.
