### ISSUE TITLE
Dependencies are not resolved

### ISSUE THREAD

**Issue by jeusdi** [Microsoft/vscode-maven#315]
I'm running against an issue when maven or Java Language Server (I don't know) tries to get dependencies project dependencies:

![imagen](https://user-images.githubusercontent.com/941639/56789993-98d81780-6803-11e9-8f14-4b3b4bcca628.png)

Nevertheless, when I'm using maven from terminal launching for example `mvn -pl rep-digital-api clean compile -DskipTests`:

![imagen](https://user-images.githubusercontent.com/941639/56790282-7397d900-6804-11e9-87be-3007cd76a570.png)

**Expected behavior**
Dependencies are resolved inside vscode.

**Environments (please complete the following information as much as possible):**
 - OS: Ubuntu 18.04 (bionic)
 - VS Code version: 1.33.1
 - Extension version 0.16.2

This is my `~/.m2/settings.xml` file content:

```
<settings>

  <proxies>
   <proxy>
      <active>true</active>
      <protocol>http</protocol>
      <host>10.49.1.1</host>
      <port>8080</port>
    </proxy>
  </proxies>

  <profiles>
   <profile>
        <id>defaultProfile</id>
        <activation>
            <activeByDefault>true</activeByDefault>
        </activation>
        <repositories>
            <repository>
                <id>canigo</id>
                <url>https://sic.ctti.extranet.gencat.cat/nexus/content/groups/canigo-group-maven2/</url>
                <snapshots>
                    <enabled>true</enabled>
                    <updatePolicy>always</updatePolicy>
                </snapshots>
                <releases>
                    <enabled>true</enabled>
                </releases>
            </repository>
        </repositories>
        <properties>
            <downloadSources>true</downloadSources>
            <downloadJavadocs>true</downloadJavadocs>
        </properties>
    </profile>
  </profiles>
</settings>
```

It seems that it's not able to resolve artifacts from `https://sic.ctti.extranet.gencat.cat/nexus/content/groups/canigo-group-maven2` repository.

I added repository certificate to truststore using:

    keytool -import -trustcacerts -alias ctti-maven -file ctti.cer -keystore $JAVA_HOME/jre/lib/security/cacerts

I don't quite figure out whether the problem running around that issue... I don't know...

JAVA_HOME is pointing to: 

![imagen](https://user-images.githubusercontent.com/941639/56792137-2a965380-6809-11e9-94bb-3205f4b370a9.png)

**Comment by amrsalama** [comment]
@jeusdi What was your solution?
