### ISSUE TITLE
Support pom filenames other than pom.xml

### ISSUE THREAD

**Issue by jridgewell** [microsoft/vscode-maven#316]
**Describe the bug**

Closure Complier uses an unusual `pom.xml` hierarchy:

- /pom.xml
  - /externs/pom.xml
  - /pom-gwt.xml
  - /pom-main.xml
    - /pom-linter.xml
    - /pom-main-unshaded.xml
    - /pom-main-shaded.xml

The `/externs/pom.xml` project is picked up just fine, but none of the rest are. I think this is because it's only looking for the explicit filename "pom.xml".

Further the submodule detection always [appends](https://github.com/Microsoft/vscode-maven/blob/master/src/explorer/model/MavenProject.ts#L67) "pom.xml" to the module filepath which generates things like "/pom-min.xml/pom.xml". That's hurts, too.

**To Reproduce**

1. Clone https://github.com/google/closure-compiler
2. Open it with vscode
3. Observe Maven Projects tree only includes "pom.xml" files

**Expected behavior**

All projects should be detected.

**Environments (please complete the following information as much as possible):**
 - OS: OS X
 - VS Code version: 1.31.1
 - Extension version 0.16.2

**Additional context**

A configurable pom filename glob would probably fix this. That, and detecting if the module filepath includes an explicit file extension, implying it's a file and not a directory that contains a pom.xml file.

**Comment by Eskibear** [comment]
Thanks for reporting this, and there are two work items can be formed. 
- add a setting entry like "maven.pomfile.globpattern", it can be a workspace setting. Currently it's hardcoded as `**/pom.xml`, and I think it's easy to make the change. See [this line](https://github.com/Microsoft/vscode-maven/blob/204d7e698934cc3b2e64b6461fed2e064a28fc44/src/utils/Utils.ts#L103).
- in submodule detection, add extra logic to determine it's a folder or a file, so we can append "pom.xml" to the path accordingly. E.g. /pom-min.xml is a file, no need to append "pom.xml". It's also feasible via NodeJS `fs.lstat` API.

Are you willing to contribute?

**Comment by Eskibear** [comment]
Great appreciation for your contribution. I'll also enable auto-completion for `**/*.xml`. It's planned to be shipped in v0.17.0, together with some other improvements.

**Comment by Eskibear** [comment]
released
