### ISSUE TITLE
'Create Maven Project' doesn't work correctly when the directory has brackets on Windows

### ISSUE THREAD

**Issue by FacundoCerezo** [microsoft/vscode-maven#324]
**Describe the bug**
This happens when one tries to create a new Maven Project through the Java Overview page, selects an archetype and selects a directory with brackets in the path. The Terminal uses Powershell.

As Powershell takes brackets as a wildcard when doing a `cd` in the Terminal, VS Code won't successfully change directory in the Terminal, showing an error. As a result, it will try to generate a Maven Project in my user path (`C:\Users\User`).

**To Reproduce**
1. Go to 'Java Overview' page
2. Click on 'Create a Maven Project...'
3. Select any archetype
4. Select a directory path with brackets (e.g: `C:\dev\java\projects_[2019]\example`)
5. See "directory doesn't exist" error in PowerShell 

**Expected behavior**
VS Code should successfully change directory to that path, or at the very least, abort the operation to avoid creating projects in a wrong path.

**Possible solution**
- Use -LiteralPath flag with cd command
-- not working in Powershell < 3 

**Environments (please complete the following information as much as possible):**
- Operating System: Windows 10 1809 (17763.475) [es-AR]
- Visual Studio Code version: 1.33.1
- Extension version: 0.16.2

**Comment by Eskibear** [comment]
> Use `-LiteralPath` flag with cd command

It causes regressions for Powershell 2.x users as you mentioned. I myself prefer to escape special characters for Powershell. It is a little bit dirty, but effective and safe.

**Comment by FacundoCerezo** [comment]
Closing issue as it was resolved in #326.
