### ISSUE TITLE
Can't work on spring-hadoop-samples project

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/vscode-maven#333]
**Describe the bug**
prompt out a notification: no such file or directory.
Maven project explorer can't show this project: [spring-hadoop-samples](https://github.com/spring-projects/spring-hadoop-samples.git)

**To Reproduce**
1. Clone [spring-hadoop-samples](https://github.com/spring-projects/spring-hadoop-samples.git)
2. Open spring-hadoop-samples
3. See error

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10/OS 10.12.6
 - VS Code version: 1.34.0
 - Extension version 0.17.0 (buildId=9514205)

**Screenshots**
![image](https://user-images.githubusercontent.com/41051257/58079525-c6866580-7be3-11e9-9533-e2626cebd9b8.png)

**Comment by Eskibear** [comment]
Introduced by #317
