### ISSUE TITLE
Maven projects explorer can refresh automatically after setting "maven.pomfile.globPattern"

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/vscode-maven#334]
## Suggestion

when setting "maven.pomfile.globPattern", it can refresh automatically in maven projects explorer.

**Comment by Eskibear** [comment]
Whenever user changes a setting, we should determine which features are affected, and notify users about that. And users can decide whether to reload window to apply the changes. 

This UX improvement should be implemented in a general approach, i.e. some config listeners
