### ISSUE TITLE
Generate from archetype fails on Windows if default shell is not explicitly set.

### ISSUE THREAD

**Issue by jasonjoh** [microsoft/vscode-maven#337]
**Describe the bug**
If the default Windows shell is not explicitly set in user or workspace settings, the **Maven: Generate from Maven Archetype** command fails with the error **Command "maven.archetype.generate" fails. Cannot read property 'endsWith' of null**.

![image](https://user-images.githubusercontent.com/8966342/59058115-e9fb1280-8869-11e9-9f07-923c9e4e57cb.png)

**To Reproduce**
Steps to reproduce the behavior (using VS Code Insiders, have not tested on non-Insiders):
1. Verify that the `terminal.integrated.shell.windows` setting is not present in both your user and workspace settings.json files. This setting is optional and if not present, VS Code defaults to PowerShell.
1. CTRL + SHIFT + P, Maven: Generate from Maven Archetype
2. Select any archetype, I tried both **maven-archetype-quickstart** and **maven-archetype-webapp**. 
3. Select a destination folder

**Expected behavior**
It should not fail and detect the default. At the very least it should give an error indicating that you need to set this setting.

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: 1.36.0-insiders
 - Extension version 0.17.0

**Comment by rose-line** [comment]
Same problem with same error here when updating from 1.34 to 1.35 (W10, Extension 0.17.0, Maven 3.6.1).
Was working without **terminal.integrated.shell.windows** explicitly set on 1.34.
Now I have to use the workaround of setting it explicitly to make **Generate from Maven Archetype** work on 1.35.

**Comment by Tyriar** [comment]
Some history on the decision behind this in https://github.com/microsoft/vscode/issues/74233

The recommendation is to fill in the default yourself, a simple fix would be to just use cmd.exe on Windows and bash on Linux and macOS.

**Comment by bigtfromaz** [comment]
@Tyriar I will try setting terminal.integrated.shell.windows as a workaround but it's not a solution to the problem.  It appears that taking the default no longer works.  Avoiding the use of PowerShell on Windows is not a "fix", it's a constraint.

**Comment by Tyriar** [comment]
@bigtfromaz that's the simplest fix, the fix I recommended to Python is to copy how vscode evaluates the default shell which is a little more involved (see the linked issue).

**Comment by bigtfromaz** [comment]
I did read the thread.  Perhaps the upgrade process could have told us about the issue and offered to set a default.  It would have saved us all some time.

**Comment by rose-line** [comment]
OK, I will continue to use the 'set default' workaround in the meantime, but the Maven for Java extension guys should release a fix soon, because it doesn't look very nice from the outside (I'm trying to evangelize about VSCode over Eclipse, this definitely doesn't help ;)

**Comment by Tyriar** [comment]
FYI I created https://github.com/microsoft/vscode/issues/75091 to have a proper fix for this, in the meantime this extension should fill/guess the default like vscode-python does.

**Comment by Eskibear** [comment]
A new version v0.17.1 has been released with the ability to guess default shell, serving as a workaround before the upstream issue get resolved.

**Comment by Tyriar** [comment]
VS Code Insiders now has a `vscode.env.shell` API which gives this https://github.com/microsoft/vscode/issues/75091

**Comment by Eskibear** [comment]
looks like the API is stable now, we should remove the worksaround.

**Comment by Eskibear** [comment]
fixed in #381
