### ISSUE TITLE
Command "maven.goal.clean" fails. Cannot read property 'endsWith' of null

### ISSUE THREAD

**Issue by zhoudotnet** [microsoft/vscode-maven#338]
Issue Type: <b>Bug</b>

It returned this error message in vscode 1.35.0
Command "maven.goal.clean" fails. Cannot read property 'endsWith' of null

But it is OK in vscode 1.34

Extension version: 0.17.0
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 6.1.7601

**Comment by zhoudotnet** [comment]
Right click the project in "Maven Projects" tab, select "clear" command, it returned error:
Command "maven.goal.clean" fails. Cannot read property 'endsWith' of null

**Comment by Eskibear** [comment]
Upstream issue from vscode. Please manually set `terminal.integrated.shell.windows` as a workaround. See #337
