### ISSUE TITLE
Command "maven.archetype.generate" fails. Cannot read property 'endsWith' of null

### ISSUE THREAD

**Issue by Redik87** [microsoft/vscode-maven#341]
**Environment:**

- VS Code Version: 1.35
- Extension Version: 0.17.0
- JDK Type & Version: 11
- OS Type & Version: Windows 10 1903

**Step to Reproduce:** Create new Maven project.

**Related Issues:** The error appeared after updating the Visual Studio Code to version 1.35

**Comment by Eskibear** [comment]
Upstream issue from vscode. I'll provide a temp fix for it in 0.17.1. Before that you can manually set `terminal.integrated.shell.windows` as a workaround. 

See #337

**Comment by simon1749** [comment]
I received a similar error message when I tried to create maven-archetype-quickstart project:
"Command "maven.archetype.generate" fails. undefined."

VS Code Version: 1.63.2
Maven for Java Extension Version: 0.34.2
JDK Version: 17.0.1
OS: Windows 10 Pro,  Version: 21H2
Maven Version: 3.84

**Comment by Eskibear** [comment]
anything in output channel?

**Comment by simon1749** [comment]
> anything in output channel?

No, nothing.
