### ISSUE TITLE
Maven projects don't open correctly using "File -> Open Workspace..."

### ISSUE THREAD

**Issue by smoyer64** [Microsoft/vscode-maven#35]
If I open a folder containing a multi-module Maven project (well ... all my projects are multi-module), VS Code correctly parses the POM files and sets up the classpath.  If I then save the environment as a workspace I should, in theory, be able to load that environment using "Open Workspace...".  Instead VS Code seems to be missing some part of the previous workspace's configuration.   It's pretty common for the classpath to be incomplete - clicking on some files results in a notification indicating that my Java file isn't on the classpath so only syntax checking will be performed.  I originally noticed this because if the classpath doesn't include a test class, running the tests from the test explorer results in an error pop-up that says "Reduce of empty array with no initial value"

The saved workspace doesn't have anything surprising in it - though I'll admit I don't know what it should look like.  Since it's very small, here is the contents of that file:

```
{
	"folders": [
		{
			"path": "/home/smoyer1/git/selesy/hibp-client"
		}
	],
	"settings": {
		"java.configuration.updateBuildConfiguration": "automatic"
	}
}
```

I'm using:

-   VS Code version 1.21.1
-   Maven for Java version v0.6.0
-   mvn -version returns:

```
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-116-generic", arch: "amd64", family: "unix"
```

**Comment by Eskibear** [comment]
According to your description, I think it has nothing to do with this extension. 

In fact the **Language support for Java** extension (I guess you already have installed it) uses `m2e` to build maven projects, and then provide language support like syntax, autocompletion, etc.

Things like syntax, classpath are probably related to https://github.com/redhat-developer/vscode-java, and the test stuff is related to https://github.com/Microsoft/vscode-java-test. (which depends on the redhat.java extension)

BTW, I just cloned your repo `selesy/hibp-client` and did the same thing, but just could not reproduce the issue. And my settings looks like:
```
{
	"folders": [
		{
			"path": "hibp-client"
		}
	],
	"settings": {}
}
```

I don't know whether it has anything to do with `"java.configuration.updateBuildConfiguration": "automatic"` or not. 

If you can constantly reproduce the issue, I think you can open an issue in https://github.com/redhat-developer/vscode-java/issues

**Comment by smoyer64** [comment]
Well ... I would agree that the classpath __can__ be managed by vscode-java but for a Maven project, the classpath is managed by Maven and the classpath contains a bunch of references to the <home>/.m2/repository/... directory hierarchy.  Maven's got to do the classpath resolution but it's entirely possible that Java plugin does that without using any parts of the vscode-maven plugin.  The repository you cloned is only a stub of what I've got so far but I'll try deleting that setting to see what happens.

**Comment by Eskibear** [comment]
You may notice that when you open your project, VSCode automatically generates `.project` and `.classpath` files. That's what exactly Eclipse M2E does. 

And as I pulled your latest code, it shows some error:
![image](https://user-images.githubusercontent.com/2351748/38160935-78bb4fca-347a-11e8-8f91-e7a3014033d4.png)

I guess your issue probably results form wrongly resolving the package name.

For this, I find some information here:
https://stackoverflow.com/questions/14788480/package-name-without-main-java-in-maven
See if it helps.

**Comment by smoyer64** [comment]
I don't have the "does not match the expected package" error in my classes because I've got the classes in the src/main/java/com/selesy/hibp folder of the project (in this case a module).  I don't remember how much of the project existed when you clone it ... I've been pushing more as I clean up the original code.

**Comment by smoyer64** [comment]
I've removed ``"java.configuration.updateBuildConfiguration": "automatic"`` from my global settings (it was getting rewritten into each workspace file) and deleted this setting from the HIBP specific workspace file and I no longer have this problem.  One interesting note as I was looking at this in more depth this morning - when the workspace loaded, it actually did set the classpath correctly and I could see the error markers, along with the class status colors flash briefly in the Explorer panel.  It appears that something else was altering the classpath immediately after it was set.

I'm going to trust that you're right about this problem not being in the Maven extension but clearly there's an oddity somewhere.  Since my problem is at least triaged (and I know what to look for) I'm willing to just close this as OBE.  Hopefully someone else has submitted the underlying issue to the correct extension project?

**Comment by Eskibear** [comment]
1. I'm ok with closing this issue. And sorry for the fact that I cannot provide more help on this.

2. I'm not sure whether there has been similar issues or not. 
But if you have time, I do suggest you to open an issue in https://github.com/redhat-developer/vscode-java/issues (whose maintainers probably have a better overview of the issue) for help, and also to help the Java community in VS Code. 😄

**Comment by smoyer64** [comment]
@Eskibear Thanks for your help - I do think you pointed me in the right direction!
