### ISSUE TITLE
No "Show Effective POM" operation after rename pom.xml file

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/vscode-maven#353]
**To Reproduce**
1. Open [https://github.com/Microsoft/todo-app-java-on-azure.git](https://github.com/Microsoft/todo-app-java-on-azure.git)
2. Set `maven.pomfile.globPattern` to `**/*pom.xml`
3. Rename pom.xml

**Expected behavior**
![image](https://user-images.githubusercontent.com/41051257/60165958-db819480-9832-11e9-8ef7-ee2dcf992037.png)

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10/Linux/OS X
 - VS Code version: 1.35.1
 - Extension version 0.18.0 (buildId=978353539)

**Screenshots**
![image](https://user-images.githubusercontent.com/41051257/60166056-023fcb00-9833-11e9-91a9-db7709e9a18e.png)

**Comment by Eskibear** [comment]
limited by VSCode's API, the command is staticly registered into context menu.
