### ISSUE TITLE
Homepage broken link

### ISSUE THREAD

**Issue by asears** [microsoft/vscode-maven#360]
**Describe the bug**
Homepage link is broken from the Marketplace

**To Reproduce**
1. Go to 'https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-maven'
2. Click on 'homepage

**Expected behavior**
Wiki appears

**Environments (please complete the following information as much as possible):**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Eskibear** [comment]
Thank you for pointing it out. The homepage link in package.json was wrong.
