### ISSUE TITLE
Typo 'gourpId' in hoverProvider

### ISSUE THREAD

**Issue by thccorni** [microsoft/vscode-maven#368]
**Describe the bug**
There is a small typo in [hoverProvider.ts](https://github.com/microsoft/vscode-maven/blob/70b7e8f64bd3759151ef3e0a232c9e30a76f2b77/src/hover/hoverProvider.ts#L31)

**To Reproduce**
1. Open a pom.xml
2. Hover over a dependency
3. The hover shows `gourpId = …`

**Expected behavior**
It should be `groupId` instead of `gourpId`

**Comment by Eskibear** [comment]
Fixed in #369
