### ISSUE TITLE
maven.archetype.generate command issue 

### ISSUE THREAD

**Issue by gregcousin126** [Microsoft/vscode-maven#37]
I am new to maven but have been having issues with version 3.5.3, when I was on 3.5.2 the plugin worked perfectly but every-since I upgraded with brew to 3.5.3 the maven plugin in vscode shows me this: command 'maven.archetype.generate' not found. I know that if i use man archetype:generate it will work with the terminal, but its the plugin that wont work. I made sure to route where my maven path is in settings in vs studio just in case.. path: /usr/local/Cellar/maven/3.5.3/libexec. its where i had it with version 3.5.2, I just changed it to 3.5.3: anyway, let me know if you can help with this issue. would be glad to have the plugin working rather than keep getting command 'maven.archetype.generate' not found

**Comment by Eskibear** [comment]
@gregcousin126 The error message probably has nothing to do with your Maven version. 'maven.archetype.generate' is a VSCode command registered in this extension. Let me have a check on it. And would you please provide the version of VSCode and this extension?

**Comment by Eskibear** [comment]
The issue looks like that the extension has not been activated when you call the command. 
However, according to https://github.com/Microsoft/vscode-maven/blob/develop/package.json#L40 , the extension will be activated once you open the command palette and call the command "Maven :Generate from Maven Archetype". 

As I mentioned, please provide the version of VSCode and this extension, and the steps to reproduce. Thanks.

**Comment by gregcousin126** [comment]
@Eskibear thanks for the repose. Yeah i thought thats what was happening but i've been searching through a lot of files to try to configure a way so it can be recognized but no luck. The version of VS Code Studio is the latest one, Version 1.21.1 and the version for the maven plugin is release 0.6.0.

**Comment by Eskibear** [comment]
I just upgraded my maven from 3.5.0 to 3.5.3:
```
==> Upgrading maven 
==> Downloading https://www.apache.org/dyn/closer.cgi?path=maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.tar.gz
==> Best Mirror http://download.nextag.com/apache/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.tar.gz
######################################################################## 100.0%
🍺  /usr/local/Cellar/maven/3.5.3: 104 files, 10.2MB, built in 4 seconds
```

VS Code version:
```
Version 1.21.1 (1.21.1)
```

But I still cannot reproduce your issue. Can you provide detailed steps? 
Or is there any possibility that it conflicts with your other extensions? Maybe you can try it again by re-install this extension, and disabling all the other extension in the meantime.

**Comment by gregcousin126** [comment]
hello @Eskibear I've attempted to reinstall the Java extension pack plugin along with its dependencies, (Maven) in vs code studios. I've installed the latest version of maven with brew 3.5.3 and the latest version of vs code... like the one you have as well. I'm not too sure what happened but as soon as i upgraded to mavens latest version with brew the vs code plugin stopped working. heres the directories that i have. as well as other information. still no luck yet but digging



<img width="1903" alt="screen shot 2018-03-31 at 12 02 52 am" src="https://user-images.githubusercontent.com/31825527/38155317-682ce914-3477-11e8-81a6-726ffc6bd46c.png">
<img width="729" alt="screen shot 2018-03-31 at 12 06 24 am" src="https://user-images.githubusercontent.com/31825527/38155318-684c7810-3477-11e8-8bce-fc333cbc9c74.png">
<img width="828" alt="screen shot 2018-03-30 at 11 57 30 pm" src="https://user-images.githubusercontent.com/31825527/38155319-6868a4ea-3477-11e8-8a82-37c16ec2e91e.png">
<img width="712" alt="screen shot 2018-03-30 at 11 57 04 pm" src="https://user-images.githubusercontent.com/31825527/38155320-6887efa8-3477-11e8-8964-ef5a0cba3a47.png">
<img width="784" alt="screen shot 2018-03-30 at 11 56 57 pm" src="https://user-images.githubusercontent.com/31825527/38155321-69331d56-3477-11e8-86cf-96990ef2f7cf.png">
<img width="708" alt="screen shot 2018-03-30 at 11 55 05 pm" src="https://user-images.githubusercontent.com/31825527/38155322-69b477d4-3477-11e8-83ad-e016822d250d.png">
<img width="401" alt="screen shot 2018-03-30 at 11 53 54 pm" src="https://user-images.githubusercontent.com/31825527/38155323-69ea12f4-3477-11e8-9e80-86ee638c5b05.png">
<img width="774" alt="screen shot 2018-03-30 at 11 53 20 pm" src="https://user-images.githubusercontent.com/31825527/38155324-6a15fc16-3477-11e8-9bb9-4640ff5e2205.png">

**Comment by Eskibear** [comment]
I think I know the reason from your first image. Please check the content of the `settings.xml`.

My settings.xml looks like:
![image](https://user-images.githubusercontent.com/2351748/38160786-c2d62326-3477-11e8-8950-44323a638531.png)

And if I remove the comment header `<!--` in line 3, I get the same error of yours.

There might be something wrong during your upgrading of maven 3.5.3.
Maybe you can try fixing the content of your `settings.xml`. Or totally remove your maven, and re-install.

Above are my findings. Hope it helps.

**Comment by gregcousin126** [comment]
eureka! That was it. It was a combination of vscode extensions not completely removing the extension folders upon uninstalling them in the IDE and that <!--  was deleted some time ago in a couple of place in the settings.xml file. Thank you for the help!

**Comment by Eskibear** [comment]
😄
