### ISSUE TITLE
Documentation inadequate - JAVA_HOME envvar

### ISSUE THREAD

**Issue by sylistine** [microsoft/vscode-maven#377]
I installed java and maven for VSCode and received a known error (JAVA_HOME variable not set)

Context:
1) I've installed java, JDK, android studio, etc, etc, but somehow I don't have this variable set.
2) Search for this error leads here, and becomes a dead end.

While it isn't strictly the responsibility of this source to explain, define, or manage a java or JDK installation, at the very least it would be useful for the documentation to provide a link to the relevant information.

As it stands, it seems excessive that I should install another java or JDK again just to get this variable, cluttering my environment and system in general.
Odds are I have the relevant kit somewhere on my system; enough information to locate and create the JAVA_HOME var myself would be helpful. Or, at least, a breadcrumb to locate what is wrong with the way I setup java on my system.

edit:
the documentation is basically a restating of the information provided by vscode itself. That is not helpeful.

**Comment by Eskibear** [comment]
Would it be more helpful if I place the below link into TroubleShooting.md ?
https://maven.apache.org/install.html

**Comment by sylistine** [comment]
Frankly speaking I've been drinking at a club and that link has already unblocked me  Yes, it would be helpful.
