### ISSUE TITLE
Show Explorer view conditionally

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/vscode-maven#380]
Perhaps the contributed explorer view, `mavenProjects`, should use a `when` clause so that it is only shown when relevant. It is currently a permanent fixture in the Explorer view when the extension is installed and enabled, even when it is not activated or useful.

I often work in non-Java projects and find that the contributed view is just wasting space there. I know I can disable extensions per workspace, but I was hoping for a better solution.

**Comment by Eskibear** [comment]
Previously it was conditionally visible, only when pom.xml was detected in the workspace. But some customers (mainly new users) complained about not knowing how to start after installation. (e.g. to create a maven project when no workspace is open).

So we remove the logic in https://github.com/microsoft/vscode-maven/pull/189/files , and hand it over to users. You don't have to disable the extension, right click on title of the explore, you can hide it.

**Comment by Eskibear** [comment]
it has been optimized as below:
- show when no folder is opened. (providing entries to create new maven project)
- show when maven project is opened.
- no show when non-maven project is opened.
