### ISSUE TITLE
Code lens display error

### ISSUE THREAD

**Issue by bonaluo** [microsoft/vscode-maven#386]
Issue Type: <b>Bug</b>

Code lens display error. See the screenshot.

![image](https://user-images.githubusercontent.com/27731323/64138628-4ef5e280-ce30-11e9-8335-da333d0b70de.png)

Extension version: 0.18.2
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Eskibear** [comment]
I'm closing it as this extension doesn't register any CodeLens provider. You may check other installed extensions.
