### ISSUE TITLE
Cannot execute 'Debug' in a maven goal when using powershell

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/vscode-maven#399]
**Describe the bug**
Right click a goal, choose "Debug", it cannot execute the corresponding command in the terminal in debug mode when using powershell terminal. this is not a regression issue.

**To Reproduce**
1. Clone code from [https://github.com/Microsoft/todo-app-java-on-azure.git](https://github.com/Microsoft/todo-app-java-on-azure.git)
2. Open the cloned project and set `terminal.integrated.shell.windows` to using powershell
3. Expand the project node and expand "Plugins" node
4. Expand a plugin node, right click a goal, choose "Debug"

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: 1.38.1
 - Extension version 0.18.2

**Screenshots**
![图片](https://user-images.githubusercontent.com/41051257/65029982-4db8cf80-d971-11e9-9352-00c52003c3c1.png)

**Comment by Eskibear** [comment]
![image](https://user-images.githubusercontent.com/2351748/65101517-14c53d00-d9fb-11e9-921c-a8a1a357cdca.png)

I cannot reproduce it on my machine.

**Comment by Eskibear** [comment]
One guess is, when launching in PS, the process is not **immediately** listening on the port, but with some delay. Then the debug session attempts and fails to attach to the port. 

For this case, the best solution should be that debugger supports to retry some times untill the port is ready.

**Comment by Eskibear** [comment]
let's track it in https://github.com/microsoft/vscode-maven/issues/757
