### ISSUE TITLE
No Maven:Generate from Maven Archetype item option

### ISSUE THREAD

**Issue by alonsoaz** [microsoft/vscode-maven#401]
**Describe the bug**
From every tutorial on the network, the main option to generate a project is the item set at the title but I can not find any option like this and also if I try to make it happen from "Maven:Create Maven Project" the lines in the terminal are as it follows:

mvn archetype:generate -DarchetypeArtifactId="maven-archetype-quickstart" -DarchetypeGroupId="org.apache.maven.archetypes" -DarchetypeVersion="1.4" etc/maven/settings.xml

where DarchetypeVersion is an option to choose between many versions. I was looking for an answer of what the command really should be and then I found the correct syntax to generate project is: 

mvn archetype:generate -DgroupId=fr.myGroupId -DartifactId=MyApplication -Dpackagename=fr.myGroupId -DarchetypeArtifactId=maven-archetype-quickstart

which is confused because there is no option to generate a valid command.

**To Reproduce**
1. Go to 'View'
2. Click on 'Command Palette'
3. Scroll down to 'Maven:Create Maven Project'

**Expected behavior**
I was expecting to generate a valid maven empty project.

**Environments (please complete the following information as much as possible):**
 - Linux Mint 19.1
 - VS Code version: 1.38.1
 - Extension version: v0.18.2

**Screenshots**
This is the issue.
![image](https://user-images.githubusercontent.com/43222495/65153406-4f28dd00-d9ef-11e9-8660-f2b7be202914.png)

This is how I found how should it be working.
![image](https://user-images.githubusercontent.com/43222495/65153562-944d0f00-d9ef-11e9-9565-e185dc124ad4.png)

Finally, the items from the Command Palette.
![image](https://user-images.githubusercontent.com/43222495/65153720-d9714100-d9ef-11e9-932c-730646ca41a4.png)

**Additional context**
No additional context. The extension was set by default.

**Comment by Eskibear** [comment]
It has nothing to do with the version, the command `mvn archetype:generate -DarchetypeArtifactId="maven-archetype-quickstart" -DarchetypeGroupId="org.apache.maven.archetypes" -DarchetypeVersion="1.4"` should also work for you. 

The problem was that "etc/maven/settings.xml" was appended to the command. Have you changes the related settings, e.g. `maven.executable.options` ?
