### ISSUE TITLE
Add a custom maven goal to the menu

### ISSUE THREAD

**Issue by quantrpeter** [microsoft/vscode-maven#406]
Hi All
   How to add a custom maven goal to the menu?
thanks
Peter

**Comment by Eskibear** [comment]
I assume that by mention "menu" you mean the contex menu which pops up when you right click on a project. 

Unfortunately the menu items are staticly registered. But you can use the setting `maven.terminal.favorites` as a workaround. See https://github.com/microsoft/vscode-maven/blob/master/TestPlan.md#maven-favorite-command for the usage

**Comment by Eskibear** [comment]
it's impossible now, as items are statically defined in manifest file.
