### ISSUE TITLE
mvn debug can not hot replace code 

### ISSUE THREAD

**Issue by bjdaijun** [microsoft/vscode-maven#409]
**Describe the bug**

can not hot replace code when debug maven

**To Reproduce**
1. right click a maven goal:   spring-boot:run, and select debug
2. modify java file, and save to compile to class
3. click hot code replace icon

**Expected behavior**
 expected hot replace code ,bug got  "Cannot find any changed classes"
 

**Screenshots**
![image](https://user-images.githubusercontent.com/1940592/66809508-12a1c000-ef60-11e9-993a-213c97bc4540.png)

![image](https://user-images.githubusercontent.com/1940592/66810190-4fba8200-ef61-11e9-9c96-f8daa5367e6a.png)

**Additional context**
 When I using Spring-Boot-dashboard to debug the app, and hot replace code works.

**Comment by Eskibear** [comment]
It's as expected. In maven extension, the "debug" action actually executes `mvnDebug` and attaches the debug session.

**Comment by bjdaijun** [comment]
I use maven  debug again, and this time ,  Hot Code Replace works
