### ISSUE TITLE
Error occurred in generating effective pom file

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-maven#41]
Build: 145
1. Specify java.home in user settings:
`"java.home": "C:\\Program Files\\Java\\jdk1.8.0_161" ` 
2. Add following entry in user settings:
`"maven.terminal.useJavaHome": true`
3.  Generate Effective POM file 

RESULT:
![image](https://user-images.githubusercontent.com/22470312/38605098-f8303008-3da4-11e8-9e83-f51c60041864.png)

**Comment by Eskibear** [comment]
`Generate Effective POM` doesn't launch a terminal to do the job, it use `child_process.exec` to execute the maven command in background.

**Comment by Eskibear** [comment]
@bsaby please help to verify.

**Comment by bsaby** [comment]
Test passed.
Build: 147
