### ISSUE TITLE
Error NPE DefaultReportingConverter when updating project configuration in a maven project

### ISSUE THREAD

**Issue by zeen1x** [microsoft/vscode-maven#415]
Hi, I've been using this extension for a year now and I've recently encountered an issue that I struggle to find a solution for. I get and NPE DefaultReportingConverter when updating the project configuration of any exisiting or new maven project I create. I updated my current version of maven to 3.6.2 as I found online this could be the issue https://issues.apache.org/jira/browse/MNG-6636. However, the standalone maven compile command successfully build the project.

Here's my settings.json file:

```
{
    "java.configuration.checkProjectSettingsExclusions": false,
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "java.home": "C:\\Program Files\\RedHat\\java-1.8.0-openjdk-1.8.0.161-1",
    "java.import.maven.enabled": true,
    "java.maven.downloadSources": true,
    "maven.pomfile.autoUpdateEffectivePOM": true
}
```
**Environment**
Operating System: Windows server 2012 R2 Standard
JDK version: 1.7.141
Visual Studio Code version: 1.39.2
Java extension version: 0.51.0
Maven version: 3.6.2

**Steps To Reproduce**
Update project configuration on a pom.xml file
A brand new maven project is enough to reproduce the problem.

**Current Result**
The java language server starts without loading maven dependencies

**Expected Result**
The java language server should load the maven dependencies

**Additionnal information:**

I found out by installing the newest version of eclipse that the NPE error was also occuring. In Window >> Preferences >> Maven >> Installations of eclipse I saw it was using version 3.6.1 of maven and that could explain the error I was having. I stumbled upon by configuring the latest version of maven in eclipse on a note that says: Embedded runtime is always used for dependency resolution. After a try it did confirm that de dependency resolution was in fact still using the version 3.6.1 of maven even though I added a newer one. For my solution to work, I downloaded an older version of eclipse which is using version 3.5.3 and this one worked just fine.

Back to vscode, is it possible for the Maven for Java extension, even though I set a newer or older maven version location with "maven.executable.path" setting name in settings.json, it still uses whatever latest current version of maven and so picks up version 3.6.1?

Issue opened in vscode-java: https://github.com/redhat-developer/vscode-java/issues/1103

**Comment by zeen1x** [comment]
Here in this file "maven-wrapper/.mvn/wrapper/maven-wrapper.properties": `distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.6.1/apache-maven-3.6.1-bin.zip`
Is there plans on updating to version 3.6.2 soon? thanks.

**Comment by Eskibear** [comment]
> Update project configuration on a pom.xml file
> The java language server starts without loading maven dependencies

Actually it's related to vscode-java and the language server, not in control of this "Maven for Java" extension. Thus "maven.executable.path" won't change behavior of the language server. I guess if it's because the language server is depending on an m2e library which is using Maven v3.6.1.

> Here in this file "maven-wrapper/.mvn/wrapper/maven-wrapper.properties" ..... Is there plans on updating to version 3.6.2 soon? 

This embedded maven wrapper is used to create a project from archetype, and only when you don't have a maven installed locally. It should  also have nothing to do with your issue. 
But as you mentioned there's a known issue in v3.6.1, I'll update it to 3.6.2

**Comment by Eskibear** [comment]
I'm closing this now.
