### ISSUE TITLE
Existing terminals don't apply new nvironment variables.

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/vscode-maven#42]
Steps:

1. Open a maven project 
1. Execute a maven goal, e.g. `clean`, it launches an integrated terminal.
1. Update `maven.terminal.customEnv` in settings. 
    ```    
    "maven.terminal.customEnv": [
        {
            "environmentVariable": "testName",
            "value": "testValue"
        }
    ] 
    ```
1. In the terminal, verify the env, it's not set.

**Comment by Eskibear** [comment]
fixed in #43 , terminals will be closed once there's change in related settings.

**Comment by Eskibear** [comment]
@bsaby please help to verify.

**Comment by bsaby** [comment]
Build: 47
Update related settings
**Result:**  An error occurred when the terminal was closed
![image](https://user-images.githubusercontent.com/22470312/38656686-b7953624-3e4e-11e8-853d-20fcf477542b.png)

**Comment by Eskibear** [comment]
fixed. please help to verify the latest build.

**Comment by bsaby** [comment]
Test passed.
Build: 148
