### ISSUE TITLE
Display available Maven profiles or have a way of reporting them

### ISSUE THREAD

**Issue by calvin1864** [microsoft/vscode-maven#423]
## Suggestion

It would be nice to have a menu option to dump the results of `mvn help:all-profiles` (similar to the way Effective POM or the Show Dependencies menu items work)

It would be even better to display the profiles as a child of each maven project in the tree-view (sibling to the Plugins tree).  Seems easier to discover and might give you the ability to interact with for other use-cases going forward

## Use Cases

Dumping the Effective POM doesn't list all available profiles.   This is mostly a shortcut to running the maven goal myself (just like the other tools in this plugin seem to do)

## Examples

1)  Open Maven Projects 
2)  Right click Maven Project
3)  Click new "Show Profiles" button
4)  New window pops up with profiles

or

1)  Open Maven Projects 
2)  Expand Maven Project tree
3)  Expand new 'Profiles' tree
4)  List of available profiles is shown

**Comment by Eskibear** [comment]
It looks like a convenient feature for users who are dealing with profiles. Below are my questions and thinking. 

Example 1:
I assume you mean the drop-down list on top of the window, by using the phrase "new window".  So if a list of profiles shows, what will be the implied action if I click them (maybe activating it) ? Or you just want to have a view of all profiles?

Example 2:
Adding a "Profiles" node is natural, just the same as the "Plugins" node.  This requires execution of the `help:all-profiles` commands with the "output" parameter. It can be either on-the-fly or pre-executed as soon as the extension is activated.

For the moment, I myself prefer Example 2, and on-the-fly execution of the command whenever users expand the "Profiles" node.

**Comment by calvin1864** [comment]
Yes, I did mean a dropdown  (I suppose I had the wrong amount of coffee yesterday 😄 )

I didn't go through the code, but it looked like the "Show Dependencies" and "Show Effective POM" actions just seem to dump a maven job's output to a new untitled file.   That's not my preference, but I figured that would be easiest to implement.

My preference is Example 2 as well.  If you agree, then one of us could take a look into it.   


Thanks!

**Comment by Eskibear** [comment]
If showing all profiles under a "Profiles" node is the only thing you want, actually you don't have to execute `help:all-profiles`. The profiles can be read from the effective-pom, which is calculated automatically when you open the project. We list the plugins in the same way.

You can add a similar getter `profiles()`, see below for example
https://github.com/microsoft/vscode-maven/blob/cf27b6dca9c4ce230038a1be3c97b229631bda33/src/explorer/model/MavenProject.ts#L47-L60

**Comment by calvin1864** [comment]
Thanks.  I did get started on it, but it may take me a little time to finish since weekends have most of my availability

The effective pom isn't enough to get all of the profiles.  I believe the `mvn help:effective-pom` command only gets you the ACTIVE profiles.  

https://maven.apache.org/plugins/maven-help-plugin/effective-pom-mojo.html


 This was part of the reason I opened this ticket.  Short of opening another IDE or running the `all-profiles` command, I couldn't figure out the name of a specific profile I needed in order to run code coverage and integration tests for my project.  The names of those profiles were hidden away in some  parent pom someone else controlled.

The downside of the `all-profiles` command is it doesn't return parseable XML, but I think simple regex is enough to get all the info we need (including which profiles are active)

**Comment by Eskibear** [comment]
`help:all-profiles` solution looks good to me.

> The downside of the all-profiles command is it doesn't return parseable XML, but I think simple regex is enough to get all the info we need (including which profiles are active)

please also be aware of possible ANSI escape code, which might cause potential issues.  See https://github.com/microsoft/vscode-maven/issues/340#issuecomment-511125457
