### ISSUE TITLE
Navigate to dependency pom.xml with a click

### ISSUE THREAD

**Issue by marweck** [microsoft/vscode-maven#428]
Hi everyone.

I would like to inspect the **pom.xml** definition file of a dependency when I Ctrl+click (or Cmd+click) it on a pom (key bindings could also apply).

## Example

I am editing my project's pom.xml file. I depend on, for example:
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
</dependency>
```

If I hit F12 on or Ctrl+Click the **artifactId** value, my editor would navigate to the pom.xml of the *spring-boot-starter-web* component which resides on my local repository.

If I click on another dependecy of my dependency the editor would do the same.

The same behavior applies to pom.xml files of modules inside a multi-module project.

I believe this feature would help maintainers to visualize dependencies and configurations inherited from parent pom files and dependency pom files.

**Comment by humbinal** [comment]
very good feature！It's an important obstacle for me to switch from IntelliJ IDEA to vs code.
When will this feature be supported?

**Comment by Eskibear** [comment]
It's already in our plan. Please share any thoughts about the behavior or implementation here.

**Comment by simahao** [comment]
Important feature, I would like to know what's the release plan?

**Comment by Eskibear** [comment]
@simahao
No one is currently working on it before we get the requirements clarified. If you are interested in the project, it's welcome to contribute. I can first share some points, and you may share your thoughts about the experience.
- Basically we can know the version from effective pom, so with gid,aid,version it's feasible to add "Go to definition" support which points to a pom.xml file in local maven repository if it exists (e.g. in ~/.m2/respository). 
- In IntelliJ IDEA, the pom.xml opened seems to be readonly, but as far as I know vscode doesn't. Since it would bring wired troubles if pom.xml of artifacts is modified by mistake. Does it harm the experience?
- What if it doesn't exist in local filesystem? Do we download it from maven central repo?
...

**Comment by marweck** [comment]
Hi @Eskibear,

I will try to answer your questions:

> * In IntelliJ IDEA, the pom.xml opened seems to be readonly, but as far as I know vscode doesn't. 

Since it would bring wired troubles if pom.xml of artifacts is modified by mistake. Does it harm the experience?
In my opinion, even a readonly view of the pom file would be great. Whereas if the dependency is a module of a multi-module project that is already open, than it could navigate to the project file. If possible, that experience would be even better. 

> * What if it doesn't exist in local filesystem? Do we download it from maven central repo?

If the dependency pom.xml file is not present on the local repository, having VSCode to download it would be great.

Hope it helps.

**Comment by humbinal** [comment]
Hi @Eskibear @marweck ,

Some of my thoughts:

1. In IntelliJ IDEA, the pom.xml opened seems to be readonly, In vscode also support open in read-only mode([Java Dependency Viewer](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency) plugin open xxx.class file is read-only mode).

2. If the dependency pom.xml file is not present on the local repository, I don't recommend automatic download it. In IntelliJ IDEA If the dependency pom.xml file is not present on the local repository we can't open it, Unless we use Maven's refresh button to manually trigger the download.

Hope it helps.

**Comment by Eskibear** [comment]
Thanks for pointing out `xxx.class` file, I can talk to the author about the exact mechanism of rendering it. 
I think the first step would be the "Go to definition" support for `project.dependencies.dependency` node. If the corresonponding pom.xml can be found in local repository, we render it.

As for the downloading part, language server will automatically resolve dependencies and download artifacts, and before that the project can not even run. So I don't think we should rush for it.

**Comment by anupama-sinha** [comment]
I needed to check if we have a certain sub dependency in one of the pom dependencies. But not able to hover it with CTRL+Click. Please let me know if there is a way to see this quickly.

**Comment by Eskibear** [comment]
@anupama-sinha Not implemented yet. This issue is exactly for the feature you need.

**Comment by Eskibear** [comment]
We have already shipped this feature. The click-to-navigate feature works for below cases:
* a) `version` is also defined inside a `dependency` 
or 
* b) version is successfully calculated from effective pom,


Further action items:
* Open `*.pom` in Read-Only mode. Depending on VS Code's support, tracked in https://github.com/microsoft/vscode/issues/4873
* Properties are not resolved. E.g. it doesn't recongnize `<version>${azure.version}</version>`, see https://github.com/microsoft/vscode-maven/issues/558#issuecomment-745930908

**Comment by Eskibear** [comment]
*.pom is opened in RO mode since v0.34. We use content provider to implement the RO mode.
