### ISSUE TITLE
Cant not select maven project

### ISSUE THREAD

**Issue by bonaluo** [microsoft/vscode-maven#429]
Issue Type: <b>Bug</b>

I can not select maven project if did not open the 'MAVEN PROJECTS' panel.

Extension version: 0.19.1
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (0.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Eskibear** [comment]
What do you mean by "select maven project", where do you want to select from? Can you explain the details?

**Comment by bonaluo** [comment]
I want to execute maven commands but first i need to select a mavenproject that command apply.

![image](https://user-images.githubusercontent.com/27731323/69508712-795bc580-0f71-11ea-9588-5d38e4fdd67d.png)
![image](https://user-images.githubusercontent.com/27731323/69508758-95f7fd80-0f71-11ea-9a72-9769b129a7c3.png)

There is no maven project in the list.

If i open the 'MAVEN PROJECTS' panel and execute maven commands again.

![image](https://user-images.githubusercontent.com/27731323/69509022-71505580-0f72-11ea-9520-dc2af3eee42a.png)

![image](https://user-images.githubusercontent.com/27731323/69508922-39491280-0f72-11ea-9b46-67cc654eba04.png)

![image](https://user-images.githubusercontent.com/27731323/69508897-25051580-0f72-11ea-929b-6316a826b2a7.png)

**Comment by Eskibear** [comment]
Confirmed, thank you for reporting. 
The root cause is, projects are only indexed when refreshing the Maven Explorer. Thus, command "Maven: Add a dependency" should have the same issue.

**Comment by Eskibear** [comment]
fixed.
