### ISSUE TITLE
An error pom.xml created by Blank Spring Archtype

### ISSUE THREAD

**Issue by bonaluo** [microsoft/vscode-maven#432]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/27731323/69850179-a4b81a80-12b9-11ea-9734-9de285dfd94d.png)
There is no property named **"spring-loaded.version"** in properties
![image](https://user-images.githubusercontent.com/27731323/69850217-bbf70800-12b9-11ea-906f-341198ff8528.png)

Extension version: 0.20.0
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Eskibear** [comment]
This extension simply assembles `mvn archetype:generate` command for you, which you can see from your integrated terminal. 

If the content of generated pom.xml is wrong, I suggest you to report to the archetype owner.
