### ISSUE TITLE
Option to verify automated changes of .classpath file

### ISSUE THREAD

**Issue by depascalis** [microsoft/vscode-maven#434]
First of all, I'm sorry if this is the wrong place to report this, I'm uncertain of which extension it is that could be causing the behaviors described below.

I noticed that sections that are commented out in `.classpath` sometimes are being completely removed, this might be a bug?
This is however related to automated changes of the .classpath file when reading-in poms, which is a good thing, but I would like to be more aware.

## Suggestion
1. Show a message - in a popup or similar - when automated changes are being made to the .classpath file. Have buttons to accept or decline the change.
2. Make this feature optional from the extension settings, where the options are:
    - Automated changes (current behavior)
    - Interactively verify changes
    - Disable automated changes

### Installed Java Extensions
Maven for Java 0.20.0
Language Support for Java(TM) by Red Hat 0.53.1
Java Extension Pack 0.8.1
Java Test Runner 0.21.0
Debugger for Java 0.23.0
Java Dependency Viewer 0.6.0
Java Properties 0.0.2
Eclipse New Java Project 1.0.0

**Comment by Eskibear** [comment]
"Maven for Java" extension is not aware of  `.classpath` file, and thus won't modify it.

https://github.com/redhat-developer/vscode-java/issues might be the right place for it.
