### ISSUE TITLE
Need more detailed procedures for working with maven managed project

### ISSUE THREAD

**Issue by bitflame** [microsoft/vscode-maven#438]
https://github.com/kevin-wayne/algs4 site is a maven manged project. I cloned it, and opened it in VSCode which I already ran other java files, but I can not get any of the source files to execute. Specifically I have tried to run BinarySearch 
Can you provide highleve steps of how to build this source? I get to the point of selecting an architype and open folder option comes up, but I am not sure that to do next. I do need to learn more about Maven, but I have watched a number of tutorials, and the steps I follow should be ok. not sure though.

**Comment by Eskibear** [comment]
It's either a Gradle project or Maven project. There's a `build.gradle`, thus it's recognized as a Gradle project, but failed to build.

Remove below section

```
```

**Comment by bitflame** [comment]
Thanks.
