### ISSUE TITLE
Install Maven

### ISSUE THREAD

**Issue by bitflame** [microsoft/vscode-maven#439]
## Suggestion
I had to install Maven on Windows and point to it in order to compile a project. Is there something wrong with my setup, or is that Maven is not installed when you choose to install the extension? Is that is the case, maybe a notification to the use is in order. I feel it is only intuitive that if someone chooses to install the extension, they want to work with the software. I realize there are other considerations like users from other IDEs, and the fact that Maven may have other owners and ....

**Comment by Eskibear** [comment]
When you open a Maven project, by default the extension attempts to locate the maven executable following the below order:
* `maven.executable.path` 
* maven wrapper in your project

And yes, I think if no Maven executable is found, the extension should better at popup a notice, which guides users where to download Maven. Or maybe jut download one for the users...

**Comment by bitflame** [comment]
Thanks.
