### ISSUE TITLE
Favorites support Debug mode

### ISSUE THREAD

**Issue by jinweilin** [microsoft/vscode-maven#444]
## Suggestion
Can the favorites run debug mode ?

## Use Cases

I have several module in a project, and I run maven from the top folder, I will assign which module will be started, any dependence module will package together, so I use favorites to start my application for testing in development environment, but I don't find the debug.

## Examples

project
  |-core-module
  |-erp-core-module
  |-ec-module  
  |-erp-module

I use tomcat plugin, I usually run command at project folder, the command is `tomcat7:run -pl :erp-moudle -am -Puat` , it will package the core-moudle,erp-core-moudle and erp-moudle.
I hope I can run the favorites command on debug mode.

Thanks.

**Comment by Eskibear** [comment]
Thank you for the feature request. 

For the moment, you can set value of `maven.executable.path` = path to mvnDebug. Then you can manually attach to it.  e.g. in `launch.json`, add an entry:
```json
        {
            "type": "java",
            "name": "Debug (Attach)",
            "request": "attach",
            "hostName": "localhost",
            "port": 8000
        }
```

**Comment by Eskibear** [comment]
@jinweilin 
You can take a look at PR #459 works, see if that covers your case.
