### ISSUE TITLE
destination folder of create new project 

### ISSUE THREAD

**Issue by divyang4481** [microsoft/vscode-maven#446]
I try to create new maven project  by selecting archetype is  maven-archetype-quickstar  in interactive mdoe.
 I select my destination folder  in D drive  but it always create project at

C:\Users\{myusername}\.vscode\extensions\vscjava.vscode-maven-0.20.1\resources\maven-wrapper.

**Comment by Eskibear** [comment]
If you don't have a maven distribution installed in your local machine, it will use the embedded maven wrapper to generate the project. Please check the command passed to the integrated terminal, see if the destination folder is specified by parameter `-DoutputDirectory`.

**Comment by divyang4481** [comment]
thank you,
 after installation of  maven distribution in the local machine it is working as expected
