### ISSUE TITLE
Run custom/favorite command with parent POM

### ISSUE THREAD

**Issue by benjavalero** [microsoft/vscode-maven#450]
I have a multi-module Maven project with a parent POM and two children submodules.

I have a workspace for each child submodule. And I want to run a Maven command to the whole project from the workspace of a submodule.

However, the submodule POM is always appended to the command.

**Steps to reproduce the behavior**
1. Custom/favorite command: `mvn clean install -f ../pom.xml`
2. The command executed, as displayed in the terminal, is: `"/Users/benja/Developer/apache-maven-3.6.3/bin/mvn" clean install -f ../pom.xml -f "/Users/benja/Developer/replacer/replacer-backend/pom.xml"`

If I run the command from the terminal it works well.

**Expected behavior**
The final part `-f "/Users/benja/Developer/replacer/replacer-backend/pom.xml"` of the command should not be appended in case the `-f` option is already used.

**Environments (please complete the following information as much as possible):**
 - OS: OSX Catalina
 - VS Code version: 1.41.1
 - Extension version: 0.20.2

**Comment by Eskibear** [comment]
Favorite command was designed to contain goals and options other than `-f`. We supposed that the parent project would be open as the workspace root, thus your use case was not covered. 

But if you insist to open submodule as workspace and want to execute command against parent project...em.. During the project selection stage, what if I add an entry "current project" which won't append `-f`? That should unblock you.

**Comment by benjavalero** [comment]
Well, it is not actually _unblocking_, as I can run the command manually as usual from the terminal.

I understand it is not a quite common scenario (Angular front-end, Java back-end, final WAR file).

So, if _this is not a bug, it is a feature_, I guess the issue can be closed.

**Comment by Eskibear** [comment]
This issue would be gone after we adopt #451 in the future. I'm closing it now.
