### ISSUE TITLE
Don't prefix with cmd /c

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode-maven#452]
**Describe the bug**
The extension runs Maven prefixed with `cmd /c`. However, this is no longer necessary. This was added to solve #111. However, when following the steps in that issue and running `& '.\mvnw ...'  on the command line (note that I'm not using the absolute path to mvnw, because I believe the command should always be run in the project directory anyway, see #451), it doesn't open a separate window and everything works as expected.

**To Reproduce**
1. run a Maven action

**Expected behavior**
The extension runs Maven with just `mvn ...` instead of `cmd /c mvn`.

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: 1.41.1
 - Extension version: 0.20.2

**Comment by Eskibear** [comment]
> The extension runs Maven prefixed with cmd /c. However, this is no longer necessary. 

Thank you for the information, I'll remove "cmd /c" for powershell, and run a full regression test for it. 


> ...note that I'm not using the absolute path to mvnw...

>maven.executable.path: ...... Note that [a relative path is not suggested](url), but if you do specify one, the absolute path will be resolved from your workspace root folder (if exists).

We don't ensure that "./mvnw" works. mvnw is supposed to be under your project root folder, and you should open it directly as a workspace, or a workspace folder..., and we'll handle it for you. 

You can refer to historical discussion in #68 #78 .

**Comment by Eskibear** [comment]
fixed
