### ISSUE TITLE
Allow referencing modules from local Maven repository

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode-maven#46]
Brought by @biezhi

This is not necessarily a problem of THIS extension. But we are looking for a fix cross the whole vscode-java solution.

**Comment by merqrial** [comment]
I am facing similar issue. I have a local maven repo and VScode can't find that properly.
Is there a path where I should set?

**Comment by alvint** [comment]
I would say not referencing the local repo **is** a problem of this extension, since the "Generate [project] from Maven Archetype" option does not show archetypes that are installed locally. And they usually are if you've created your own project templates.

**Comment by Eskibear** [comment]
> since the "Generate [project] from Maven Archetype" option does not show archetypes that are installed locally.

It should.  See #82 . 
But the limitation is, currently the local maven repository is determined by:
- Reading from settings file `~/.m2/settings.xml` if possible
- `~/.m2/repository` by default.

**Comment by djangofan** [comment]
Currently, my VSCode downloads Maven dependencies directly into the .m2/  folder rather than into  .m2/repository/   .   What would cause that mismapping?   The "maven for java" vscode plugin documention does not show that there is a property i can set to override that.

**Comment by Qiuzhuang** [comment]
Just add following configuration into settings.json file:
"java.configuration.maven.userSettings": "your maven settings.xml location"

**Comment by Eskibear** [comment]
now you can specify user settings with `maven.settingsFile`.
