### ISSUE TITLE
Switch to different profiles quickly

### ISSUE THREAD

**Issue by hantsy** [microsoft/vscode-maven#465]
I want to run tests and debug java in the editor UI and execute the testing codes against one or more Maven profiles, but there is no simple way to switch between profiles(by just some clicks).

**Comment by Eskibear** [comment]
The extension should be able to list all available profiles first, see feature request #423 , and it should allow you to select profiles to activate...e.g. via a dropdown list. If some profiles are selected, `-P<profiles>` would be appended to the following commands. But currently I don't see a good entry for listing/selecting the profiles. Any idea?

**Comment by hantsy** [comment]
I hope it looks like the one in IDEA, under a **Profiles** node, a list of profiles and uses checkboxes to select the active profiles.

Also can provide a command interface(like the Spring Boot to check features) for those stick on command shortcuts.

But I think **Profile** will make current work(if it did not take *profile* in account) become a little complex, such as it will affect the current project dependencies, lifecycle goals. etc, it could differ from the default.

**Comment by Eskibear** [comment]
> under a Profiles node, a list of profiles and uses checkboxes to select the active profiles.

Limited by VSCode's API, we cannot add checkboxes in the explorer. 

> Also can provide a command interface

Agree. I think it would be good to add a command "Run with Profiles..." in the context menu. By executing the command, it would list all profiles in a quickpick box that you could select one or many, and then you could select the commands you want to run.
It would enable users to quickly run some commands/goals with different profiles.

**Comment by hantsy** [comment]
>Limited by VSCode's API, we cannot add checkboxes in the explorer.
 I think two lists in explorer view  is also accepted.
* Profiles(add a *activate* on very items, except the ones from global settings.xml)
* Active Profiles(add a *deactivate* on very items)

If possible remember the selection of profiles somewhere?in the configuration file, it can be restored at the next time.
If it can be stored somewhere, it could have to add another to clear all selection.

**Comment by Eskibear** [comment]
that would increase the complexity a lot. 

> If possible remember the selection of profiles somewhere?in the configuration file, it can be restored at the next time.

This is against the "single source of truth" principle, as active profiles have already defined in pom.xml. And it would be less transparent and introduce confusion. 
This extension only serves to provide convenience for Maven users on VSCode, instead of making it an IDE.

**Comment by Massinissab** [comment]
Its will be also possible to interpret a command in the command text box (where we enter file name to open).
With a prefix like : #p my-maven-profile
We can also imagine to have autocomplete on profile entries.
And when we hit enter, the maven view can show the choose profiles
