### ISSUE TITLE
Maven command(like install) fails when whitespace in project path

### ISSUE THREAD

**Issue by JingangLi** [microsoft/vscode-maven#472]
**Describe the bug**

I refer the issue https://github.com/microsoft/vscode-maven/issues/304. As it solves the problem on that the path of mvn has whitespace. But my issue is for having a whitespace in the path of project's pom file. As I am useing Microsft one driver, the project is saved in the path like: C:\User\userId\OneDrive - mycompany\my project\pom.xml.

The maven install reports issues:
"c:\Users\userId\OneDrive - mycompany\my project\mvnw.cmd" install -f "c:\Users\userId\OneDrive - mycompany\my project\pom.xml"
'C:\Users\userId\OneDrive' is not recognized as an internal or external command,
operable program or batch file.

I have confirmed the issue isn't because of there being whitespace in the path of mvnw.cmd. It is because of whitespace in the path of pom file.

**Comment by Eskibear** [comment]
What's the version of maven distribution defined for you mvnw? 

I remember some older version like 3.5.4 has issue handling quoted whitespaces. See https://github.com/spring-projects/spring-petclinic/issues/404

**Comment by JingangLi** [comment]
Hi @Eskibear ,

This is my mvnw version, I think I am using the latest version. But still face the problem.
"c:\...\mvnw.cmd" -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Users\ellljjj\.m2\wrapper\dists\apache-maven-3.6.3-bin\1iopthnavndlasol9gbrbg6bf2\apache-maven-3.6.3
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_201\jre
Default locale: en_US, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

Rgds,
Jingang Li

**Comment by Eskibear** [comment]
I cannot reproduce the issue with `3.6.3`. The maven extension itself is sending the correct command. So it should be an external issue. 

I'm wondering if it's because of the version of the **maven wrapper** (not maven distribution) in your project folder.  
You can take the below action:
-  Regenerate the maven wrapper for your project, e.g. by running `mvn -N io.takari:maven:0.7.7:wrapper`, see if it works.
