### ISSUE TITLE
Maven REM error message:failure to build project

### ISSUE THREAD

**Issue by Jessevarela** [microsoft/vscode-maven#473]
installed vscode, java extension, maven 0.21 extension.. attempted to create project using maven archetype and got this error in the console output: 

@REM: command not found
syntax error near unexpected token `('
`@REM Licensed to the Apache Software Foundation (ASF) under one'

**To Reproduce**
1. Go to VsCode, maven project
2. Click on the + button to create a new project, select maven-archetype-webapp
3. Scroll down to console

**Expected behavior**
I expected a new java project to be created using the Maven archetype

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: 1.41.1
 - Extension version 0.21.0

**Screenshots**

**Additional context**

**Comment by Eskibear** [comment]
I cannot reproduce it with the steps. Actually after Step 2, it also let me choose the version and target folder, did you do that?

And in your case, what's the exact command line it sent to the terminal? Can you share with us? Thanks.
