### ISSUE TITLE
VSCode pom.xml not resolving dependency with internal maven repo server yet mvn build command works fine

### ISSUE THREAD

**Issue by alantango** [microsoft/vscode-maven#484]
**Describe the bug**
VSCode maven project's pom.xml has errors not able to resolve dependency imports, against internal maven central repository.

**To Reproduce**
1. Ctrl-P open command pallet
2. Maven: update maven archetype catalog
3. Maven: Create maven project
4. Choose 'maven-archetype-quickstart' by org.apache.maven.archetypes
5. After interactive creation is done, open project folder in vscode

**Expected behavior**
Pom.xml should be completely clean without error after first open the newly created maven project in VSCode.

But we see errors in pom.xml as below. If there are any more dependencies added to the pom (for example AWS java sdk libraries), those types won't resolve in the code.

**Why is it that mvn command works but the pom.xml has error and seems to be looking for the standard public Maven repo central (https://repo.maven.apache.org/maven2)?**

![vscode-mvn-error-pom-1](https://user-images.githubusercontent.com/56481094/78302857-a6b11500-7509-11ea-950d-97d7405946fe.png)

**Maven settings**
- Maven v.3.3.9
- VS Code does not have any setting override
- Environment variables:
M2=C:\dev\maven\3.3\bin
M2_HOME=C:\dev\maven\3.3
- Global settings file in %M2_HOME%\config\settings.xml (masked):
```
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0  http://maven.apache.org/xsd/settings-1.0.0.xsd">
	<mirrors>
		<mirror>
			<id>corp-mvn</id>
			<url>https://my.company.com/repository/maven/</url>
			<mirrorOf>*</mirrorOf>
		</mirror>
	</mirrors>
	<profiles>
		<profile>
			<id>profile-1</id>
			<properties>
				<corp-mvn.url>https://my.company.com/repository/maven/</corp-mvn.url>
			</properties>
		</profile>
	</profiles>
	<activeProfiles>
		<activeProfile>profile-1</activeProfile>
	</activeProfiles>
</settings>
```

- User settings.xml in c:\Users\user-someone\.m2\setttings.xml (along with settings-security.xml):
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0  http://maven.apache.org/xsd/settings-1.0.0.xsd">
	<servers>
		<server> 
		  <id>corp-mvn</id> 
		  <username>${env.USERNAME}</username> 
		  <password>{encrypted-pwd-string-xxxxxx}</password> 
		</server>
	</servers>
</settings>
```

**Environments (please complete the following information as much as possible):**
VSCode Version: 1.43.2 (user setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

Extensions:
Java Extension Pack by Microsoft v0.8.1
Maven for Java by Microsoft v0.21.2

**Further details**
The built-in OUTPUT console window of 'Maven for Java' shows mvn build works fine upon initial load of the project, pointing to internal corporate maven repo:

Wizard output:

>mvn org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate -DarchetypeArtifactId="maven-archetype-quickstart" -DarchetypeGroupId="org.apache.maven.archetypes" -DarchetypeVersion="1.4"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> maven-archetype-plugin:3.1.2:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO]
[INFO] <<< maven-archetype-plugin:3.1.2:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO]
[INFO] --- maven-archetype-plugin:3.1.2:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Interactive mode
[INFO] Archetype repository not defined. Using the one from [org.apache.maven.archetypes:maven-archetype-quickstart:1.0-alpha-1] found in catalog remote
Downloading: https://my.company.com/repository/maven/org/apache/maven/archetypes/maven-archetype-quickstart/1.4/maven-archetype-quickstart-1.4.pom
Downloaded: https://my.company.com/repository/maven/org/apache/maven/archetypes/maven-archetype-quickstart/1.4/maven-archetype-quickstart-1.4.pom (2 KB at 0.3 KB/sec)
Downloading: https://my.company.com/repository/maven/org/apache/maven/archetypes/maven-archetype-bundles/1.4/maven-archetype-bundles-1.4.pom
Downloaded: https://my.company.com/repository/maven/org/apache/maven/archetypes/maven-archetype-bundles/1.4/maven-archetype-bundles-1.4.pom (5 KB at 3.4 KB/sec)
Downloading: https://my.company.com/repository/maven/org/apache/maven/archetypes/maven-archetype-quickstart/1.4/maven-archetype-quickstart-1.4.jar
Downloaded: https://my.company.com/repository/maven/org/apache/maven/archetypes/maven-archetype-quickstart/1.4/maven-archetype-quickstart-1.4.jar (7 KB at 17.7 KB/sec)
Define value for property 'groupId': testGroup
Define value for property 'artifactId': vs-tester
Define value for property 'version' 1.0-SNAPSHOT: :
Define value for property 'package' testGroup: :
Confirm properties configuration:
groupId: testGroup
artifactId: vs-tester
version: 1.0-SNAPSHOT
package: testGroup
 Y: :
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: maven-archetype-quickstart:1.4
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: testGroup
[INFO] Parameter: artifactId, Value: vs-tester
[INFO] Parameter: version, Value: 1.0-SNAPSHOT
[INFO] Parameter: package, Value: testGroup
[INFO] Parameter: packageInPathFormat, Value: testGroup
[INFO] Parameter: package, Value: testGroup
[INFO] Parameter: version, Value: 1.0-SNAPSHOT
[INFO] Parameter: groupId, Value: testGroup
[INFO] Parameter: artifactId, Value: vs-tester
[INFO] Project created from Archetype in dir: c:\Users\user-someone\Lab\AWS\vs-tester
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 50.176 s
[INFO] Finished at: 2020-04-02T17:11:54-04:00
[INFO] Final Memory: 13M/245M
[INFO] ------------------------------------------------------------------------

Initial launch of project in vscode:
...
...
Downloaded: https://my.company.com/repository/maven/org/apache/maven/plugins/maven-surefire-plugin/2.22.1/maven-surefire-plugin-2.22.1.jar (40 KB at 84.7 KB/sec)
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building vs-tester 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-help-plugin:3.2.0:effective-pom (default-cli) @ vs-tester ---
[INFO] Effective-POM written to: c:\Users\user-someone\AppData\Roaming\Code\User\workspaceStorage\4dda2c8ca69abf72274a056df86ba332\vscjava.vscode-maven\fb2af0f36506cf81de09052785b6ea57
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.947 s
[INFO] Finished at: 2020-04-02T17:12:50-04:00
[INFO] Final Memory: 16M/272M

**PROBLEMS window shows below errors**

{
	"resource": "/C:/Users/user-someone/Lab/AWS/vs-tester/pom.xml",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "0",
	"severity": 8,
	"message": "Failed to read artifact descriptor for junit:junit:jar:4.11\n\norg.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for junit:junit:jar:4.11\r\n\tat org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:255)\r\n\tat org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171)\r\n\tat org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:541)\r\n\tat org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:524)\r\n\tat org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:412)\r\n\tat org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:365)\r\n\tat org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:352)\r\n\tat org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)\r\n\tat ...
	...
	org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)\r\nCaused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to transfer junit:junit:pom:4.11 from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact junit:junit:pom:4.11 from/to central (https://repo.maven.apache.org/maven2): Software caused connection abort: recv failed\r\n\tat org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:424)\r\n\tat org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)\r\n\tat org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207)\r\n\tat org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240)\r\n\t... 33 more\r\nCaused by: org.eclipse.aether.transfer.ArtifactTransferException: Failure to transfer junit:junit:pom:4.11 from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact junit:junit:pom:4.11 from/to central (https://repo.maven.apache.org/maven2): Software caused connection abort: recv failed\r\n\tat org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:225)\r\n\tat org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:193)\r\n\tat org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:559)\r\n\tat org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:483)\r\n\tat org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:401)\r\n\t... 36 more\r\n",
	"source": "Java",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}

{
	"resource": "/C:/Users/user-someone/Lab/AWS/vs-tester/pom.xml",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "0",
	"severity": 8,
	"message": "CoreException: Could not calculate build plan: Plugin org.apache.maven.plugins:maven-compiler-plugin:3.8.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-compiler-plugin:jar:3.8.1: ArtifactResolutionException: Failure to transfer org.apache.maven.plugins:maven-compiler-plugin:pom:3.8.1 from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact org.apache.maven.plugins:maven-compiler-plugin:pom:3.8.1 from/to central (https://repo.maven.apache.org/maven2): Software caused connection abort: recv failed",
	"source": "Java",
	"startLineNumber": 43,
	"startColumn": 10,
	"endLineNumber": 43,
	"endColumn": 17
}

**Comment by Eskibear** [comment]
Thanks for reporting it. [Language support for Java](https://github.com/redhat-developer/vscode-java) is responsible for importing and building your project, and the error was reported by that extension. I'm closing it here, please open an issue there.

**Comment by zacutti-basf** [comment]
hi @alantango , did you figure it out how to get it working? we are facing the same issue.. 4 years after
