### ISSUE TITLE
Allow to invoke Maven with a specified JDK

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode-maven#487]
## Suggestion
It should be possible to invoke Maven with a specified JDK.

## Use Cases
Currently, any Maven invocations are done via the Terminal, with the JDK as specified by `JAVA_HOME`.
However, some projects require a specific JDK to be used.

## Examples
This could be done by introducing a custom property to be set in the `pom.xml`, for example, `vscode-maven.jdk`. The value of that property could be:
* the absolute path to the JDK to be used (by using a property and `settings.xml`, this could still be kept portable: developers would specify `${my.company.jdk8}` as the value, and the absolute path in their personal `settings.xml` file).
* an "Eclipse runtime environment", e.g. "JavaSE-1.8". In this case, the extension would look up the JDK path using the `java.configuration.runtimes` setting (or an analog setting which is "owned" by this extension). This is what NetBeans does with its `netbeans.hint.jdkPlatform` property. (Note that an alternative for using a `pom.xml` property would be to extract the "Eclipse runtime environment" from the .classpath file)

After determining the JDK to be used, the extension would first set the JAVA_HOME environment variable in the terminal, before invoking maven itself.

**Comment by Eskibear** [comment]
This can be achieved by setting custom environment variables. 
```json
"maven.terminal.customEnv": [
    {
        "environmentVariable": "JAVA_HOME",
        "value": "path-to-java-home"
    }
]
```

**Comment by anthonyvdotbe** [comment]
Ah yes, thanks for pointing that out. So it's simply a matter of making that setting available on the folder level.

**Comment by Eskibear** [comment]
Then we need to change it to "resource" scope, and change a little bit how it's consumed.
https://github.com/microsoft/vscode-maven/blob/b57a84afd5f4a918dfb42e65309d3452ed91beae/package.json#L457

I'll put it in plan, and check if there's any pitfall.
