### ISSUE TITLE
Create Maven Project:Unexpected token 'org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate' in expression or statement.

### ISSUE THREAD

**Issue by CodeNovice2017** [microsoft/vscode-maven#492]
**Describe the bug**
When i use maven plugin to create maven project,it always show that Unexpected token 'org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate' in expression or statement.
Terminal run codes like""C:\CodeEnv\apache-maven-3.6.3\bin\mvn.cmd" org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate -DarchetypeArtifactId="archetype-quickstart-jdk8" -DarchetypeGroupId="com.github.ngeor" -DarchetypeVersion="1.0.14"",
I have tired run vscode as administritor,and I have set the maven settings.xml right.

'<localRepository>C:\CodeEnv\apache-maven-3.6.3\repository</localRepository>',I also checked the maven-archetype-plugin in my repository, I really have no idea to solve this prolblems.

**To Reproduce**

**Expected behavior**

**Environments (please complete the following information as much as possible):**
 - OS: Windows10
 - VS Code version:1.34
 - Extension version 0.21.3

**Screenshots**
![image](https://user-images.githubusercontent.com/26214741/81519858-289c2580-9375-11ea-82b0-4682428c7cd6.png)

**Additional context**

**Comment by Eskibear** [comment]
It looks more like your terminal failed to correctly parse the whole command.  What's the shell you used for the integrated terminal? (CMD? powershell? or a thirdparty one?)

**Comment by CodeNovice2017** [comment]
> It looks more like your terminal failed to correctly parse the whole command. What's the shell you used for the integrated terminal? (CMD? powershell? or a thirdparty one?)

Thanks for reply! My termial is PowerShell-preview2 7.1.0

**Comment by Eskibear** [comment]
If it's powershell, the full command missed a `&` in the beginning...Maybe it's recognized as another type of shell. In this extension, filename of the binary is used to identify shell type. E.g. only "powershell.exe" is recognized as PowerShell. 
https://github.com/microsoft/vscode-maven/blob/e2b4ee8cf2ab76987e09754f58981fd92cbceab7/src/mavenTerminal.ts#L118-L119

I notice vscode has [two types of PowerShell](https://github.com/microsoft/vscode/blob/da1d56500a2d2a9f3ccfa2487b7696340ad9e276/src/vs/workbench/contrib/terminal/node/terminal.ts#L112-L113), `Windows PowerShell` and `PowerShell`.  Can you take a look of the filename of your terminal, is it `pwsh.exe`?

**Comment by Eskibear** [comment]
I can reproduce it with PowerShell 6, same error message. 

![image](https://user-images.githubusercontent.com/2351748/81531356-1fbb4c00-9395-11ea-955a-bab46f5b1f90.png)

**Comment by CodeNovice2017** [comment]
My English is so poor.My terminal filename is pwsh.exe.My vscode settings.json configured  `"terminal.integrated.shell.windows": "C:\\Program Files\\PowerShell\\7-preview\\pwsh.exe",`

**Comment by CodeNovice2017** [comment]
![image](https://user-images.githubusercontent.com/26214741/81534421-96a71380-939a-11ea-96d9-9e5343c46307.png)
it is working when I add `&` before the command!

**Comment by Eskibear** [comment]
Thanks for the information, we'll fix it.
