### ISSUE TITLE
Can't execute maven goals in PowerShell when there are space in the folder

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/vscode-maven#498]
**To Reproduce**

1. Change to an account which has space
2. Clone code from https://github.com/Microsoft/todo-app-java-on-azure.git
3. Open the cloned project.
4. Right-click on the project item
5. Click `Clean`
6. See error

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: 1.45.1
 - Extension version:
    - Maven for Java: 0.21.4

**Screenshots**

![image](https://user-images.githubusercontent.com/41051257/82875844-84b49b80-9f6a-11ea-9d66-bda4077b5fc9.png)

After change `cmd /c` to `&`, it works
![image](https://user-images.githubusercontent.com/41051257/82875074-7dd95900-9f69-11ea-83f8-a1f5218c6eb9.png)

**Comment by Eskibear** [comment]
fixed.
