### ISSUE TITLE
Searching for Maven Projects throws "No whitespace between attributes Line: 0 Column: 105 Char: x"

### ISSUE THREAD

**Issue by chrisumitratech** [Microsoft/vscode-maven#50]
Hi,

I've opened a folder which have previously successfully built with Maven and run through Eclipse. 

When scanning the folder for Maven projects I get:
"No whitespace between attributes Line: 0 Column: 105 Char: x"

I've tried a fresh clone so the workspace is clean and I get the same result.  I've also tried setting the Maven path in my VS Code User settings.

I'm using Windows 10.

Help please.

**Comment by chrisumitratech** [comment]
Sorry, I googled for VSC logs for extensions and couldn't find any info on where VS Code logs errors to.

Any ideas where I can get a log for this error?

**Comment by Eskibear** [comment]
`Help` -> `Toggle Developer Tools`, it is supposed to open a Chrome panel. Inside, select `Console` tab to see the error log in red.

**Comment by chrisumitratech** [comment]
This is what Developer Tools gives me:

No whitespace between attributes Line: 0 Column: 105 Char: x
e.onDidNotificationChange @ notificationsAlerts.ts:39
(anonymous) @ notificationsAlerts.ts:28
e.fire @ event.ts:140
e.notify @ notifications.ts:127
e.error @ notificationService.ts:61
(anonymous) @ mainThreadTreeViews.ts:89
v @ winjs.base.js:1224
enter @ winjs.base.js:916
_run @ winjs.base.js:1083
_error @ winjs.base.js:1056
e.resolveErr @ lazyPromise.ts:78
e._receiveReplyErr @ rpcProtocol.ts:154
e._receiveOneMessage @ rpcProtocol.ts:99
(anonymous) @ rpcProtocol.ts:33
(anonymous) @ rpcProtocol.ts:213
e.fire @ event.ts:140
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560

**Comment by Eskibear** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. Please reach out if you have or find the answers we need so that we can investigate further.
