### ISSUE TITLE
Cannot close the error notification "Maven executable not found in PATH"

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-maven#501]
My machine didn't install maven cli tools, then opening a workspace containing pom.xml, the extension will pop up the error message over and over again.

![mavenbug](https://user-images.githubusercontent.com/14052197/83475739-8b3e9800-a4c1-11ea-8d7b-4b4272b3c484.gif)

**Comment by Eskibear** [comment]
Confirmed. Open a workspace with `n` maven projects, none of which has `mvnw`. The extension will calculate effective pom for each project, and pops up the notification if failing to find a maven executable (mvn or mvnw). So in this case, it pops up `n` times, which is annoying.

#### Enhancement
At startup, we probably should check existence of mvn for only once. And each time when user **explicitly** executes command, check it again.

**Comment by Eskibear** [comment]
fixed in #506
