### ISSUE TITLE
mvnw is not identified if .mvn folder doesn't exists

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-maven#504]
In some case, to use maven wrapper, we don't have to check in a `.mvn` folder. E.g. repo https://github.com/retaildevcrews/helium-java 

Steps:
- open a machine without maven distribution installed locally.
- checkout the code from above repo, and open it in vscode

Current behavior:
- it pops up notification to set maven executable, instead of using `mvnw` directly

Expected behavior:
- it should use `mvnw` directly, without any warning

**Comment by jyotsnaravikumar** [comment]
Hello, When will this fix be published?

**Comment by Eskibear** [comment]
it has already been shipped in v0.22.0

**Comment by jyotsnaravikumar** [comment]
Hello, 
So when we goto maven project-> helium->rightclick->open menu->install or package - it throws the this same error which we had discussed few days ago

vsonline@helium ~/workspace/helium-java/ $ ./mvnw
./mvnw: 219: ./mvnw: cannot open /home/vsonline/workspace/helium-java/.mvn/wrapper/maven-wrapper.properties: No such file
/home/vsonline/workspace/helium-java/.mvn/wrapper/maven-wrapper.jar: No such file or directory
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain

This issue still persists. When will this be fixed/published?

**Comment by Eskibear** [comment]
> vsonline@helium ~/workspace/helium-java/ $ ./mvnw
./mvnw: 219: ./mvnw: cannot open /home/vsonline/workspace/helium-java/.mvn/wrapper/maven-wrapper.properties: No such file
/home/vsonline/workspace/helium-java/.mvn/wrapper/maven-wrapper.jar: No such file or directory
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain

I just tried on my mac, it just works as below. Take a look at the content of `mvnw`, I guess it might have different behaviour on Linux. That's the issue of your `mvnw`, not this extension. Usually you would like to check in the `.mvn` folder together with `mvnw`. And that's why we used to check existence of `.mvn` folder.

<details>
<summary>log</summary>
<pre>
[sechs@01HW864271:~/Desktop/helium-java] (master)
$> ./mvnw clean
Downloading https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.5.4/apache-maven-3.5.4-bin.zip
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /Users/sechs/.m2/wrapper/dists/apache-maven-3.5.4-bin/jl1qqhdeineh9qg83dtj7i91c/apache-maven-3.5.4-bin.zip to /Users/sechs/.m2/wrapper/dists/apache-maven-3.5.4-bin/jl1qqhdeineh9qg83dtj7i91c
Set executable permissions for: /Users/sechs/.m2/wrapper/dists/apache-maven-3.5.4-bin/jl1qqhdeineh9qg83dtj7i91c/apache-maven-3.5.4/bin/mvn
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------------< com.cse:helium >---------------------------
[INFO] Building helium-java 0.1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ helium ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.857 s
[INFO] Finished at: 2020-06-18T09:41:32+08:00
[INFO] ------------------------------------------------------------------------
</pre>
</details>
