### ISSUE TITLE
vscode "Error while downloading 'http://maven.apache.org/maven-v4_0_0.xsd'

### ISSUE THREAD

**Issue by WestFarmer** [microsoft/vscode-maven#508]
I am using vscode wtih this extension behind a proxy, the vscode global proxy settings wi configed, but maven pom schema still can't be downloaded.

**Comment by WestFarmer** [comment]
I am using fedora 31, proxy is set by:
![image](https://user-images.githubusercontent.com/14016562/84391779-0293ca80-ac2c-11ea-8f9e-e76d0bab0f66.png)
extension version: 0.21.4
vscode version:1.44.1

**Comment by WestFarmer** [comment]
I have manually download the xsd file and put it to /home/ggfan/.lemminx/cache/https/maven.apache.org/xsd, and restart vscode, but still get this error

**Comment by Eskibear** [comment]
This feature is provided by XML extension.
I'm closing it, sorry about the inconvenience but please open the issue in https://github.com/redhat-developer/vscode-xml/issues by yourself.
