### ISSUE TITLE
Skip selection of project when only one maven project exists

### ISSUE THREAD

**Issue by bonaluo** [microsoft/vscode-maven#515]
Issue Type: <b>Feature Request</b>

Skip selection of project when only one maven project exists
![image](https://user-images.githubusercontent.com/27731323/87928152-eb5fbc80-cab6-11ea-9c00-a6afc25ea86f.png)

Extension version: 0.22.0
VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Eskibear** [comment]
It makes sense. We have multiple actions requiring project selection, can you tell explicitly which action were you performing?

**Comment by bonaluo** [comment]
The most commonly used are package and install

**Comment by Eskibear** [comment]
I mean the entry to this drop-down list. Did you trigger the command through **command palette** or from the maven explorer on the bottom left?

**Comment by bonaluo** [comment]
I trigger the command through command palette [maven: execute command]

**Comment by bonaluo** [comment]
I think all the maven commands involving project selection need to be enhanced

**Comment by Eskibear** [comment]
> I think all the maven commands involving project selection need to be enhanced

Agree. I just remember we've already done that before, just not sure why this command is left out.  Anyway, thanks for reporting, I'm fixing it.

**Comment by bonaluo** [comment]
> > I think all the maven commands involving project selection need to be enhanced
> 
> Agree. I just remember we've already done that before, just not sure why this command is left out. Anyway, thanks for reporting, I'm fixing it.
