### ISSUE TITLE
Ansi escape code not rendered or hide in output window

### ISSUE THREAD

**Issue by Hypnoes** [microsoft/vscode-maven#528]
**Describe the bug**
![批注 2020-08-21 092757](https://user-images.githubusercontent.com/13956546/90841954-a4ecce80-e390-11ea-958f-8f7ca7a223f6.png)

**Expected behavior**
Show the color properly, or at least hide it.

**Environments (please complete the following information as much as possible):**
 - OS: Wsl Debian
 - VS Code version: 1.48.1
 - Extension version 0.24.1

**Comment by Eskibear** [comment]
The output is generated by the maven command, and the output window is only for logging and diagnosing purpose. Thus we won't fix it, at least for the moment. 

If you do want to dismiss the color code, add "-B" into setting `maven.executable.options`. 
Hope it helps.
