### ISSUE TITLE
Non-resolvable parent POM which is offered in mirror repository

### ISSUE THREAD

**Issue by Jacky-Chang** [microsoft/vscode-maven#533]
**Describe the bug**
I opened a maven project with multi modules whose parent pom is offered in my mirror repository. But I got an error as the follows: 
<code>Project build error: Non-resolvable parent POM for com.yonyou.yuncai.bid:yuncai-bid-biddoc:1.0.0-SNAPSHOT: Could not find artifact com.yonyou.yuncai:yuncai-parent-spring-boot:pom:0.0.2-SNAPSHOT and 'parent.relativePath' points at wrong local POMJava(0)</code>
The structor of the root pom file like this:
```xml
project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.example.demo</groupId>
		<artifactId>demo-parent-spring-boot</artifactId>
		<version>0.0.2-SNAPSHOT</version>
	</parent>
	<groupId>com.example.demo.bid</groupId>
	<artifactId>demo-bid-biddoc</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>
	<modules>
		<module>demo-bid-biddoc-domain</module>
		<module>demo-bid-biddoc-api</module>
		<module>demo-bid-biddoc-dao</module>
		<module>demo-bid-biddoc-web</module>
		<module>demo-bid-biddoc-service</module>
	</modules>
	<properties>
		<biddoc.version>1.0.0-SNAPSHOT</biddoc.version>
		<bidproject.version>1.0.0-SNAPSHOT</bidproject.version>
		<score.version>1.0.0-SNAPSHOT</score.version>
		<poi.version>3.8</poi.version>
		
    </properties>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.example.demo</groupId>
				<artifactId>demo-parent-spring-boot</artifactId>
				<version>0.0.2-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>com.example.demo.bid</groupId>
				<artifactId>demo-bid-biddoc-api</artifactId>
				<version>${biddoc.version}</version>
			</dependency>
			<dependency>
				<groupId>com.example.demo.bid</groupId>
				<artifactId>demo-bid-biddoc-domain</artifactId>
				<version>${biddoc.version}</version>
			</dependency>
			
			<dependency>
				<groupId>com.example.demo.bid</groupId>
				<artifactId>demo-bid-biddoc-service</artifactId>
				<version>${biddoc.version}</version>
			</dependency>
			<dependency>
				<groupId>com.example.demo.bid</groupId>
				<artifactId>demo-bid-biddoc-dao</artifactId>
				<version>${biddoc.version}</version>
			</dependency>
			
		</dependencies>
	</dependencyManagement>
</project>
```
I got the error message of 
```xml
<parent>
	<groupId>com.example.demo</groupId>
	<artifactId>demo-parent-spring-boot</artifactId>
	<version>0.0.2-SNAPSHOT</version>
</parent>
```
like this:
![image](https://user-images.githubusercontent.com/12825179/91957953-4b45b600-ed39-11ea-9892-0e669e484255.png)
**So, how can I fix this error?**

**Comment by Eskibear** [comment]
First of all, the error was reported by [Java extension](https://github.com/redhat-developer/vscode-java) instead of Maven extension (this one). 

Looks like your pom.xml is not correctly configured. Can you successfully compile your project with Maven CLI? e.g. `mvn clean compile`

>... whose parent pom is offered in my mirror repository

Then you probably should define `repository` in your pom.xml.

**Comment by Jacky-Chang** [comment]
Yes, I can compile my project successfully with this maven complier plugin.

> Then you probably should define `repository` in your pom.xml.

And this suggestion also worked for me.

At the beginning, I defined `repository` in my settings.xml. It seems that, the maven extension cannot get the information?

**Comment by Eskibear** [comment]
@Jacky-Chang 

> java.configuration.maven.userSettings : Path to Maven's settings.xml.

See https://github.com/redhat-developer/vscode-java#supported-vs-code-settings

**Comment by Jacky-Chang** [comment]
@Eskibear
It works well now! Thanks!
