### ISSUE TITLE
Broken under WSL

### ISSUE THREAD

**Issue by soerenBoisen** [microsoft/vscode-maven#534]
**Describe the bug**
I have my terminal in VS Code set to WSL 1 bash (Ubuntu).

1. When executing a Maven command without maven.executable.path in settings.json:
Extension attempts to execute mvnw.cmd instead of mvnw, leading to syntax errors.

2. When executing Maven command with `maven.executable.path: "/usr/share/maven/bin/mvn"`:
Extension wrongly adds Windows mount point to the absolute path:
```bash
-bash: /mnt/c/usr/share/maven/bin/mvn: No such file or directory
```

**Expected behavior**
With no Maven executable path set, I expect extension to execute mvnw in project, not mvnw.cmd, since the shell is bash and don't understand Windows batch files.

With Maven executable path set to an absolute path, I expect extension to run it without adding random and wrong mount point in front, since the path is supposed to be _absolute_.

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: 1.48.2
 - Extension version: 0.24.2

**Comment by Eskibear** [comment]
Thanks for reporting this. I guess you are connecting to WSL via VS Code Remote extension. Just FYI that WSL support in this extension was added long before VS Code Remote is released, when WSL was only a different shell. At that time, `maven.executable.path` was **shared** between WSL and Windows, and the path was converted by executing `wslpath -u <path>`. That's why you see "/mnt/c/" prepended.

**Comment by soerenBoisen** [comment]
I am unsure if I connect via VS Code Remote. My settings are also from long before Remote released 😄 

This is what I have in settings for terminal:
```json
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\wsl.exe",
```

**Comment by Eskibear** [comment]
Ok, then you are not using Remote. 
Here are two ways of using WSL:
* Only one maven distribution is installed in Windows (let's say `C:\Maven`), and the user wants to use this one in both Windows and WSL, so we have to convert `C:\Maven` to `/mnt/c/Maven/`. 
* Maven is installed in WSL and it's dedicated for WSL (e.g. `/usr/share/maven/` in your case). 

Currently I cannot think of a simple fix covering both cases above... You may want to try VS Code Remote if you prefer WSL, as that's also better supported by vscode itself.

**Comment by soerenBoisen** [comment]
Why not simply check if the path starts with forward slash and don't perform conversion in that case?
What is the use case for a Windows path (needs conversion to WSL) that starts with '/'?

I switched to VS Code Remote and it now works with the Maven Wrapper ✔️ 

But now I cannot get 'maven.executable.path' to take effect. When I have settings.json open, this setting is faded with a tooltip of "This setting cannot be applied in this window. It will be applied when you open local window." ✖️ 

For projects without Maven Wrapper I can get around it by not setting 'maven.executable.path'. The extension then correctly picks up Maven from path. So as long as I use Remote WSL, I can now run Maven commands with the extension for a project with and without the wrapper. Thank you for the workaround 👍

**Comment by Eskibear** [comment]
> Why not simply check if the path starts with forward slash and don't perform conversion in that case?

Yes, it can be a patch.  

> But now I cannot get 'maven.executable.path' to take effect. When I have settings.json open, this setting is faded with a tooltip

In VS Code Remote `maven.executable.path`should be only set in **Remote** scope, I guess you opened the user settings. Can you double check which `settings.json` did you open (user/remote/workspace)? If you cannot judge, let me know the absolute path.

**Comment by soerenBoisen** [comment]
Arh, I did not realize there was a remote settings file! 
`maven.executable.path` works perfectly now.

I guess this issue can be closed when your PR is merged 💯

**Comment by soerenBoisen** [comment]
Closed in https://github.com/microsoft/vscode-maven/pull/535
