### ISSUE TITLE
Add setting to hide "Create Maven Project" explorer menu item

### ISSUE THREAD

**Issue by IAL32** [microsoft/vscode-maven#537]
## Suggestion

A new setting voice to disable the "Create Maven Project" menu item that appears when right clicking on a project's explorer, either on a per-project basis or in my user settings.

## Use Cases

- Not clicking "Create Maven Project" by accident when working on a non-Maven related project
- Not seeing Maven-related stuff in a non-Maven environment

## Examples

Right now:
![right now](https://user-images.githubusercontent.com/562969/93135600-e2682180-f6da-11ea-8728-ccc56b2e97a8.png)

What I'd love:
![what I'd love](https://user-images.githubusercontent.com/562969/93135637-f0b63d80-f6da-11ea-9e6d-95f14d95b7ad.png)

**Comment by IAL32** [comment]
I have just noticed the recent pull request https://github.com/microsoft/vscode-maven/pull/536

Sorry!

**Comment by Eskibear** [comment]
> right clicking on a project's explorer

Can you be more specific on the point you clicked? E.g. on a folder node, file node, or body of the explorer?

> Not seeing Maven-related stuff in a non-Maven environment

The command is statically registered via `package.json`, and the entry is there even before Maven extension is activated.

Introducing a new settings brings a few concerns, as I mentioned in https://github.com/microsoft/vscode-maven/pull/536#issuecomment-691806213 , a comprosing approach is to only show "Create Maven Project" on folder node to mitigate the noise.

**Comment by IAL32** [comment]
> > right clicking on a project's explorer
> 
> Can you be more specific on the point you clicked? E.g. on a folder node, file node, or body of the explorer?

- Clicking on a folder node (selected and non)
- Clicking on a file node (selected and non)
- Clicking on the body of the explorer

> > Not seeing Maven-related stuff in a non-Maven environment
> 
> The command is statically registered via `package.json`, and the entry is there even before Maven extension is activated.
> 
> Introducing a new settings brings a few concerns, as I mentioned in [#536 (comment)](https://github.com/microsoft/vscode-maven/pull/536#issuecomment-691806213) , a comprosing approach is to only show "Create Maven Project" on folder node to mitigate the noise.

I see, that could help!

**Comment by Eskibear** [comment]
shipped with 0.25.0
