### ISSUE TITLE
Error creating temporary directory when using extension via Remote-SSH with multiple users

### ISSUE THREAD

**Issue by frachel** [microsoft/vscode-maven#547]
**Describe the bug**
The extension is creating a temporary directory under linux at "/tmp/vscode-maven" that is owned by the the first user that runs the extension. Any subsequent user that runs a maven command via the extension gets an access denied error trying to create a directory underneath /tmp/vscode-maven since they don't have write permissions to the directory.

**To Reproduce**
1. Remote-SSH into a server from VScode (remote-ssh extension)
2. Run a maven command via VScode and the extension (assumes you have a workspace/folder with a maven project)
3. a /tmp/vscode-maven directory will be created, owned by the user you connect as in step #1 
4. Remote-SSH into the same server as a different user
5. Run a maven command via VScode and the extension
6. You'll get a popup about permission denied since the folder is owner by someone else and not world-writeable.

Note: The maven command will run ok, but the commandHistory.json that is being stored in the tmp folder won't get created, and the error popup each time will be a nuisance and will surely get people reporting it as an issue to our support team.

**Expected behavior**
Temp directories work for multiple users with no permission issues.

**Environments (please complete the following information as much as possible):**
 - OS: Linux (RHEL 7)
 - VS Code version: 1.50.1
 - Extension version 0.25.0

This looks like the function that gets the path. I tried setting TMPDIR and TMP environment variables (then we could have each user have their own folder in /tmp) but os.tmpdir() didn't seem to use them.

export function getPathToTempFolder(...args: string[]): string {
    return path.join(os.tmpdir(), ...args);
}

**Comment by Eskibear** [comment]
Thanks for reporting this issue. One simple approach is to append `os.userInfo().username` to the folder name, i.e. "vscode-maven-<username>".

**Comment by frachel** [comment]
How often is the extension released so we know when to expect the fix to be available? We'd rather not do the fix locally in the meantime and just stick with the official extension. Thanks!

**Comment by Eskibear** [comment]
We release it every 3 weeks (if there's new feature/fix). And the next release will be end of November.
