### ISSUE TITLE
A native exception occurred during create a Maven Project

### ISSUE THREAD

**Issue by Rooock** [microsoft/vscode-maven#550]
The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 5).

**Describe the bug**
An exception occurred while creating the maven project, VSCODE tips: "The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 5)."

**To Reproduce**
1. Ctrl + Shift + P, and Enter "Maven: Create Maven Project"
2. Choose "maven-archetype-archetype"
3. Choose "1.4"
4. Select Destination Folder
5. See error: "The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 5)."

**Expected behavior**
the Maven Project is created

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10 x64
 - java: 14.0.1 2020-04-14
 - VS Code version: 1.51.1
 - vscjava.vscode-maven-0.25.0
 - redhat.java-0.70.0
 - vsjava.vscode-java-debug-0.29.0
 - vsjava.vscode-java-dependency-0.14.0
 - vsjava.vscode-java-test-0.26.0

**Comment by Eskibear** [comment]
Do you have customized terminal settings? 
Are you able to open an integrated terminal in vscode by your own? The shortcut is <kbd>ctrl + ~</kbd> by default.

**Comment by Rooock** [comment]
> Do you have customized terminal settings?
> Are you able to open an integrated terminal in vscode by your own? The shortcut is ctrl + ~ by default.

Oh no ! I can not open an integrated terminal in vscode.  It give me a error msg when I enter Ctrl + ~
"An exception occurred while creating the maven project, VSCODE tips: "The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 5)."

What happend ? I did not modify the default settings， in fact ，my vscode is just unzipped and install some extensions

**Comment by Eskibear** [comment]
> Oh no ! I can not open an integrated terminal in vscode.

And that must be the root cause. The extension asks vscode to open a terminal, and then pass the full command. 

Maybe something is wrong with your default terminal(CMD or Powershell) when vscode tried the launch it. My suggestions:
* you can F1 -> `Terminal: Select default shell`, select another one and try if you are able to open it.
* create a issue in vscode's repo https://github.com/microsoft/vscode/issues

**Comment by Rooock** [comment]
> * you can F1 -> `Terminal: Select default shell`, select another one and try if you are able to open it.

thanks a lot , I added this to the settings.json:
```json
"terminal.integrated.automationShell.linux": "C:\\WINDOWS\\System32\\cmd.exe",
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"
```

It works !

**Comment by Rooock** [comment]
thanks , Eskibear.
