### ISSUE TITLE
Rollback field have a semicolon " ; "

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/vscode-maven#551]
**To Reproduce**

1. Open Command Palette, execute the command Maven: Create Maven Project
2. Select an archetype
3. Observe rollback field have a semicolon " ; "

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10/Ubuntu Server 18.04 LTS/OS 10.15.3
 - VS Code version: 1.51.1
 - Extension version: 0.25.0

**Screenshots**
![image](https://user-images.githubusercontent.com/41051257/99501080-3c74b400-29b6-11eb-9fc4-45fbf603b301.png)

**Comment by Eskibear** [comment]
@ZhengJun003 Thanks, good catch. 
@CsCherrYY please take a look.

**Comment by CsCherrYY** [comment]
Thanks for reporting. I have opened a pull request #552 to solve this issue.
