### ISSUE TITLE
Feature request: Support to access the pom file corresponding to the jar package by clicking on the dependency

### ISSUE THREAD

**Issue by msdemt** [microsoft/vscode-maven#558]
## Suggestion

Support to access the pom file corresponding to the jar package by clicking on the dependency

## Examples

[step 1] open a maven project and add some dependency, for example
``` 
       <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>2.4.0</version>
        </dependency>
```
[step 2]
hold crtl and click the artifactId can't access the spring-boot-starter-2.4.0.pom

**Current Result**
can't access the spring-boot-starter-2.4.0.pom by clicking the dependency on maven project

**Expected Result**
vscode could access the spring-boot-starter-2.4.0.pom by clicking the dependency on maven project

**Comment by Eskibear** [comment]
It's feasible to do that. We can construct the file path and search local maven repository for it. 

However as below, if version is not explicitly defined here, (e.g. in parent pom), it's not easy to get the version and locate the pom file.
```xml
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
</dependency>
```

Another concern is, if it's not in local maven repository, things become complicated. E.g. Do we help to download in from Maven Central?

**Comment by msdemt** [comment]
Thanks Reply

**Comment by brillianceke** [comment]
<img width="644" alt="_20201216164502" src="https://user-images.githubusercontent.com/13117626/102325546-3c200680-3fbe-11eb-8f29-c887fc331258.png">

this is a problem , the local repsitory is not  "c:\Users\DELL\",  setting.mxl set local repository is :
<img width="613" alt="20201216164649" src="https://user-images.githubusercontent.com/13117626/102325651-59ed6b80-3fbe-11eb-9fbb-39dcbacd405f.png">

thinks !!

**Comment by Uniman-Su** [comment]
> `Unable to open 'springfox-swagger-ui-${swagger.version}.pom': Unable to read file 'c:\Users\DELL\.m2\repository\io\springfox\springfox-swagger-ui\${swagger.version}\springfox-swagger-ui-${swagger.version}.pom' (Error: Unable to resolve non-existing file 'c:\Users\DELL\.m2\repository\io\springfox\springfox-swagger-ui\${swagger.version}\springfox-swagger-ui-${swagger.version}.pom').`
> 
> this is a problem , the local repsitory is not "c:\Users\DELL", setting.mxl set local repository is :
> `<localRepository>D:\.m2</localRepository>`
> 
> thinks !!

I met the same problem
