### ISSUE TITLE
Resolve conflicting dependencies

### ISSUE THREAD

**Issue by FunnyYish** [microsoft/vscode-maven#559]
## Suggestion

add Dependency Exclusions

## Use Cases

Since Maven resolves dependencies transitively, it is possible for unwanted dependencies to be included in your project's classpath. For example, a certain older jar may have security issues or be incompatible with the Java version you're using. To address this, Maven allows you to exclude specific dependencies. Exclusions are set on a specific dependency in your POM, and are targeted at a specific groupId and artifactId. When you build your project, that artifact will not be added to your project's classpath by way of the dependency in which the exclusion was declared.

**Comment by Eskibear** [comment]
I understand the use case you mentiond. 

> For example, a certain older jar may have security issues or be incompatible with the Java version you're using.

In this case, the first step is to **find out** the incompatible dependency before you perform any action to **exclude** it. After that you take some action to "exclude" it. For the exclusion part, without VS Code, you can always mannually add `<exclusion>`  in pom.xml. So what kind of experience are you expecting? Click dependency node to mark it as "exclusion" or...

**Comment by FunnyYish** [comment]
Maybe like the  idea  [maven-hleper plugin](https://plugins.jetbrains.com/plugin/7179-maven-helper)

**Comment by Eskibear** [comment]
Looks good. As I mentioned above, the pre-requisites of the feature are:
* capability of finding conflicting dependencies. 
  * this extension is written in TS/JS, no convenient library/API for that. 
  * alternative is to parse output of [maven-dependency-plugin](https://maven.apache.org/plugins/maven-dependency-plugin/examples/resolving-conflicts-using-the-dependency-tree.html), but less robust.
* proper UI (vscode doesn't support such a dialog)
  * show dependencies in flat/hierarchical view (see #261)
  * highlight conflicts

Suggestions and PRs are welcome...

**Comment by Melody618** [comment]
hi, @FunnyYish. 

Since 0.32.0, dependency tree has been visualized in maven explorer and dependency exclusions are supported. Here is a [demo.](https://github.com/microsoft/vscode-maven/pull/651#issue-685005501) 
Maybe you can give it a try. Feedbacks, suggestions are welcome.

**Comment by FunnyYish** [comment]
no more better
