### ISSUE TITLE
Maven wrapper is not installed after opening a Maven wrapper project

### ISSUE THREAD

**Issue by bcaure** [microsoft/vscode-maven#575]
**Describe the bug**
After opening a folder containing a Maven Wrapper project, maven-wrapper is not installed and Maven plugins are not shown

**To Reproduce**
1. Open a folder containing files:
- .mvn
  + maven-wrapper.properties
- src
- mvnw
- mvnw.bat
- pom.xml
2. When prompted on "Maven wrapper is found on this folder, do you trust it", click on "yes"
3. When prompted on "This folder contains a Java project, do you want to import it?", click on "yes" 
4. No Maven plugin is visible in the Maven side view, even after refreshing the view, restart VSCode

**Expected behavior**
Maven wrapper should be installed, Maven plugins and goals should be displayed.

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: 1.52.1
 - Extension version: 0.27.1

**Additional context**
mvn is not in the PATH

**Comment by Eskibear** [comment]
Can you open "Output" panel, select "Maven for Java", and share the detailed output there?

![image](https://user-images.githubusercontent.com/2351748/105659470-c46dc180-5f03-11eb-9d64-54be3194ca56.png)

**Comment by bcaure** [comment]
Here it is:

`Spawn {"command":"\"c:\\temp\\create-maven-test\\vscode\\mvnw.cmd\"","args":["help:effective-pom","-Doutput=\"c:\\Users\\benth\\AppData\\Roaming\\Code\\User\\workspaceStorage\\0b0a7b32ebb44dcd5543d8642488ec67\\vscjava.vscode-maven\\2f8609d6b43678435bbe1ec57ca2545a\"","-f","\"c:\\temp\\create-maven-test\\vscode\\pom.xml\""]}
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain`

**Comment by Eskibear** [comment]
This extension fetches information from output of `mvn help:effective-pom` command. 

> Just to mention I don't have mvn in my PATH

Yes, so this extension chose to use the maven wrapper under your project. `c:\\temp\\create-maven-test\\vscode\\` should be your workspace root folder, right?

> Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain

Something went wrong when it ran `mvnw` commands. Looks like the maven wrapper itself was not working well. 
Can you try running some commands in a terminal (e.g CMD) with your maven wrapper? For example `mvnw clean`, see if it works well.

**Comment by bcaure** [comment]
I realized that maven-wrapper.jar is not present in the .mvn/wrapper, mvnw command didn't install it automatically.
After running:

`mvn -N io.takari:maven:0.7.7:wrapper`

And opening the folder it worked.

In my mind the maven-wrapper.jar was not mandatory, my mistake.
