### ISSUE TITLE
Include .vsix File in Release Or Upload Latest Version (0.27.0 / 0.27.1) to https://open-vsx.org/

### ISSUE THREAD

**Issue by TomHermanSAP** [microsoft/vscode-maven#576]
Can you upload the `.vsix` file to the latest release (currently 0.27.0) and futures releases in the [Releases section](https://github.com/microsoft/vscode-maven/releases) in this Github repository?

Currently only `Source code (zip)` and `Source code (tar.gz)` are attached to each release.

If not, can you upload the latest release (0.27.0 / 0.27.1) to [https://open-vsx.org/](https://open-vsx.org/)? Latest version in open-vsx.org is [0.21.2](https://open-vsx.org/extension/vscjava/vscode-maven).

<br />

Thank you!!

**Comment by Eskibear** [comment]
We never did that before. The extension is built and published by internal pipeline after validation. And I don't know who uploaded previous releases in open-vsx.org...    

Corresponding `.vsix` files can be found in vscode's marketplace page: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-maven  See "Download Extension" link under section "Resources".
