### ISSUE TITLE
Displayed project name missing groupId

### ISSUE THREAD

**Issue by yaojinyang** [microsoft/vscode-maven#590]
**Describe the bug**
Displayed project name only uses artifactId defined in .pom. In multi-module project, when modules have same artifactId but different groupIds, Maven view displays same project name, which makes users impossible to distinguish the modules from name. 

**To Reproduce**
1. Import https://github.com/piranhacloud/piranha into VS Code
2. Wait till the whole project is imported 
3. Open Maven view
4. Check project names

**Expected behavior**
Each project should have a unique name.

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: 1.54.3
 - Maven extension version: 0.28.0

**Screenshots**
![Maven issue](https://user-images.githubusercontent.com/54611965/111573066-c279fd80-87e4-11eb-85d8-b93e719600bb.PNG)

**Comment by mnriem** [comment]
Please also consider allowing to switch from the POM groupId:artifactId to the POM name section

**Comment by Eskibear** [comment]
Below change looks fair:
* label of the item: use `name` if provided, `artifactId` as fallback.
* set `groupId:artifactId` as "treeItem.description" which is available now.

![image](https://user-images.githubusercontent.com/2351748/112275551-b39abb80-8cba-11eb-9701-639ed9efe40b.png)

**Comment by Eskibear** [comment]
shipped in v0.29.0
