### ISSUE TITLE
I can not find pom.xml from my local repo

### ISSUE THREAD

**Issue by cowcomic** [microsoft/vscode-maven#591]
I moved my local repo to disk D from C
but the plugin always find pom from C
![image](https://user-images.githubusercontent.com/4745969/111726098-38dd3500-88a3-11eb-84ee-a19fa6628f85.png)

my maven setting.xml
![image](https://user-images.githubusercontent.com/4745969/111726166-58745d80-88a3-11eb-8f70-05473a1f65cf.png)

**Comment by Eskibear** [comment]
Now it only reads settings from ~/.m2  . We can add a setting specifying your settings.xml file location. @mannixsuo is working on this , see https://github.com/microsoft/vscode-maven/pull/581

After moving local repo from C:/ to D:/ , where is your maven setting.xml now? Is it a global setting or per project?

**Comment by cowcomic** [comment]
> Now it only reads settings from ~/.m2 . We can add a setting specifying your settings.xml file location. @mannixsuo is working on this , see #581
> 
> After moving local repo from C:/ to D:/ , where is your maven setting.xml now? Is it a global setting or per project?

my maven setting.xml is in my maven config directory

> D:\tools\apache-maven-3.6.3\conf\

it's a global setting

**Comment by Eskibear** [comment]
ok. 
Now we parse maven local repo from settings.xml, and we want to add a setting `maven.settingsFile` specifying the location. 

For simplicity it can be a global setting. Do you know any use case about project-specific settings.xml?

**Comment by cowcomic** [comment]
> ok.
> Now we parse maven local repo from settings.xml, and we want to add a setting `maven.settingsFile` specifying the location.
> 
> For simplicity it can be a global setting. Do you know any use case about project-specific settings.xml?

where is the plugin read direcory defaultly?
I can copy setting.xml into the directory to solve the problem currently

i usually use global setting
we don't deploy to center repo, just to our private maven repo, so wo don't have to prepare different setting
one setting contains all

**Comment by Eskibear** [comment]
@cowcomic for the moment, it's hardcoded as ~/.m2/settings.xml, "~" should be `%USERPROFILE%` on Windows.

**Comment by cowcomic** [comment]
> @cowcomic for the moment, it's hardcoded as ~/.m2/settings.xml, "~" should be `%USERPROFILE%` on Windows.

OK, i solve it temporary
I use mklink making a soft link for .m2 from D to %USERPROFILE%
hope the update

**Comment by Eskibear** [comment]
`maven.settingsFile` has been added since 0.29.0
