### ISSUE TITLE
Exception Exception calling "DownloadFile" with "2" argument

### ISSUE THREAD

**Issue by schrummy14** [microsoft/vscode-maven#606]
**Describe the bug**
I try to create a new project with maven. While trying to build the brand new project, I get the following:
PS C:\Users\mschramm\Documents\consultingHelp\inMotionCare\javaTester> & "C:\Users\mschramm\.vscode\extensions\vscjava.vscode-maven-0.28.0\resources\maven-wrapper\mvnw.cmd" org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate -DarchetypeArtifactId="archetype-quickstart-jdk8" -DarchetypeGroupId="com.github.ngeor" -DarchetypeVersion="2.0.0"
Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."
At line:1 char:282
+ ... pe]::Tls12; $webclient.DownloadFile('https://repo.maven.apache.org/ma ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain

**To Reproduce**
1. Open Visual Studio Code
2. Start a new Java project
3. Select the maven project type
4. Select the quickstart archtype
5. Select version 1.4
6. Select version 1.4
7. See Error

**Expected behavior**
It creates a new java project

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: 1.55
 - Extension version: 0.28

**Screenshots**

**Additional context**

**Comment by Eskibear** [comment]
> PS C:\Users\mschramm\Documents\consultingHelp\inMotionCare\javaTester> & "C:\Users\mschramm.vscode\extensions\vscjava.vscode-maven-0.28.0\resources\maven-wrapper\mvnw.cmd" org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate -DarchetypeArtifactId="archetype-quickstart-jdk8" -DarchetypeGroupId="com.github.ngeor" -DarchetypeVersion="2.0.0"

Because you don't have Maven installed locally, so it fallbacks to use a Maven wrapper embedded in this extension. But the command is strange.
Your target folder is: `C:\Users\mschramm\Documents\consultingHelp\inMotionCare\javaTester`  **(correct me if wrong)**
Embedded Maven wrapper is located in: `C:\Users\mschramm.vscode\extensions\vscjava.vscode-maven-0.28.0\resources\maven-wrapper\mvnw.cmd` 

What I expect should include a `-DoutputDirectory`, and cwd should be different, as below:

> PS C:\Users\mschramm.vscode\extensions\vscjava.vscode-maven-0.28.0\resources\maven-wrapper> & "C:\Users\mschramm.vscode\extensions\vscjava.vscode-maven-0.28.0\resources\maven-wrapper\mvnw.cmd" org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate -DarchetypeArtifactId="archetype-quickstart-jdk8" -DarchetypeGroupId="com.github.ngeor" -DarchetypeVersion="2.0.0" -DoutputDirectory="C:\Users\mschramm\Documents\consultingHelp\inMotionCare\javaTester"


I'll take a deep look.

**Comment by Eskibear** [comment]
@schrummy14

I cannot reproduce it.
![image](https://user-images.githubusercontent.com/2351748/113828316-d4810780-97b6-11eb-8a9e-ef43ecf820c0.png)


Can you provide more details:
* Do you have Maven installed on  your machine?
* What's the output if you run `mvn --version` in powershell?
* What's the value of your vscode setting `maven.executable.path`?
* If you can reproduce it again, show me the full picture of the terminal.

**Comment by schrummy14** [comment]
Hello,
I was able to get it to work by copying over the .mvn folder located at `C:\Users\mschramm\.vscode\extensions\vscjava.vscode-maven-0.28.0\resources\maven-wrapper`.

mvn --version 
`Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Users\mschramm\.m2\wrapper\dists\apache-maven-3.6.3-bin\1iopthnavndlasol9gbrbg6bf2\apache-maven-3.6.3
Java version: 11.0.8, vendor: AdoptOpenJDK, runtime: C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"`

maven.executable.path
`C:\Users\mschramm\.vscode\extensions\vscjava.vscode-maven-0.28.0\resources\maven-wrapper\mvnw`

**Comment by schrummy14** [comment]
Here is the entire terminal
`Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\mschramm\Documents\consultingHelp\inMotionCare\javaTester> cd "c:\Users\mschramm\Documents\consultingHelp\inMotionCare\javaTester"
PS C:\Users\mschramm\Documents\consultingHelp\inMotionCare\javaTester> & "C:\Users\mschramm\.vscode\extensions\vscjava.vscode-maven-0.28.0\resources\maven-wrapper\mvnw.cmd" org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate -DarchetypeArtifactId="maven-archetype-quickstart" -DarchetypeGroupId="org.apache.maven.archetypes" -DarchetypeVersion="1.4"
Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."
At line:1 char:282
+ ... pe]::Tls12; $webclient.DownloadFile('https://repo.maven.apache.org/ma ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain
PS C:\Users\mschramm\Documents\consultingHelp\inMotionCare\javaTester>`

I also had it work with the .mvn folder inside `C:\Users\mschramm\Documents\consultingHelp\inMotionCare`

**Comment by schrummy14** [comment]
Sorry about the formatting of the last one... Here is a picture.
![image](https://user-images.githubusercontent.com/25237907/114609236-2ff24000-9c64-11eb-8950-15b915965121.png)

**Comment by Eskibear** [comment]
mvnw searches required files (under .mvn) in current directory, and it's usually along with your project. The mvnw embedded in this extension is served as a fallback only to create maven projects when you don't have local Maven distribution installed.

> maven.executable.path: Specifies absolute path of your 'mvn' executable. 

@schrummy14 Setting `maven.executable.path` is for `mvn` instead of `mvnw`. Since you have mvn installed and in PATH, please reset  `maven.executable.path` and give it a try.

**Comment by Eskibear** [comment]
let me know if that works.

**Comment by schrummy14** [comment]
It is working now... Thank you
