### ISSUE TITLE
Sometimes the identifier group value will show "undefined"

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/vscode-maven#610]
**To Reproduce**
1. Clone and open [spring-hadoop-samples](https://github.com/spring-projects/spring-hadoop-samples.git)
2. Click on the project item and expand the plugins node
3. See error

**Environments (please complete the following information as much as possible):**

- OS: Windows 10/Mac OS 10.15.7
- VS Code version: 1.55.0
- Extension version 0.28.0

**Screenshots**
![image](https://user-images.githubusercontent.com/41051257/113839567-617d8e00-97c2-11eb-84fb-7bae37c38df8.png)

**Comment by Eskibear** [comment]
confirmed. Extension doesn't deal with `relativePath` of parent pom.
```
<relativePath>../parent/pom.xml</relativePath>
```
