### ISSUE TITLE
Can't show a dropdown list of popular maven archetypes

### ISSUE THREAD

**Issue by SunnyChen1** [microsoft/vscode-maven#611]
**Reproduce**
1. Open a maven project 
2. Open command palette, Find and select Maven: Update Maven Archetype Catalog
3. Then Execute the command Maven: Create Maven Project, show empty archetype

**Environments (please complete the following information as much as possible):**

OS: Windows 10/Mac OS 10.15.7
VS Code version: 1.55.0
Extension version 0.28.0
**Screenshots**
![image](https://user-images.githubusercontent.com/63633836/113846670-4eba8780-97c9-11eb-8909-946df86706d6.png)

**Comment by Eskibear** [comment]
I assume it's a long existing issue? Can you give it a try of older version e.g. 0.27.0?

**Comment by Eskibear** [comment]
BTW the error message is unrelevant, but rather another issue.

**Comment by Eskibear** [comment]
regression introduced from https://github.com/microsoft/vscode-maven/pull/592/files#diff-a0eee5b9220a1862c39f5eb3b0524a80a994659085068cd00506c958dd028e63R120

**Comment by SunnyChen1** [comment]
Verify fixed on buildId=14995569, so closed it.
