### ISSUE TITLE
Creating Java Project with Maven Quickstart Archetype: The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by rhystedstone** [microsoft/vscode-maven#623]
**Describe the bug**
After inputting the package and artifact id, then choosing the directory, the terminal spits out the following:
```
> Executing task: "C:\Maven\apache-maven-3.8.1\bin\mvn.cmd" org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate -DarchetypeArtifactId="maven-archetype-quickstart" -DarchetypeGroupId="org.apache.maven.archetypes" -DarchetypeVersion="1.4" -DgroupId="com.example" -DartifactId="demo" <

The filename, directory name, or volume label syntax is incorrect.
The terminal process "cmd.exe /c "C:\Maven\apache-maven-3.8.1\bin\mvn.cmd" org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate -DarchetypeArtifactId="maven-archetype-quickstart" -DarchetypeGroupId="org.apache.maven.archetypes" -DarchetypeVersion="1.4" -DgroupId="com.example" -DartifactId="demo"" failed to launch (exit code: 1).

Terminal will be reused by tasks, press any key to close it.
```

**To Reproduce**
1. Go to Explorer
2. Press "Create Java Project"
3. Press "Maven"
4. Press any archetype
5. Input package id, artifact id and parent directory
6. Errors

**Expected behavior**
I expected the terminal to open for setting up the project, rather than VSCode's gui asking for the package id and artifact id. This problem wasn't occuring on 25/04/21 when I created a previous java project with the same methods.

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10 Pro 20H2 (19042.928)
 From Settings > About:
> Edition	Windows 10 Pro
> Version	20H2
> Installed on	‎12/‎03/‎2021
> OS build	19042.928
> Experience	Windows Feature Experience Pack 120.2212.551.0

 - VS Code version:
> Version: 1.55.2 (user setup)
> Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
> Date: 2021-04-13T09:35:57.887Z
> Electron: 11.3.0
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Windows_NT x64 10.0.19042
 - Extension version v0.30.0

**Screenshots**
*The console's error*
![Console On Error](https://user-images.githubusercontent.com/12123847/116817584-fe7fdc80-ab5e-11eb-8839-f41d799c0aec.png)

*When run in external terminal*
![When run separately in Windows Terminal (Exact same command as VSCode](https://user-images.githubusercontent.com/12123847/116817666-6afadb80-ab5f-11eb-8c22-5e81dd684b76.png)

**Additional context**
I have tried the same steps with Windows Terminal, CMD and Powershell configured. The command fully works if run via a terminal, just not in vscode.

**Comment by nghuyenthevinh2000** [comment]
I face the same problem as well

**Comment by rhystedstone** [comment]
I can confirm that this also does not work on my other machine using the same process.
![The same process on my laptop](https://user-images.githubusercontent.com/12123847/116951809-cc669b80-ac80-11eb-8698-3e785ca772db.png)

**Comment by Eskibear** [comment]
If Maven is added into PATH and `maven.executable.path` is not set, it works without any problem.
```
> Executing task: mvn org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate -DarchetypeArtifactId="maven-archetype-quickstart" -DarchetypeGroupId="org.apache.maven.archetypes" -DarchetypeVersion="1.4" -DgroupId="com.example" -DartifactId="demo" <

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
...
```

I can reproduce the issue when I point `maven.executable.path` to my local maven binary. 
```
> Executing task: "C:\Users\zy199\AppData\Local\Maven\apache-maven-3.6.0\bin\mvn.cmd" org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate -DarchetypeArtifactId="maven-archetype-quickstart" -DarchetypeGroupId="org.apache.maven.archetypes" -DarchetypeVersion="1.4" -DgroupId="com.example" -DartifactId="demo" <

The filename, directory name, or volume label syntax is incorrect.
The terminal process "cmd.exe /c "C:\Users\zy199\AppData\Local\Maven\apache-maven-3.6.0\bin\mvn.cmd" org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate -DarchetypeArtifactId="maven-archetype-quickstart" -DarchetypeGroupId="org.apache.maven.archetypes" -DarchetypeVersion="1.4" -DgroupId="com.example" -DartifactId="demo"" failed to launch (exit code: 1).
```

@rhystedstone @nghuyenthevinh2000 Have you explicitly set `maven.executable.path`?

BTW, I tried outside VS Code, in CMD and PowerShell. Looks like CMD doesn't parse quotation marks well.
![image](https://user-images.githubusercontent.com/2351748/117390011-f689b900-af1f-11eb-9ae1-d5e646d1678a.png)

**Comment by Eskibear** [comment]
Why I quote the maven executable path? Because there can be whitespace in it (it's a common case).

Inspired by https://stackoverflow.com/a/6378038 , I want to quote the full command with `"` before prepending `cmd /c`. 
The final command would be something like below:

cmd /c ""c:\Users\zy199\Work\vscode-maven\resources\maven wrapper\mvnw.cmd" org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate -DarchetypeArtifactId="maven-archetype-quickstart" -DarchetypeGroupId="org.apache.maven.archetypes" -DarchetypeVersion="1.4" -DgroupId="com.example" -DartifactId="demo""

Note the maven path contains a whitespace, and it works in my local machine. 

I'll create a PR soon, and please give it a try and let me know if there's any issue.

**Comment by Eskibear** [comment]
shipped in 0.30.1, please give it a try.

**Comment by nghuyenthevinh2000** [comment]
thanks a lot.

**Comment by ahsansoftengineer** [comment]
Same Problem with me
