### ISSUE TITLE
Mvn under windows with git-bash as terminal

### ISSUE THREAD

**Issue by j3rem1e** [microsoft/vscode-maven#636]
**Describe the bug**

On windows, when using git bash as the terminal, this extension generates a wrong command lines : the file is referenced as a lnux path, however the mvn windows executable doesn't understand this syntax.

for example, it generates mvn -f "/mnt/c/my/project/pom.xml" instead of mvn -f "c:/my/project/pom.xml"

**To Reproduce**

1. configure vscode to use gitbash as the favorite terminal
2. Open a maven project
3. Try to compile this project from the maven view

**Expected behavior**

pom location as generated as real windows path.

**Environments (please complete the following information as much as possible):**
 - OS: Window 10
 - VSCode: 1.56.2
 - Maven ext 0.30.1

**Comment by Eskibear** [comment]
Similar to #633 

I'm wondering if it's wrongly recognized as WSL, because we only do path conversion (to unix-like format) for WSL. 
Can you check you settings, and let me know if there's any terminal related settings?

**Comment by j3rem1e** [comment]
You're right. I was using the old "terminal.integrated.shell.windows" settings. by switch to the new profiles settings, I have now the same error as 633. 

I assume it will be fixed in a future vscode release, thanks !
