### ISSUE TITLE
maven for java issue

### ISSUE THREAD

**Issue by SONU74268** [microsoft/vscode-maven#639]
Issue Type: <b>Bug</b>

it's cause a problem when i try want to use maven it doesn't show it's feature.

Extension version: 0.30.1
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD PRO A6-7350B R5, 5 COMPUTE CORES 2C+3G      (2 x 2994)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.86GB (1.00GB free)|
|Process Argv|--crash-reporter-id 1f81fa05-d8dc-4c70-8d4c-c7b3329185f5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscorehovct:30302760
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by Eskibear** [comment]
Please provide more details about the "problem" and which "feature", and the steps to reproduce it.

**Comment by SONU74268** [comment]
> Please provide more details about the "problem" and which "feature", and the steps to reproduce it. 
I'm not facing that issues anymore. It's kind of shocking when I close a maven project and load a new maven project after opening a new project the maven error is gone.

**Comment by Eskibear** [comment]
ok, I'm closing it.
