### ISSUE TITLE
Self referencing maven modules should not trigger an infinite loop

### ISSUE THREAD

**Issue by boriswaguia** [microsoft/vscode-maven#644]
**Describe the bug**
Vscode enters an infinite loop while trying to compile a falsy module setup. It should instead break the build should break with an error stating that a module is self-referencing itself the same way the maven cli report it.

**To Reproduce**
1. Create a parent maven project with packaging type `pom` - `parent`
2. Create a submodule (module-1) project with the packaging type '`jar`' in the previous parent project
3. Add a dependency of `module-1` in `parent` with the save version (${project.version})
4. See the error: Vscode will enter an infinite loop trying to resolve the dependency

**Expected behavior**
Vscode-maven should fail the compilation with the following message as the maven-cli does it:

**Environments (please complete the following information as much as possible):**
 - OS: OSX  BIg Sur
 - VS Code version: [Version: 1.56.2 Commit: 054a9295330880ed74ceaedda236253b4f39a335]
 - Extension version [0.31.0]

**Screenshots**

Current behaviour (The build will never get past the 339/1000 as displayed in the console)

<img width="1058" alt="Screenshot 2021-06-10 at 10 40 39" src="https://user-images.githubusercontent.com/1632187/121496680-fd9e5e00-c9da-11eb-84fb-7149860c140b.png">

Expected Build Error In vscode:

<img width="964" alt="Screenshot 2021-06-10 at 10 41 27" src="https://user-images.githubusercontent.com/1632187/121497030-50781580-c9db-11eb-9cb2-1428540aef67.png">

**Additional context**

**Comment by Eskibear** [comment]
Importing Maven project is managed by [vscode-java](https://github.com/redhat-developer/vscode-java) extension. Can you transfer this issue to https://github.com/redhat-developer/vscode-java/issues ?

**Comment by boriswaguia** [comment]
Hello @Eskibear 

Done [#1977](https://github.com/redhat-developer/vscode-java/issues/1977) !

Thanks.
