### ISSUE TITLE
Feature request: Automatically open newly created projects

### ISSUE THREAD

**Issue by rhystedstone** [microsoft/vscode-maven#653]
## Suggestion
The ability to have projects automatically open after being created.
It would just be a convenience and a simple way of showing that the project has been created successfully.

## Use Cases
Currently, you just have to navigate to the project's directory, or press the small "open" button after creation.

## Examples
It could simply be another option in the settings file, which either makes projects automatically open or not.

**Comment by Eskibear** [comment]
> or press the small "open" button after creation.

The "open" button has a normal size. I'm wondering if it's as inconvenient as you described. Are you creating a lot of projects at the same time? I'm interested in your use case, can you describe more about it?

**Comment by Eskibear** [comment]
A new setting `maven.projectOpenBehavior` was added in #717
