### ISSUE TITLE
Automatically open the new created maven project

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-maven#662]
reference: https://www.reddit.com/r/vscode/comments/o8muvl/maven_for_java_extension_automatically_open/

Or make a setting to control it.

Anyway, if a user creates a new Maven project, it looks like having a large possibility to open it to do sth after that.

**Comment by Eskibear** [comment]
>  it looks like having a large possibility to open it 

Yes. But if a single project is created, I don't think it's that annoying to ask for confirmation only once. 

Technically it's feasible to add a setting `maven.project.defaultOpenMethod`, and set it to empty by default.  


BTW, in Spring Initializr we have this setting as required by 3rd party integration.

**Comment by Eskibear** [comment]
Do you want me to include it in the coming release?
