### ISSUE TITLE
FAQ Guidance error pop-up when set maven.executable.path to mvnw.cmd

### ISSUE THREAD

**Issue by JanusWu** [Microsoft/vscode-maven#67]
**Describe the bug**
Set value of maven.executable.path to mvnw/mvnw.cmd path and save, get below error.
But in fact, for the maven wrapper, we can succefully execute maven command .

**To Reproduce**
1. Open project todo-app-java-on-azure in vscode
2. set "maven.executable.path" to mvnw/mvnw.cmd path and save

**Expected behavior**
No error.

**Environments :**
 - OS: Windows 10/Linux/OS X
 - VS Code version: 1.24.1
 - Extension version 0.9.0 (build #234)

**Screenshots**
![image](https://user-images.githubusercontent.com/17060520/42314993-e6646724-8078-11e8-8269-55bdab40a311.png)

![image](https://user-images.githubusercontent.com/17060520/42315020-f2feb0ca-8078-11e8-893c-02456503d597.png)

**Comment by Eskibear** [comment]
fixed in #69 , please help to verify.

**Comment by JanusWu** [comment]
Verified with build[ #237](https://vscjavaci.cloudapp.net/job/vscode_maven/job/vscode-maven.vsix/237/), the issue is gone.
