### ISSUE TITLE
Improve the progress notification when resolving the dependencies

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-maven#674]
Currently we are using progress notification when loading the dependencies, which it can be improved in following part

### Give more transparency

Try to report some more meaningful messages to reflect current status, currently seems it will always show as `Generating Dependency tree xxxx...`

### Give more control
Since I believe in most cases, this is a long-run action, in case that user want to dismiss the notification, at least we need to support `cancel` action for it.

**Comment by Melody618** [comment]
marked as enhancement

**Comment by jdneo** [comment]
Another issue:

When on a clean machine (without any cache). Trigger `Show dependencies` and expand the `Dependencies` node will pop two progress notifications with same content.

**Comment by Eskibear** [comment]
>  need to support cancel action for it.

Agree. 

What I prefer is status bar progress.

**Comment by Eskibear** [comment]
mitigated by moving it to status bar.
