### ISSUE TITLE
Show omitted dependencies in ignored style?

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-maven#676]
Not sure if it's doable or not. (Feel free to close it if it's not)

For omitted dependencies, I think it could be better to show then in grey color, just like the git ignored files in the file explorer

![image](https://user-images.githubusercontent.com/6193897/127109554-f3fed403-712c-4c03-a22b-91242d622c3a.png)

**Comment by Melody618** [comment]
Now we show dependencies that are omitted for conflicts in a warning style. See screenshot in https://github.com/microsoft/vscode-maven/pull/664#issue-695729355 

And it is good advice to show dependencies that are omitted for duplicates in an ignored style for better visualization.

**Comment by Eskibear** [comment]
Let me take this. Proposed styling with badge and tooltips

de-emphasize duplicated items as below
![image](https://user-images.githubusercontent.com/2351748/127126294-f8f34a97-bfb8-4a88-b4ad-2395ab9ea906.png)

warn conflict items as below
![image](https://user-images.githubusercontent.com/2351748/127126392-0f24b663-a8f6-475d-9f87-484c79358ca5.png)

**Comment by Melody618** [comment]
It looks great. 👍
