### ISSUE TITLE
Can dismiss the warnings in the pom.xml

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-maven#677]
Project which has several dependencies will have such conflicts with a high possibility. It could be better if some controls can give to the user, such as:

- code action to dismiss the warnings in a pom.xml
- turn off the conflicts detection (Maybe he just want to see all the direct dependencies and their versions)

**Comment by Melody618** [comment]
We provide warnings and quick fixes for users in case they meet weird bugs that are probably caused by conflict dependencies. So it is important to show warnings in the pom.xml.

Waiting to see if there are other users think dismissing is necessary.

**Comment by Eskibear** [comment]
a boolean setting like `maven.warnConflictsInDiagnostics` should work. Default value is true.
