### ISSUE TITLE
.pom file not correctly highlighted

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-maven#696]
**Steps to reproduce:**
1. Expand "dependencies". 
2. Click inline "go to definition" button of a node with depth >=2.
3. xxx.pom is opened as plaintext. 

![image](https://user-images.githubusercontent.com/2351748/128675142-ce3b90f9-8f56-4756-8d1b-b4cf88b52cc1.png)

**Expected Behavior:**
xxx.pom file is opened as XML.

**Comment by Eskibear** [comment]
possible solution:

1. investigate if there's way to explicit map .pom file to XML langauge.
2. before `showTextDocument`, call `setTextDocumentLanguage` first.

**Comment by Melody618** [comment]
use option 2. And it is after `showTextDocument`, call `setTextDocumentLanguage` that it works.
