### ISSUE TITLE
Missing ▶ icon when expanding Plugins or Dependencies node

### ISSUE THREAD

**Issue by doggy8088** [microsoft/vscode-maven#700]
**Describe the bug**

If any node inside MAVEN view been expanded, all lifecycle unable to start with a right-triangle icon ( ▶ ).

**To Reproduce**

1. When all nodes been folded. The ▶ button shown.

    ![image](https://user-images.githubusercontent.com/88981/129061778-3ec0ed0d-62f9-4e57-8ef9-f671cababcf1.png)

2. When any node been expanded. The ▶ button disappeared.

    ![image](https://user-images.githubusercontent.com/88981/129061896-87234fdc-163f-44bd-a1a1-aeb3705521cf.png)

**Expected behavior**

**Environments (please complete the following information as much as possible):**
 - OS: `Windows_NT x64 10.0.19043`
 - VS Code version: `v1.59.0`
 - Extension version: `v0.32.2`

```txt
Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
```

**Screenshots**
See **To Reproduce**.

**Additional context**
N/A

**Comment by Eskibear** [comment]
I cannot reproduce it.
![image](https://user-images.githubusercontent.com/2351748/129173826-a7fd42bd-2492-4a62-8567-44e3f50ce7ee.png)


From you screenshot, I see a horizontal scrollbar there. Please check if that's reason you don't see the inline button.

**Comment by doggy8088** [comment]
@Eskibear I made a short video clip. Please check: https://youtu.be/YHU38F7k9zA

**Comment by Eskibear** [comment]
yes, I already see it from your screenshot. There is a **horizontal scrollbar**, and I guess if you scroll it you'll see the inline button.
![image](https://user-images.githubusercontent.com/2351748/129292048-583cfbdd-0053-4974-891e-74925d982540.png)

Please check if you explicitly turned  `workbench.list.horizontalScrolling` on. 
![image](https://user-images.githubusercontent.com/2351748/129292160-42cdf553-60d2-49af-9ee3-2246f3c78ab9.png)

**Comment by doggy8088** [comment]
WOW, you have very good eyesight. I never realized there is a horizontal scrolling bar down there. 😅 👍

Yes, you are right. I do have a `"workbench.list.horizontalScrolling": true` user setting been defined explicitly long long time ago.

I think https://github.com/microsoft/vscode-maven/pull/702 can solve this UX issue if `workbench.list.horizontalScrolling` been enabled.
