### ISSUE TITLE
Suppress discovery of the pom files in some workspace folders

### ISSUE THREAD

**Issue by dbarvitsky** [microsoft/vscode-maven#705]
## Suggestion

I would like to be able to configure the plugin to not look into certain workspace folders when searching for `pom.xml` files, notably `it` (integration tests) and `**/target`. The `**/target` should probably be excluded by default, although this might be subject to a debate.

## Use Cases

The problem is rare enough, so adding configuration option will likely suffice. Below are two options (both will work for my case, but there are pros and cons to each).

**Option 1**: limit the discovery to the master `pom.xml` and only include its sub-modules. This may work for some setups, as people usually do not include the `it` (integration tests) folders in their master pom. This will work poorly when the workspace does not include the master pom file (i.e. individual modules are set up in their individual repositories). Latter is more exotic setup, but still happens. This will not work at all if the workspace includes several unrelated Maven projects, or if the master `pom.xml` is not in the workspace root.

**Option 2**: provide options to include or exclude certain folders in the workspace in `pom.xml` discovery. This will require a bit more work from a developer to set up, but will likely be sufficient to accommodate for even very exotic project setups.

## Examples

Real-life example: my project setup is a multi-module Maven project. It involves heavy use of code generators and integration tests. The code generators (like Swagger, for instance), create pom files in the `./target` folders. The integration tests contain folders with `pom.xml` files in them, that are not part of the code that IDE should be concerned with. Presently `vscode` with maven plugin tries to discover all of `pom.xml` files in the workspace folder, which introduces a lot of garbage into development experience.

For instance the "Errors" tab would have thousands of irrelevant errors and warnings, and intellisense would often be confused (as integration tests can contain duplicate classes and artifacts). If any of those `pom.xml` files from `./target` and `it` folders contain any issues (for instance, lack of `m2e` mapping for certain phases) the `vscode` would start reporting build errors even though none of these `pom.xml` files are reachable from the project loaded into the workspace.

If I could exclude the `**/target` and `./it` folders through configuration, or force the IDE to only include modules defined in the main `./pom.xml`, my developer experience with `vscode` would be a whole lot better.

**Comment by Eskibear** [comment]
There's a setting `maven.excludedFolders`, which is probably what you want. 

See https://github.com/microsoft/vscode-maven#settings

**Comment by Eskibear** [comment]
let me know if that's what you need.
