### ISSUE TITLE
The names of projects in the maven pane shows the literal content within the name tag of the XML rather than the resolved content.

### ISSUE THREAD

**Issue by JasonWThompson** [microsoft/vscode-maven#706]
**Describe the bug**
If the pom of a maven project uses a variable for the name tag, said variable will be used as the name in the maven pane rather than the resolved name.

**To Reproduce**
1. Create a pom.
2. Add the `<name>` tag to said pom with a value of `${project.artifactId}`
3. Expand out the 'Maven' pane.

**Expected behavior**
The label should be the resolved name.

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: [e.g. 1.59.0]
 - Extension version [e.g. 0.32.2]

**Screenshots**
![image](https://user-images.githubusercontent.com/7197333/130100647-ae45d7b8-8f03-463d-8de4-3244afab8acf.png)

![image](https://user-images.githubusercontent.com/7197333/130101190-625d5996-209a-4d17-bb0b-638b14b366d1.png)

**Additional context**
N/A

**Comment by Eskibear** [comment]
See https://github.com/microsoft/vscode-maven/issues/646

**Comment by JasonWThompson** [comment]
Thanks, @Eskibear. Closing as duplicate.
