### ISSUE TITLE
change dependency tree icon

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-maven#707]
For consisitency please use below icon for "Dependency Menu", and please add TODO comment to switch directly to codicon `folder-library` after vscode's next release. 
https://github.com/microsoft/vscode-codicons/blob/main/src/icons/folder-library.svg

For omitted dependencies (duplicate/conflict), let's keep discussion in this thread.

**Comment by Eskibear** [comment]
For duplicate/conflict dependencis, one proposal is to share the same icon with strikethrough line.

strikethrough line represents "omitted". Decoration badge (C for conflict / D for duplicate) and corresponding color provide extra information of "duplicate" and "conflict". 

It looks like:
![image](https://user-images.githubusercontent.com/2351748/130212580-fc0f78c4-f3c6-4904-8cde-e8a33211d262.png)

**Comment by Eskibear** [comment]
@jdneo @testforstephen @CsCherrYY @akaroml  please comment about above idea.

**Comment by CsCherrYY** [comment]
How can we get the icon (with strikethrough line)?

**Comment by Eskibear** [comment]
it's designed by @Melody618 and checked in repository as a .svg file.

**Comment by jdneo** [comment]
Since the description and the decoration has enough information the tell the user the node status. Actually I think we can just use the icon **without** strikethrough line for all nodes.
