### ISSUE TITLE
open POM under local maven repo in read-only mode

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-maven#718]
It's a follow-up item of #428 

So far vscode has no such API, but we can workaround it via ContentProvider API, the same way we show effectivePOM and dependency list now.

**Comment by Eskibear** [comment]
To verify:

1. Open a Maven project
2. hover on a dependency node, press "ctrl" and click
3. it should open corresponding .pom file in readonly mode.

Note: if "version" is not directly specified in dependency node, you should calculate its effective pom first.

**Comment by gigitacoo** [comment]
> 

Sorrry for reply in a closed issue, But i tried press "command" and click on a dependency and it raises an error like this:

`Unable to open 'pring-boot-starter-test-2.2.4.RELEASE.pom': Unable to read file '/Users/hilion/.m2/repository/org/springframework/boot/spring-boot-starter-test/2.2.4.RELEASE/spring-boot-starter-test-2.2.4.RELEASE.pom' (Error: Unable to resolve non-existing file '/Users/hilion/.m2/repository/org/springframework/boot/spring-boot-starter-test/2.2.4.RELEASE/spring-boot-starter-test-2.2.4.RELEASE.pom').

settings.xml set local repository is :
<localRepository>/Users/hilion/Public/repo</localRepository>` 

 Specifies the location of the settings.xml 
![图片](https://user-images.githubusercontent.com/95706849/146170454-a511f401-6fa9-49d0-b3d8-f30d9ae9535b.png)

version:
version: 1.63.1 (Universal)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 18.5.0

 Thank you for your efforts

**Comment by Eskibear** [comment]
@gigitacoo These two settings are defined by extension "Language Support for Java", (see https://github.com/redhat-developer/vscode-java#supported-vs-code-settings ) which is responsible for importing and compiling Maven project, and providing intellisense.

This Maven extension doesn't honor above two settings (at least for now), please use `maven.settingsFile`, see https://github.com/microsoft/vscode-maven#settings

**Comment by gigitacoo** [comment]
@Eskibear 
Got it, it works for the dependency which has specified version tag, thx.
