### ISSUE TITLE
Setting maven command to "./mvnw" works, but it shows an error on startup

### ISSUE THREAD

**Issue by adrianmoya** [Microsoft/vscode-maven#74]
**Describe the bug**
I have my settings like this, to use the maven wrapper that comes from start.spring.io projects: 
`    "maven.executable.path": "./mvnw",`

This works smoothly, but after upgrading to last release, because of the new validation, I get: 

> Unable to execute Maven commands.
> Error:
> Command failed: "./mvnw" --version
> /bin/sh: 1: ./mvnw: not found
> 

**To Reproduce**
1. Set the maven executable path to "./mvnw"
2. Close and Open vscode.

**Expected behavior**
I know the goal for the plugin is to support maven and not the maven wrapper, but I think it's commonly used, so I would like to see if there is a valid workaround or if maybe the command for validation `"./mvnw" --version` could be run in the project's root. 

Thoughts?

**Comment by Eskibear** [comment]
> see if there is a valid workaround

A valid workaround is to specify the absolute path of mvnw in the settings. 

> if maybe the command for validation "./mvnw" --version could be run in the project's root.

Yes, it makes sense, I'll fix it. But consider the multi-root workspace, how do I determine which root to execute the command under?

**Comment by Eskibear** [comment]
And just as you mentioned in #68 , if you open 2 projects A and B, and specify the maven.executable.path to "./mvnw", how should it know which mvnw to use? 

Or we can force to use mvnw if it is found in project root folder. Do you think it makes sense for all users?

**Comment by Eskibear** [comment]
fixed in [0.9.2](https://github.com/Microsoft/vscode-maven/releases/tag/v0.9.2)

**Comment by adrianmoya** [comment]
Hey great! The whole idea behind the maven wrapper (mvnw) is that each project use it's own self-contained maven distribution, so that the build is consistent. So it could make sense to force the use od mvnw if it's present, but I think #68 could also solve the problem, more community input on the topic would be nice. 
Anyway I tested the fix and it works, so I'm closing this one. Thanks!
