### ISSUE TITLE
Configure maven profiles

### ISSUE THREAD

**Issue by alexiswaldo13** [microsoft/vscode-maven#744]
I need to use multiple specific profiles at the same time when running Maven in my project, the profiles are:

- adobe-public
- autoInstallPackage
- coverage

These profiles are configured in the `pom.xml` file, but i have not found a way to tell VSC to use them.

I tried setting them this way: `"maven.executable.options": "autoInstallPackage, adobe-public, coverage"` in the `settings.json` but it does not work

For example, using **IntelliJ IDE** profiles can be selected, but not in **VSC** _(I could just work in IntelliJ, but I don't like that IDE, that's why I want to use it in VSC_).

**_IntelliJ IDE:_**
![image](https://user-images.githubusercontent.com/75273217/134825439-f10e74d5-eb76-4f4d-ba30-51feb975820d.png)

**_VSC IDE:_** **(THERE ARE NO PROFILES)**
![image](https://user-images.githubusercontent.com/75273217/134825466-39964c86-5d0c-4d8b-9de3-fe4ea0c4504c.png)

**Comment by mannixsuo** [comment]
see this [Introduction to Build Profiles](http://maven.apache.org/guides/introduction/introduction-to-profiles.html)
use `mvn groupId:artifactId:goal -P profile-1,profile-2,?profile-3` (profile-1,profile-2,profile-3 are ids of profile to use) may help.

**Comment by giosooul** [comment]
is there any gui solution in the pipeline?

**Comment by baijunjs** [comment]
+1

**Comment by Eskibear** [comment]
Checkbox in tree item is in proposed state. See https://github.com/microsoft/vscode/issues/116141

**Comment by hujghc** [comment]
+1
