### ISSUE TITLE
maven.settingsFile is not work

### ISSUE THREAD

**Issue by owen6846** [microsoft/vscode-maven#758]
I want to use my local setting.xml.
I set "java.configuration.maven.userSettings": "D:\\apache-maven-3.6.3\\conf\\setting.xml", and maven.settingsFile : "D:\\apache-maven-3.6.3\\conf\\setting.xml".
But I update pom.xml, maven always download in C:\\\User\\users\\.m2\\repository.

Can help me how to set setting.xml in vscode .

![image](https://user-images.githubusercontent.com/41528436/140439824-26747ee7-2881-41f0-a192-5e85894e9720.png)

**Comment by Eskibear** [comment]
[vscode-java extension](https://github.com/redhat-developer/vscode-java) is reponsible for downloading dependencies and compiling your projects. And according to the spec, setting `java.configuration.maven.userSettings` is enough.

It works well on my machine. And in my user setting I added below line:
```
  <localRepository>D:/.m2/repository</localRepository>
```

After reloading window, it started to download libs into my custom folder:

![image](https://user-images.githubusercontent.com/2351748/140450643-b29b3d00-6422-4ed4-b3c0-0ace033c1d4f.png)



Can you provide content of your `settings.xml`?

**Comment by owen6846** [comment]
> [vscode-java extension](https://github.com/redhat-developer/vscode-java) is reponsible for downloading dependencies and compiling your projects. And according to the spec, setting `java.configuration.maven.userSettings` is enough.
> 
> It works well on my machine. And in my user setting I added below line:
> 
> ```
>   <localRepository>D:/.m2/repository</localRepository>
> ```
> 
> After reloading window, it started to download libs into my custom folder:
> 
> ![image](https://user-images.githubusercontent.com/2351748/140450643-b29b3d00-6422-4ed4-b3c0-0ace033c1d4f.png)
> 
> Can you provide content of your `settings.xml`?

This is my setting.xml

![image](https://user-images.githubusercontent.com/41528436/140458516-8e3d88dc-1dc0-4be4-ad38-25a4f562140e.png)

When I always update pom.xml or open vscode my project, maven always downlond in C:\User\users\.m2\repository

I try only set  `java.configuration.maven.userSettings`, but it's not work.

![image](https://user-images.githubusercontent.com/41528436/140458686-98237111-a094-4b56-8105-8e0541607dbf.png)

![image](https://user-images.githubusercontent.com/41528436/140458701-def2ca66-f3b9-42bd-999d-813bf048e4d2.png)

**Comment by Seamk** [comment]
i have the same problem,but  now my vscode is ok.
i remove the "java.configuration.maven.userSettings","maven.settingsFile","maven.executable.path" then only write the "java.configuration.maven.userSettings". restart the vscode.

**Comment by Eskibear** [comment]
> then only write the "java.configuration.maven.userSettings". restart the vscode.

It makes sense. The other settings are dedicated to run maven commands through "Maven" explorer.

**Comment by Eskibear** [comment]
v0.35.0 is released. I'm closing this issue.
