### ISSUE TITLE
feature request: "maven" view in Explorer when using VS Code Remote Development

### ISSUE THREAD

**Issue by christophbrejla** [microsoft/vscode-maven#759]
Hello, 

when i am using VS Code locally with the maven extension has a view that can be shown in the VS Code "explorer" where you can for example trigger lifecycle commands. 

when i use VS Code with Remote Development and attach a VS Code Window to a Docker Container or SSH target, i can install the "maven" extension on the remote target, but it is not possible to open the maven view in the "explorer".

is it possible for you to implement this?

or do i just need to change some settings?

thank you

**Comment by Eskibear** [comment]
I cannot reproduce it. Was that because a non-Maven project was opened?

Please make sure that
- Maven extension is installed on Remote.
- A Maven project is opened.

Let me know if you can find a way to reproduce it.
