### ISSUE TITLE
maven Background process terminated with code 1.

### ISSUE THREAD

**Issue by lgpzll** [microsoft/vscode-maven#760]
**Describe the bug**
When i use maven dependencies , show Background process terminated with code 1.
but no log detail , what happen ?

**Environments (please complete the following information as much as possible):**
 - OS: OS X
 - VS Code version: 1.62.2
 - Extension version Maven for Java v0.34.1

**Screenshots**
![image](https://user-images.githubusercontent.com/3469120/141940366-0b07721e-c5eb-42c9-b859-ffa37e642dd9.png)

**Comment by Eskibear** [comment]
Detailed log can be found in  **Output** -> **Maven for Java**.

**Comment by hong8713** [comment]
> Detailed log can be found in **Output** -> **Maven for Java**.

干得漂亮
