### ISSUE TITLE
Maven dependency search command not working

### ISSUE THREAD

**Issue by Jimmya14** [microsoft/vscode-maven#766]
**Describe the bug**
the maven search command for dependencies is not working

**To Reproduce**
1. Use the add dependency command
2. search for any dependency
3. the bar would do the loading animation for a split second then stop

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: v1.63.2
 - Extension version: v0.34.1

**Screenshots**
in window log whenever I try to search for a dependency:
![image](https://user-images.githubusercontent.com/61597538/146914604-17a04672-16d8-45c7-bb39-8c6f72565fd3.png)

**Comment by Eskibear** [comment]
I can reproduce it.

**Comment by Eskibear** [comment]
When sending request to `https://search.maven.org/solrsearch/select?q=azure&rows=50&wt=json`, the response was 

```
```

**Comment by Eskibear** [comment]
Looks like something was changed to maven search API. If no User-Agent specified when sending a request using NodeJS `https` lib, the service returns 403. 

A possible solution is to specify a user agent.
