### ISSUE TITLE
Create Maven Project does not work.

### ISSUE THREAD

**Issue by Kambaa** [microsoft/vscode-maven#771]
**Describe the bug**
Maven options for custom "settings.xml" file does not work when trying to create a new maven project.

**To Reproduce**
1. Go to 'Any workspace'
2. Click on 'Right clicking on the selected folder and selecting Create maven project'
3. Doing the steps to 'create to create a new maven archtype project'
4. See the problem as the image error, in the command line section no particular options are added to the running command.
![resim](https://user-images.githubusercontent.com/5601326/147887160-008be71b-2026-4d1e-93f4-5500564561d5.png)

**Expected behavior**
running maven(as well as java) commands from command list (opened with ctrl+shift+p) should have extra arguments described in the Options.json file(or stuff set up in the extension settings). meaning take a look at vscode's terminal window's last lines: 
![resim](https://user-images.githubusercontent.com/5601326/147887660-12209f50-8525-493f-9b07-61229d1fced3.png)
where is the -gs <settings.xml path> or other given parameters set up in the setting.json?? 

**Environments:**
 - OS: Windows 10
 - VS Code version: Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
 - Extension version 11.430.106 (installed with Java extension pack 10.802.438)

**Screenshots**
See the 4th step in To reproduce. 

**Additional context**
In the screenshot, Because of the default "work" settings of maven, i needed to change the settings.json file to default settings.xml by settings up the vscode settings as seen in the upper "Settings.json" tab. I tried various things, using *maven.settingsFile* , *maven.executable.options* but no avail. Please don't mind the duplicate lines of the same configuration as i am cleaning it up right now. 
I am trying to test if i can swicth to vscode and test out if a java dev enviroment can set up quickly, so far, scaaaary 😨

**Comment by Eskibear** [comment]
About `maven.settingsFile` part, #768 would probably fix the issue.

**Comment by Kambaa** [comment]
Hello again, 
After leaving the issue as is, and clearing my head for some time, i returned and tried it again, it seems **_maven.settingsFile_** option does not work for plugin. So for now, i have to manually change settings.xml file myself. 

![resim](https://user-images.githubusercontent.com/5601326/149991124-f83147c1-359d-4589-8f06-5ba71e60a7c2.png)



Also, trying to add the argument on the maven.executable.path setting breaks the command somehow. So after trying and trying, i did made it work somehow but, as you can see in the image below, running command opens in a new command line (it was hard to pause fast closing terminal and take a screenshot! :) )
![resim](https://user-images.githubusercontent.com/5601326/149991786-b1cb9542-dc7b-442b-bc54-3480969ccbe6.png)
I will be looking forward to the fix and make myself a nice, portable, java vscode enviroment.

Thank you for your patience and have a wonderful year.

**Comment by Eskibear** [comment]
https://github.com/microsoft/vscode-maven/pull/776 does fix the settings file issue, appending `-s <mavenSettingsFile>` to the command. You'll see it in the next version.


> running command opens in a new command line

This is windows/powershell's behavior when you specify full path of mvn without providing its file extension `.cmd`. Specifying `mvn.cmd` instead of `mvn` would probably work. See below:

```
PS C:\Users\username> & "C:\apache-maven-3.8.1\bin\mvn" --help
PS C:\Users\username> & "C:\apache-maven-3.8.1\bin\mvn.cmd" --help

usage: mvn [options] [<goal(s)>] [<phase(s)>]

Options:
 -am,--also-make                        If project list is specified, also
...
```

**Comment by Kambaa** [comment]
Thank you for your time. Have a nice day.
