### ISSUE TITLE
Cannot debug JavaFX project

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-maven#773]
**Describe the bug**
Cannot debug JavaFX project via Maven goal.

**To Reproduce**
1. Download the sample project and open in VS Code 
[hellofx.zip](https://github.com/microsoft/vscode-maven/files/7805699/hellofx.zip)
2. After project is imported, debug the maven goal `javafx:run`

**Environments (please complete the following information as much as possible):**
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
Extension version: 0.34.2

**Screenshots**
![image](https://user-images.githubusercontent.com/6193897/148018074-2c8f211b-2e91-4402-af14-00102ede4495.png)

**Comment by Eskibear** [comment]
Probably same with #757 

I'm curious that, with command line, how do you debug your javafx project? `mvnDebug`?
