### ISSUE TITLE
Problema-creazione

### ISSUE THREAD

**Issue by Pietro-GitHub** [microsoft/vscode-maven#779]
[Problema-creazione.txt](https://github.com/microsoft/vscode-maven/files/7850354/Problema-creazione.txt)
I dati necessari sono stati scritti negli appunti perché erano eccessivi per l'invio. Incollarli.

**Comment by Eskibear** [comment]
> Error: JAVA_HOME is set to an invalid directory.
Please set the JAVA_HOME variable in your environment to match the 
location of your Java installation.

Maven requires you to have a correct JAVA_HOME environment variable.

**Comment by Eskibear** [comment]
Let me know if that work after you set JAVA_HOME

**Comment by Pietro-GitHub** [comment]
Yes, I managed to solve it, thanks.

Il ven 21 gen 2022, 07:08 Yan Zhang ***@***.***> ha scritto:
