### ISSUE TITLE
How can like eclipse or idea of this

### ISSUE THREAD

**Issue by nightmare-mio** [microsoft/vscode-maven#783]
# idea
![2](https://user-images.githubusercontent.com/52735303/149909819-4576e8bf-5597-4089-851f-7c94d6c171ed.png)
# vscode
![1](https://user-images.githubusercontent.com/52735303/149910032-d79918f5-d57f-4f15-9e13-3e0035324d14.jpg)
# 我看不到jar包具体的源码，请问怎么设置或者解决。

**Comment by Eskibear** [comment]
You can find related information in "Java Projects" explorer. See https://github.com/microsoft/vscode-java-dependency
