### ISSUE TITLE
Add setting to allow setting JDK path manually

### ISSUE THREAD

**Issue by robertyoung-vungle** [microsoft/vscode-maven#786]
For developers working on multiple projects, being able to over ride the JDK used by mvn would be incredibly helpful. A setting such as `maven.excludedFolders` would save much time changing system/vscode variables and seeing if this extension picks up the change. Additionally, having some way to inspect the current settings would also be quite helpful.

**Comment by Eskibear** [comment]
See https://github.com/microsoft/vscode-maven#settings

You can use `maven.terminal.customEnv` to override system envs. Let me know if that works for you.
