### ISSUE TITLE
Feature request : Add scala support

### ISSUE THREAD

**Issue by DachuanZhao** [microsoft/vscode-maven#789]

**Comment by Eskibear** [comment]
Can you provide more specific information?

**Comment by DachuanZhao** [comment]
> Can you provide more specific information?

Like this [tutorial](https://docs.microsoft.com/en-us/azure/hdinsight/spark/apache-spark-create-standalone-application) .

Can we use maven for both java and scala in vscode ?

**Comment by Eskibear** [comment]
> From the list of archetypes, select org.scala-tools.archetypes:scala-archetype-simple. This archetype creates the right directory structure and downloads the required default dependencies to write Scala program.

Despite of the name, this extension is language neutral. You can run `Create Maven Project` to scaffold your project from the scala archetype mentioned above.

For other scala-related features, you can explore vscode marketplace, see if there's any "scala extension".
