### ISSUE TITLE
Support the setting of 'maven.executable.path' in vscode workspace folder settings 

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-maven#79]
**Describe the bug**
Open a multi-root workspace with multiple maven projects, I want one of the projects to use its own mvnw file and others use the environment maven path. But when I search  using 'maven' keyword in specified folder settings, there are only two maven settings and I can't find 'maven.executable.path' 

**To Reproduce**
1. Open a muitl-root worksapce
2. Open folder settings to choose a project and search maven related settings

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10/OS X
 - VS Code version: 1.25.1
 - Extension version 0.9.2

**Screenshots**
![image](https://user-images.githubusercontent.com/22470312/42683144-07c1b1b4-86bf-11e8-8cf6-72258cb74c99.png)

**Comment by Eskibear** [comment]
fixed in #88
