### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by princes91221** [microsoft/vscode-maven#792]
Issue Type: <b>Bug</b>

While retrieving the data from, I'm getting an error stating "Extension host terminated unexpectedly" and it is asking to `restart the extension host` or `open developer tool`.

Extension version: 0.35.0
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.78GB (1.47GB free)|
|Process Argv|--crash-reporter-id 2d74d41c-18ae-4bca-a916-76c85d5bfff5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30436984
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710:30416614
vscop841:30437297
pythonvspyt640:30436486
vsbas813:30436447
vscscmwlcmt:30436993

```

</details>

**Comment by Eskibear** [comment]
Can you provide more details about the error? Or try disabling all other extension, see if it's caused by `Maven for Java` extension?
