### ISSUE TITLE
Lifecycle phase list incomplete and not customizable

### ISSUE THREAD

**Issue by matter-it-does** [microsoft/vscode-maven#793]
**Describe the bug**
Lifecycle section in maven panel is incomplete. I want to run "test-compile" phase but that is not present in the list. https://maven.apache.org/plugins/maven-compiler-plugin/usage.html That helps me check the compile-ability status in one click.

https://github.com/microsoft/vscode-maven/blob/main/src/explorer/model/LifecycleMenu.ts#L17

**To Reproduce**
See the  screenshot in #601 
![image](https://user-images.githubusercontent.com/76812421/154625444-87a7fcdd-1944-4037-9c9f-6b2ac45ad6f6.png)

**Expected behavior**
Customizable lifecycle phase list or just full list.

**Environments (please complete the following information as much as possible):**

 - Extension version v0.35.0

**Comment by Eskibear** [comment]
> Customizable lifecycle or just full list.

As you see, lifecycles are not hard-coded, and only include most common ones. Now it's impossible to customize the items shown in the tree view (they are static defined in manifest file). But we can definitely consider to hard-code more items (if that's also commonly used). Do you know where we can get the full list?

Workaround:
`mvn test-compile` is equivalent to executing plugin goal `compiler:testCompile`. See https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#packaging

So you can do that from plugins menu as below:
![image](https://user-images.githubusercontent.com/2351748/154632965-b286504f-6a4a-4b14-9446-42e0b3ca6b3c.png)

**Comment by matter-it-does** [comment]
> > Customizable lifecycle or just full list.
> 
> As you see, lifecycles are not hard-coded, and only include most common ones. Now it's impossible to customize the items shown in the tree view (they are static defined in manifest file). But we can definitely consider to hard-code more items (if that's also commonly used). Do you know where we can get the full list?

I'm guessing this one  https://maven.apache.org/ref/3.8.4/maven-core/lifecycles.html

Or on the link you shared https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#lifecycle-reference

> Workaround: `mvn test-compile` is equivalent to executing plugin goal `compiler:testCompile`. See https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#packaging

Umm I don't see that in my project.. I'm not very experienced in java build phases so grain of salt would be handy.

Running `compiler:testCompile` from the plugin dropdown only compiles some 10 test files.
Running `mvn test-compile` compiles 40 source files and 10 test files.

> To compile your test sources, you'll do:
> 
>     mvn test-compile
> 
> The above command will execute both compiler:compile and compiler:testCompile since the compile phase happens a few phases before the test-compile phase.
>

**Comment by Eskibear** [comment]
> I'm guessing this one https://maven.apache.org/ref/3.8.4/maven-core/lifecycles.html

23 default lifecycle in total, and that's too many. That would make the context menu too long, which is not a good experience. Maybe we can add 'test-compile' first if that's more frequently used. 

For the moment, if you do want to run `test-compile` from the context menu, you can use below entries:

![image](https://user-images.githubusercontent.com/2351748/154647830-f9a70114-ccde-427f-a5a5-ec5b59bb6397.png)

- Custom... : input 'test-compile' by your own.
- History... : Once you run your custom command, it's convenient to re-run from here without inputing again
- Favorite... : add 'test-compile' into settings `maven.terminal.favorites`, see https://github.com/microsoft/vscode-maven#settings

**Comment by matter-it-does** [comment]
Oh didn't know about custom command thanks

95k views .. sounds commonly used to me (;  https://stackoverflow.com/questions/4768660/maven-how-to-compile-tests-without-running-them
