### ISSUE TITLE
Should provide ways to distinguish projects with same name

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-maven#794]
When opening a folder containing multiple projects, with the same name, it's difficult to distinguish them.

e.g. 
rootFolder/a1/b/parent/pom.xml
rootFolder/a2/b/parent/pom.xml
rootFolder/a3/b/parent/pom.xml

All above have the same `name` called "parent project` (but with different artifactId maybe). The corresponding project items have the same label.

Possible solution I can think for now:
- append the full path (or the different parts) if there's projects with same name. 
- append groupId and artifactId

Or we can explore if we can provide hover information.

**Comment by Eskibear** [comment]
mitigated by #799 for the moment

**Comment by janitza-towe** [comment]
Hello.
We are pretty much interested in this feature and would also like to see the possibility to display the current version of a module inside the project tree. This is especially useful for when working with SNAPSHOTs and to distinguish whether the module is closed/opened.

Comming from Netbeans IDE, we were able to setup the appearance of shown projects in a custom way which is pretty useful. Maybe this feature will find it's way into vscode some day too :)

Thanks!

![image](https://user-images.githubusercontent.com/39914028/177771896-ab0e89c4-70c0-41f4-8b2b-010b3ae7554d.png)

**Comment by Eskibear** [comment]
BTW, in VS Code, project node name consists two part, i.e. `label` and `description` (less prominent text on the right). 

Currently we put `${project.name}` in `label`, and `${project.groupId}:${project.artifactId}` in `description`. I'm wondering whether we allow to customize both fields and how to design the setting. Maybe simply adding `${project.version}` into `description` would mitigate your case.

**Comment by Eskibear** [comment]
@janitza-towe

I created a PR adding the corresponding setting, see demo here: https://github.com/microsoft/vscode-maven/pull/834#issuecomment-1180019790

**Comment by Eskibear** [comment]
closed in favor of #834
