### ISSUE TITLE
Could not load main pom file content, see example:

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode-maven#795]
Issue Type: <b>Bug</b>

Could not load main pom file content, see example:

https://user-images.githubusercontent.com/54253524/154777668-da56c6ff-9fb8-42ff-be63-e871ca73ab42.mp4

Extension version: 0.35.0
VS Code version: Code - Insiders 1.65.0-insider (1d618b2df1cf08f0e3ab706353f0a8f6f1424795, 2022-02-18T05:17:35.717Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

**Comment by Eskibear** [comment]
Can you share the main `pom.xml` ?

**Comment by zhouxinghong** [comment]
> 

XML
v0.19.1
Red Hat
Language Support for Java(TM) by Red Hat
v1.3.0
Red Hat
This problem has been around for a very long time, but it has not been resolved until around 2019. . .

**Comment by Eskibear** [comment]
Outline should be provided by XML extension. I find this issue is already tracked in vscode-java repo. I'm closing this one.

**Comment by zhouxinghong** [comment]
ok
