### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by yntelectual** [microsoft/vscode-maven#802]
## Suggestion

Hi, it would be great if VS code maven integration could automatically discover and add generated sources from target folder.

## Use Cases

Many code gen plugins generate additional sources to target folder - e.g. Openapi codegen, GRPC plugins.. and many java IDEs will automatically pick them up and add to classpath. In VS Code, we have to explicitly add them to classpath via build-helper-maven-plugin which is cumbersome, and breaks interop with colleagues using other IDEs 

## Examples

Generating HTTP clients/stubs from openapi using openapi maven plugin
![image](https://user-images.githubusercontent.com/1354787/156755129-909f5c43-df26-4306-a85c-1c45b5d66b66.png)

**Comment by Eskibear** [comment]
Can you describe the detailed steps to get your project working in both VS Code and other IDE? Then we can find where to improve overall user experience, and what's the gap.
