### ISSUE TITLE
Show mvn log from m2e

### ISSUE THREAD

**Issue by karlvr** [microsoft/vscode-maven#803]
## Suggestion

My "Maven for Java" output channel only ever has "local repository: /" in it. I would like to see the log of Maven running, like I can see in Eclipse.

## Use Cases

Things sometimes break or take a long time in our Maven build and viewing the log often helps to diagnose what is happening.

**Comment by Eskibear** [comment]
"Maven for Java" is not responsible for importing projects via m2e. vscode-java extension starts a Java language server, which uses m2e to do the stuffs you mentioned. Please open issue to https://github.com/redhat-developer/vscode-java/
