### ISSUE TITLE
vscode-maven seems to ignore settings.xml

### ISSUE THREAD

**Issue by perereman** [microsoft/vscode-maven#806]
Hello everybody

I have and extrange behavior in VSCode with "Maven for Java" extension:

- If I compile my maven project from Windows 10 cmd terminal or VSCode embedded terminal ("mvn clean" and "mvn package"), maven **works fine**
- If I compile my maven project from VSCode with "right click" over Maven Extension over my project, and then "left click" over "clean" and "left click" over "package" it **works fine** 
- However, all the time my IDE shows a red alert over my project pom.xml. If I open the pom.xml, I can see a red underline over <parent> tag showing the following message:

> Project build error: Non-resolvable parent POM for my.package:my-proyect:0.0.1-SNAPSHOT: org.springframework.boot:spring-boot-starter-parent:pom:2.3.8.RELEASE failed to transfer from https://repo.maven.apache.org/maven2 during a previous attempt. As a subsidiary problem, my project doesn't show up in "Spring Boot Dashboard"

Ok, we have a proxy at the organization so, up to now, behavior seems common. **The point is**: in my organization, we work with a local maven repository. We don't use repo.maven.apache.org but a local URI. In fact, when I run "mvn clean; mvn package" from Windows 10 cmd I can see messages like "Downloading dependency from 10.0.0.200" so my settings.xml file should be working properly.

However, for some reason, "Maven for Java" plugin seems to be trying to resolve dependencys from "https://repo.maven.apache.org/maven2".

My developping enviroment is:
 - Windows 10
 - I have my local copy of maven executable (v3.8.5) at the following path: C:\ENTORNO2022.00\01.SOFTWARE\03.HERRAMIENTAS\apache-maven-3.8.5
 - Settings.xml file is at C:\ENTORNO2022.00\01.SOFTWARE\03.HERRAMIENTAS\apache-maven-3.8.5\conf\settings.xml
 - VisualStudioCode version 1.65.2
 - Maven for Java v0.35.1

Settings.json from my VSCode is 

> {
>     "java.configuration.maven.globalSettings": "C:\\ENTORNO2022.00\\01.SOFTWARE\\03.HERRAMIENTAS\\apache-maven-3.8.5\\conf\\settings.xml",
>     "java.configuration.maven.userSettings": "C:\\ENTORNO2022.00\\01.SOFTWARE\\03.HERRAMIENTAS\\apache-maven-3.8.5\\conf\\settings.xml",
>     "maven.settingsFile": "C:\\ENTORNO2022.00\\01.SOFTWARE\\03.HERRAMIENTAS\\apache-maven-3.8.5\\conf\\settings.xml",
>     "maven.executable.path": "mvn",
>     "maven.executable.preferMavenWrapper": false,
>     "maven.terminal.useJavaHome": true,
>     "workbench.startupEditor": "none",
>     "redhat.telemetry.enabled": true,
> }

Could any one provide some help. I don't know what to. Thank you very much

**Comment by Eskibear** [comment]
> all the time my IDE shows a red alert over my project pom.xml.

That's provided by [Java Extension](https://github.com/redhat-developer/vscode-java), which is imports and compile your project via m2e. Looks like it ignores the proxy for some reason.  **I suggest that you create an issue there, providing [correponding log](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging) if there's any.** 

These settings look good to me. BTW, Java extension reads those settings starting with "java" and this Maven extension reads those staring with "maven".

> As a subsidiary problem, my project doesn't show up in "Spring Boot Dashboard"

That's because "Spring Boot Dashboard" depends on "Java Extension" to get proper project information.

**Comment by perereman** [comment]
Thank you Eskibiar. I will go to vscode-java github repository looking for further help.

Regards

**Comment by perereman** [comment]
Ok, I got it fixed.

The problem was in my settings.json. I was trying to use a Windows 10 enviroment variable y differents routes. The point is:

Configuration variables for "Maven for VSCode" accept those variables with a format like $env:VARIABLE_NAME
Configuration variables por VScode-jave doesn't accept neither the format $env:VARIABLE_NAME nor %VARIABLE_NAME%.
So "Maven for VSCode" was reading properly the maven config file (settings.xml) however VSCode-java wasn't. That's why VSCode-java was pointing to Maven Central instead of our local Maven Repository, throwing many and many erros about private packages thay are not available at Maven Central.

Regards
