### ISSUE TITLE
Locally installed archetypes not detected

### ISSUE THREAD

**Issue by paroxayte** [Microsoft/vscode-maven#82]
Installing an archetype and updating the local-catalog to contain said archetype does not cause it to appear in the list of available archetypes from the Maven: Generate from Maven Archetype command. I have verified that my archetype is correctly installed by cat'ng the local-catalog as well as generating a project using the archetype from the command line. 

OS: Debian Stretch

**Comment by Eskibear** [comment]
@paroxayte Could you share the way you are using local-catalog? So we can think about how to improve the experience?

**Comment by Eskibear** [comment]
Forgot to say, yes, currently it only fetches the catalog from maven central repo, and caches it locally. The drop list of maven archetypes is loaded from the cached catelog. So we want to know how you install your archetype, and how to get the list of archetypes installed to local-catalog, and how you use command line to generate projects from that archetype. It would help a lot. Thanks.

**Comment by paroxayte** [comment]
@Eskibear Yes, certainly! When installing an archetype from source I run 

    mvn install archetype:update-local-catalog
    mvn archetype:crawl
You can similarly do this with install:install-file and a local archetype jar.
Doing this causes ~/.m2/repository/archetype-catalog.xml to either be created or updated to contain identifcation data for your archetype. For my archetype in this case the generated entry is:

    <archetype>
      <groupId>paroxayte</groupId>
      <artifactId>cs2Template</artifactId>
      <version>1.1</version>
      <description>cs2Template</description>
    </archetype>

Then to generate a project from the now installed archetype I cd into my workspace directory and run 
`mvn archetype:generate -B -DarchetypeGroupId=paroxayte -DarchetypeArtifactId=cs2Template -DgroupId=paroxayte -DartifactId=test -Dversion=1.0` or you can do it interactively by witholding the '-B' flag and just supplying the archetypeGroupId and archetypeArtifactId. The archetype-catalog-.xml file is very simple with the only attributes I've encountered being groupId, artifactId, archetypeId, version, and opening/closing attributes.

**Comment by Eskibear** [comment]
Yes, by executing `mvn install archetype:update-local-catalog` I find `~/.m2/repository/archetype-catalog.xml` created. But `install:install-file` doesn't work for me. 

## Plan
1. read archetypes from `~/.m2/repository/archetype-catalog.xml` if it exists.
1. show archetypes in local-catalog together with the recommended archetypes in the 1st page. 

Do you think this works for you and other local-catalog users ?

**Comment by paroxayte** [comment]
Yes, I believe this plan would cover most/all local-catalog users. Note that `mvn install:install-file` is for installing a local jar, not from local source.  If you were to install from a local jar you also have to point at the archetype pom when you update the catalog. Eg: `mvn -f cs2Template.pom archetype:update-local-catalog`

**Comment by Eskibear** [comment]
Fixed in PR #86 . Will be shipped with v1.0.0. You can checkout the latest code if you want to try it now.
