### ISSUE TITLE
Add reloading project supporting in Maven explorer

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-maven#837]
## Suggestion
- A `Reload All Maven Projects` button in the navigation bar
- A `Reload Project` button in each project node's context menu

**Comment by Eskibear** [comment]
Are you talking about adding reloading projects functionality provided by Java extension, but the entry is to be added in the "Maven" explorer? It sounds a little bit strange here, and we do have cases that Maven extension is installed independently.

**Comment by jdneo** [comment]
> Are you talking about adding reloading projects functionality provided by Java extension, but the entry is to be added in the "Maven" explorer?

Yes. BTW I'm not worrying about this behavior since it can be found in other popular IDE as well.
![image](https://user-images.githubusercontent.com/6193897/178929652-7f58d79b-081c-48ce-a12d-fbe83f29445f.png)

> and we do have cases that Maven extension is installed independently.

A when clause can be used to guard this case - `javaLSReady`

**Comment by jdneo** [comment]
They are implementation details. Usually, users do not know the difference behind the scenes. A user comes from IDEA would try to find it there according to the experience he has learnt in IDEA.

**Comment by jdneo** [comment]
I just realized that you might be talking about that in IDEA, the `reload` action contains both `import all` & `reload all`, while here we only have `reload all` and `import all` is missing. Is that the thing you are worrying about?

**Comment by Eskibear** [comment]
looks like it's already done.
