### ISSUE TITLE
add new project as module of existing project

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-maven#849]
We can provide an extra entry for this feature, "Add a module" from a project node.

E.g. Similar as mentioned in this doc: https://www.codejava.net/ides/intellij/create-multi-module-maven-project-intellij

**Comment by dev-techmoe** [comment]
Any updates on this?

Despite manually creating a sub-module using “create maven project” to my project root and adding some maven configuration to pom.xml, I still need to reload the entire VSCode workspace (Developer: reload window) to ensure that all Java plugins recognize my new sub-module.

**Comment by Jf710001011** [comment]
> This is a must have feature for heavy maven user
Please tell me what should I do specifically?

**Comment by testforstephen** [comment]
You can now create a new module in existing projects with the context menu “**Maven -> New Module…**”. To see how it works, check out the demo on #1018.

Please try out the pre-release version v0.43.2024011905 and let us know your feedback.
