### ISSUE TITLE
Consider updating depgraph-maven-plugin to version 3.3.2

### ISSUE THREAD

**Issue by ferstl** [microsoft/vscode-maven#852]
**Describe the bug**
Hi,
I am the developer of the [depgraph-maven-plugin](https://github.com/ferstl/depgraph-maven-plugin) which you are apparently using in the maven extension of VS Code. Two people reported an [error](https://github.com/ferstl/depgraph-maven-plugin/issues/159) where a `ConcurrentModificationException` occurred when using the plugin. I released version 3.3.2 of the plugin which fixes this issue. Please consider updating the plugin to this version. I can also create a fix for the 4.0.x line of the plugin if needed. If not, the fix will also be available in version 4.1.0 which is not yet released.
Please also note that I am totally unfamiliar with VS Code and its Maven extension. But if you encounter any problems with the depgraph-maven-plugin, feel free to contact me or file a bug report at https://github.com/ferstl/depgraph-maven-plugin/issues .

Cheers,
Stefan

**To Reproduce**
n/a

**Expected behavior**
n/a

**Environments (please complete the following information as much as possible):**
n/a

**Screenshots**
n/a

**Additional context**
n/a

**Comment by Eskibear** [comment]
Thank you for the information. I'll update it to v3.3.2. 

I'll consider to update to 4.0.x later after some investigation and verification. BTW for 4.0.x, is there any other major changes other than requiring JDK 8 instead of 7?

**Comment by ferstl** [comment]
The 4.0.x version has not many changes in the code that was already there. You can find a complete List here: https://github.com/ferstl/depgraph-maven-plugin/releases/tag/depgraph-maven-plugin-4.0.0 .
Since you are planning to switch to 4.0.x I‘ll fix the problem there as well. The fixed version will most likely be 4.0.2 .

**Comment by Eskibear** [comment]
Cool. The improvements look good, especially the "download pom only" one. I'll switch to 4.0.2 when it's ready.

**Comment by ferstl** [comment]
Version 4.0.2 is released and available on Maven Central
