### ISSUE TITLE
Fail to calculate Effective POM

### ISSUE THREAD

**Issue by v-yuyul** [microsoft/vscode-maven#866]
**To Reproduce**
1. Open the project: https://github.com/junit-team/junit5-samples/tree/master/junit5-migration-maven
2. Open a .java file. In body of a function, type below statements.
   ```
   StringUtils.capitalize("abc");
   ```
3. When hovering on the classname, "Resolve unknown type" action is shown. Clicking "Resolve unknown type" to solve the error
4. Pops up the error (I can't always reproduce this issue and only see it one time)

**Expected behavior**
No error

**Environments (please complete the following information as much as possible):**
 - OS: Mac intel Monterey
 - VS Code version: v1.70.2
 - Extension version: v0.38.0

**Screenshots**
![image](https://user-images.githubusercontent.com/31497677/187649951-2ffff20b-6998-4e60-a3f5-666f87d1e099.png)

**Additional context**
log file - 
[maven for java.txt](https://github.com/microsoft/vscode-maven/files/9460428/maven.for.java.txt)

**Comment by Eskibear** [comment]
Failed to reproduce it. And the attached logs are also good.
