### ISSUE TITLE
Wrongly prepend /mnt to pom path

### ISSUE THREAD

**Issue by grimly** [microsoft/vscode-maven#874]
**Describe the bug**
When git for windows is installed with a custom path, the transformation of the pom path to wsl is attempted.

**To Reproduce**
1. Install git for windows in a path not including `Git` and set it as default shell
2. Run any goal from a maven project
3. See maven complain about a path (starting with `/mnt`) not existing

**Expected behavior**
If detection is not possible, allow a setting to disable WSL path transformation

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: 1.71.0
 - Extension version: 0.38.0

**Screenshots**

**Additional context**
I have no control over the path to the shell and wsl is not enabled (organization ruling)

**Comment by Eskibear** [comment]
https://github.com/microsoft/vscode-maven/blob/0a01aea7548b32feafb96c4383f68c3fdc1b7553/src/mavenTerminal.ts#L145-L152

**Comment by Eskibear** [comment]
I'll follow vscode's impl to fix this issue.

https://github.com/microsoft/vscode/blob/1755a21efc89bcb5ccef3fd908372bf7c8944d3c/src/vs/platform/terminal/node/windowsShellHelper.ts#L144-L164
