### ISSUE TITLE
Adding new maven projects to an existing parent project's POM

### ISSUE THREAD

**Issue by ENate** [microsoft/vscode-maven#876]
Adding a new maven project to an existing multi-module maven project disrupts the parent POM file (by introducing blank lines between each line of code in the parent POM). When this happens, we will need to reformat the parent POM.

**Comment by Eskibear** [comment]
Can you provide a sample project to reproduce the issue?

BTW, the job to create a project is delegated to Maven itself. This extension just assembles the command `mvn archetype:generate .....`, thus the behavior is tied with either the [maven-archetype-plugin](https://maven.apache.org/archetype/maven-archetype-plugin/) or the archetype you are using.

**Comment by ENate** [comment]
Thanks but say I have a parent POM file called POM (say someParent.xml) containing:
```
<modules>
    <module>newJavaMvnProject</module>
</modules>
```
After generating the ``` newJavaMvnProject ```, two blank lines are always added to the parent POM (our  someParent.xml) resulting in:
```
<modules>


    <module>newJavaMvnProject</module>


</modules>
```
OK, maybe the extension is not responsible for this issue.
