### ISSUE TITLE
[Question] How does the dependency resolve(download) process work?

### ISSUE THREAD

**Issue by grisha9** [microsoft/vscode-maven#882]
Hi. Sorry for the question, I would like to know how dependency resolve works for the purpose of self-education.
My understanding is: 
In versions prior to 0.39 you used the dependency:tree plugin first and after com.github.ferstl:depgraph-maven-plugin:3.3.2:graph to get the dependency graph and resolve (load) the dependency.
But since 0.39 version used com.github.ferstl:depgraph-maven-plugin:4.0.2 which only getting dependency graph without downloading dependency.
Unfortunately now I can't figure out who downloads the dependencies. Could you help me explain how dependency loading works now?

**Comment by Eskibear** [comment]
> In versions prior to 0.39 you used the dependency:tree plugin first and after com.github.ferstl:depgraph-maven-plugin:3.3.2:graph to get the dependency graph and resolve (load) the dependency.

In 0.39.0, we only bump `com.github.ferstl:depgraph-maven-plugin` from 3.3.2 to 4.0.2 as below:
https://github.com/microsoft/vscode-maven/compare/v0.38.0...v0.39.0#diff-744d2390e4fa73a462e9326a3d8727ff6fe482352ec49f4e06cb6f2afc53e2caR18-R51

> Unfortunately now I can't figure out who downloads the dependencies. Could you help me explain how dependency loading works now?

We use this plugins only to calculate dependency tree/graph. `dependency:tree` was used long time ago before we introduced `com.github.ferstl:depgraph-maven-plugin`. So basically it's the behavior change of this plugin. I would invite the author @ferstl to answer the question.
BTW, if you have the [Java extension](https://github.com/redhat-developer/vscode-java/) installed, it will also download the dependencies while importing and compiling your projects.

**Comment by grisha9** [comment]
Thanks a lot for the explanation. The question is closed)

**Comment by ferstl** [comment]
Hi @grisha9 
@Eskibear already explained the behavior change pretty well. The intention of the depgraph-maven-plugin is to calculate and present dependency graphs. Downloading the dependencies during the process was kind of an annoying side effect which I managed to eliminate in version 4.0.0 of the plugin.
I am not a vscode user, so I don't know how the Maven integration works there. But from the plain Maven perspective you should use something like "mvn dependency:resolve" to download dependencies. Or if you run a build like "mvn verify" it will download the dependencies automatically.

Cheers,
Stefan

**Comment by Eskibear** [comment]
Thank you, Stefan. I'm closing this question now.
