### ISSUE TITLE
Maven for Java extension not activated even workspace contains pom.xml file

### ISSUE THREAD

**Issue by doggy8088** [microsoft/vscode-maven#885]
**Describe the bug**

I can't see **Maven for Java** extension been activated after project been loaded.

**To Reproduce**
1. Clone my project

    ```sh
    git clone https://github.com/doggy8088/spring-boot-jpa-demo.git
    code spring-boot-jpa-demo
    ```

3. I can't see `MAVEN` extension been activated. I do have a `pom.xml` in the workspace.

    ![image](https://user-images.githubusercontent.com/88981/194379776-90b124f9-999d-40e7-8561-d1f47488f6db.png)

**Expected behavior**

I expected the `MAVEN` extension will be loaded if my workspace contains a `pom.xml` file. I don't know it seems unstable.

https://github.com/microsoft/vscode-maven/blob/2a254ba103708298e8b31172eb89ae4663e72f78/package.json#L39

**Environments (please complete the following information as much as possible):**
 - OS: `Windows 10`
 - VS Code version: `v1.71.2`
 - Extension version `v0.39.0`

**Screenshots**

![image](https://user-images.githubusercontent.com/88981/194380370-44995857-9286-48ef-82f4-a5c732fe9c5b.png)

**Additional context**

I do have a workaround by execute `F1` > `Maven: Add a dependency` command once.

If the `MAVEN` extension has been activated successfully, you can try run `Developer: Reload Window` command. The `MAVEN` extension will not be loaded again after vscode window reloaded.

**Comment by Eskibear** [comment]
It was not activated somehow. Check `Log(Extension Host)` for logs about extension activation.

**Comment by doggy8088** [comment]
Check this out:

![image](https://user-images.githubusercontent.com/88981/195024392-d2f61940-c50e-4532-94db-176ce0f2dadd.png)

**Comment by doggy8088** [comment]
I think it's an upstream issue. I opened a new issue there: https://github.com/microsoft/vscode/issues/163255

**Comment by Eskibear** [comment]
also see: https://github.com/microsoft/vscode-maven/issues/881

**Comment by Eskibear** [comment]
let's track it in #881
