### ISSUE TITLE
The "maven.terminal.useJavaHome" config does not support new config key "java.jdt.ls.java.home" from [Language Support for Java(TM) by Red Hat]

### ISSUE THREAD

**Issue by GitPopcorn** [microsoft/vscode-maven#888]
**Describe the bug**
The extension [Language Support for Java(TM) by Red Hat](redhat.java) has deprecated the config key "java.home" and change it to "java.jdt.ls.java.home", but [Maven for Java](vscjava.vscode-maven) seem to not support the new config key.

**To Reproduce**
1. Add config "java.jdt.ls.java.home", set to a path of JDK diffrent from system default, make sure the config "java.home" does not exist.
2. Set config "maven.terminal.useJavaHome" to "true", set config "maven.executable.options" to "-v" to easily observing.
3. Open any maven terminal to see the version of JDK.

**Expected behavior**
The maven terminal should use the JDK in config path of "java.jdt.ls.java.home".

**Actual behavior**
The maven terminal still use the default JDK.

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: 1.72.1
 - Extension version v0.39.0

**Additional context**
In fact, the config "java.home" still affects, and the config "maven.terminal.customEnv" can be a replacement for this goal. So I am not sure if this is a bug or a feature, just make a report to you.

**Comment by Eskibear** [comment]
`java.home` is deprecated but still effective for compatibility. `maven.terminal.useJavaHome` was invented at the time `java.home` was the only setting to specify a JDK home, just for convenience. It does exactly the same thing as [we describe](https://github.com/microsoft/vscode-maven/blob/97a07a2187009044e8bddc33d8069e87c2d947f2/package.nls.json#L31).

`java.jdt.ls.java.home` is used to launch JDT.LS itself to provide language features, and it's not aimed to run your projects.

I agree that we should probably also deprecate `maven.terminal.useJavaHome`, and you should probably use `maven.terminal.customEnv` to set JAVA_HOME if you want.
