### ISSUE TITLE
How to add the `--add-opens` attribute to the make command?

### ISSUE THREAD

**Issue by VirensCn** [microsoft/vscode-maven#890]
How to add the `--add-opens` attribute to the make command?

My project runs on java17, but some of the libraries need to pass ` -- add open java. base/java Lang=ALL-UNNAMED ` To add support, I did not find the configuration method on vscode maven?

如何为mave命令添加add-opens属性？
我的项目运行在java17上，但是其中部分库需要通过`--add-opens java.base/java.lang=ALL-UNNAMED`添加支持，我并没有在vscode maven上找到如果配置的方式？

**Comment by Eskibear** [comment]
I'm not sure about your use case. Is that you want to append these args to `mvn ....` command line? Can you provide the full command you want to run your projects?

Or can you define that in you pom.xml just like below?
https://stackoverflow.com/questions/64920521/how-to-pass-add-opens-jdk-module-configuration-to-maven-test

**Comment by VirensCn** [comment]
这种方式只适用于`mvn test`，我想的是在`mvn jetty:run`或者其他命令中携带这些属性

**Comment by VirensCn** [comment]
Take eclipse as an example

![image](https://user-images.githubusercontent.com/9736815/196332174-8a982552-cc1e-49fb-8289-9862b5c5d18e.png)
![image](https://user-images.githubusercontent.com/9736815/196332140-e8bfc725-c5b1-4af2-99bb-14b002b401ac.png)

**Comment by Eskibear** [comment]
Got it. You want to specify some customized VM args. Then you may configure environment variable [MAVEN_OPTS](https://maven.apache.org/configure.html#maven_opts-environment-variable), via setting `maven.terminal.customEnv`.

Or you can try `maven.executable.options` which directly appends args to all maven commands it assembles.

**Comment by VirensCn** [comment]
Thanks for the answer, and I also found that you can configure through the `.mvn/jvm.config` file
