### ISSUE TITLE
Unable to use keyboard shortcut maven.plugin.execute

### ISSUE THREAD

**Issue by ThierrySudre** [microsoft/vscode-maven#891]
I try to configure the VSCode Keyboard Shortcut  named Maven: Run (for maven.plugin.execute), and my goal was to run the "war:inplace" command (but the problem is the same for any other plugin command).
I understand that I need to add arguments to this shortcut like the plugin command ("war:inplace") and the project (plugin.project.pomPath) in order to complete the shortcut. 
But the question is: Where and how to set these arguments?

Here is the generated error:

![maven1](https://user-images.githubusercontent.com/47594758/198321558-f1a5f0bb-1b0a-4eb5-b894-0a2fb90f7804.jpg)

Here is what I try to add in the keybindings.json to define this shortcut arguments but with no success.

![maven2](https://user-images.githubusercontent.com/47594758/198322247-97d3bb47-a7e4-4926-8076-dccdb995808b.jpg)

I also try to analyze the vscode-maven source code with no real success, unfortunatelly  am not typescript specialist.

 - OS: Windows 10 x64 10.0.19043
 - VS Code version: 1.72.2
 - vscode-maven Extension version:  v0.39.0

**Comment by Eskibear** [comment]
`maven.plugin.execute` is not designed for external call, which accepts a PluginGoal (TreeItem from Maven Explorer) as parameter.

Workaround for you is to provide some required args according to its impl, as you tried.
https://github.com/microsoft/vscode-maven/blob/97a07a2187009044e8bddc33d8069e87c2d947f2/src/extension.ts#L100

```jsonc
        "args": {
            "name": "war:inplace",   // whatever maven goal actually
            "plugin": {
                "project": {
                    "pomPath": "C:\\path-to\\your-project"  // the section appended to "-f" in mvn cmdline
                }
            }
        }
```

**Comment by ThierrySudre** [comment]
Thank you very much,  almost "magic", it works perfectly.

**Comment by Eskibear** [comment]
The implementation changed. See https://github.com/microsoft/vscode-maven/commit/d62011e6002b8cb140823b8b2b54e7e6708aec23#diff-04bba6a35cad1c794cbbe677678a51de13441b7a6ee8592b7b50be1f05c6f626R102

@ThierrySudre  Please change `"name": "war:inplace"` to `"command": "war:inplace"`.

**Comment by ThierrySudre** [comment]
Done, working fine now, thanks
