### ISSUE TITLE
Improvements on Favorites Menu

### ISSUE THREAD

**Issue by gustavosimon** [microsoft/vscode-maven#901]
As described on the conversation of pull request #900, this issue is to improve the user experience about the Favorites Menu.

This items was suggestion from @Eskibear:

a) when maven.terminal.favorites is not configured, it's strange to display empty children, and you get no idea whether it's broken or how to add favorite items.
I would suggest we add a "+" button as inline action of FavoriteMenu, which provides a UI (e.g. quickpick/input) to add corresponding items.

b) Currently when I change the corresponding setting, I have to manually click the refresh button to get the tree items updated. Listening to the change and refresh tree view would be better. In fact it can be implemented by 
vscode.workspace.onDidChangeConfiguration API.

**Comment by gustavosimon** [comment]
@Eskibear, can you assign this issue to me?

**Comment by Eskibear** [comment]
@gustavosimon  
We'll ship the feature at the end of Nov. And we want to ship it with the improvement, which would be good for users to get started, especially for those who don't know the feature at all. 

Do you have time to implement above improvement in this week? I'll decide whether to spare some time working on it based on your schedule. Please let me know, thanks!

**Comment by Eskibear** [comment]
add @cscherryy who authored similar features in Gradle extension.

**Comment by gustavosimon** [comment]
Hello @Eskibear ! I'll work on it this week to ship the features. I have already implemented item `b`. So I have to work on item `a`.

**Comment by gustavosimon** [comment]
Can we close this issue @Eskibear ?
