### ISSUE TITLE
Missing prefix javafx for goals from plugin org.openjfx:javafx-maven-plugin:0.0.8

### ISSUE THREAD

**Issue by ltorok** [microsoft/vscode-maven#910]
**Describe the bug**
In Maven explorer is missing prefix _javafx_ for goals _jlink_ and _run_ from plugin org.openjfx:javafx-maven-plugin:0.08.

**To Reproduce**
1. Go to https://openjfx.io/openjfx-docs/, and then go to section MAVEN and go step by step
2. In step _4. Run the project_ is
    To run the project, open the Maven explorer, click <YOUR_PROJECT_NAME> -> Plugins -> javafx -> javafx:run
3. Here is BUG: in <YOUR_PROJECT_NAME> -> Plugins -> javafx -> run <- HERE is _run_ only without prefix _javafx_, see bellow attached screenshot in section **Screenshots**

**Expected behavior**
In <YOUR_PROJECT_NAME> -> Plugins -> javafx -> javafx:run <- IS _javafx:run_ and also other goals under javafx plugin have correct prefix _javafx_, example _javafx:jlink_.

**Environments:**
 - OS: Windows 10
 - VS Code info:
   Version: 1.73.1 (system setup)
   Commit: 6261075646f055b99068d3688932416f2346dd3b
   Date: 2022-11-09T04:27:29.066Z
   Electron: 19.0.17
   Chromium: 102.0.5005.167
   Node.js: 16.14.2
   V8: 10.2.154.15-electron.0
   OS: Windows_NT x64 10.0.19044
   Sandboxed: No
 - Extension version: 0.40.0

**Screenshots**

![missing_prefix_for_goals](https://user-images.githubusercontent.com/7220540/204764820-734d1e27-7807-480b-803b-2883e57229b4.png)

**Additional context**
Maven version 3.8.6; I tried Java 19.0.1 and Java 17.0.3

**Comment by ltorok** [comment]
Note:
for "Alternatively, you can also open a terminal and run mvn clean javafx:run to run the project." - this is ok, this is functional

**Comment by ganxiyun** [comment]
![image](https://user-images.githubusercontent.com/3457347/204773305-245cbbba-d5a9-435b-9d2d-a3016be4bc69.png)
I met the similar issue, prefix is not there

**Comment by ltorok** [comment]
@ganxiyun yes, it is the same problem, only in Your use case is it other plugin. But example _clean_ plugin - there is all ok. But example _compiler_ plugin don't have none prefix for all goals and his functional is ok.

**Comment by ltorok** [comment]
In my case is it unusable from Maven explorer, I get in Terminal this Error:
`
[ERROR] Unknown lifecycle phase "run". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or 
<plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
`

**Comment by ganxiyun** [comment]
Exactly. Although I could run through command

**Comment by Eskibear** [comment]
It's a regression caused by https://github.com/microsoft/vscode-maven/pull/903#issuecomment-1313151269 .

Will ship a fix ASAP.

**Comment by Eskibear** [comment]
It's fixed in v0.40.1. Please give it a try, and kindly let me know if that works for you.@ganxiyun @ltorok

**Comment by ltorok** [comment]
@Eskibear
I tried Pre-Release... For my javafx-maven-plugin is now all ok, but for goals of other plugins, example compiler, resources, install, deploy, site is there the same problem yet.
Note:
this my note is relevant, only if installing Pre-Release version extension mean last version/with last commits/changes published on github (I don't know exactly what mean Pre-Release). In time writing this comment I tried (because in this time You are was published new version) v0.40.1 and all is ok. Also for above goals of plugins compiler, resources, ... - there are none problems. Thanks for quickly fix. Very good job.

**Comment by Eskibear** [comment]
We release the extensions in monthly cadence. 
Pre-Release is a "nightly" build (automatically triggered if there's new commit) that you can have the latest feature/fix before we release the extension. The `patch` version is date related large number.

To fix the regression I just checked in the fix and manually released a "stable" version v0.40.1. By [the time](https://github.com/microsoft/vscode-maven/blob/210c29e6435f0eabb44b0d2aae5229a835cd54bf/.azure-pipelines/nightly.yml#L5-L6) the nightly pipeline is triggered, the same fix will be also available in the latest pre-release version. And you can switch back to the pre-release version then.

BTW, the regression should be observed in pre-release version for about two weeks, we could have avoided to release the stable version with the regression, if it was found earlier... And that's also one of the reasons we suggest experienced developers to use pre-release version. Again, thank you for using the pre-release version and reporting the issue.
