### ISSUE TITLE
Feature request: possibility go to source code of attached dependencies

### ISSUE THREAD

**Issue by ltorok** [microsoft/vscode-maven#912]
## Suggestion

It would be nice go to definition of source code JavaFX classes (generally some other source).
When now "I select Go to Definition" (or using of key shortcut F12) for example on _javafx.application.Application_ in editor of my source Java class, then I am got to _Application.class_ which start is
`
 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
`

## Use Cases

I want to use this for I go to source code of JavaFX or generally some other source.
With current approaches I don't know go to source code.

## Examples

After when if select "I select Go to Definition" (or using of key shortcut F12) for example on _javafx.application.Application_ in editor of my source Java class, then I go to source code of _Application.java_ in package j_avafx.application_ (is opened new tab/editor with source code for _Application.java_ in package j_avafx.application_ ).

Note:
for example particular for JavaFX I have src.zip file local on my disk where are all source codes

**Comment by Eskibear** [comment]
@testforstephen might have more knowledge about best practice to attach sources.

**Comment by ltorok** [comment]
I found this: [https://github.com/redhat-developer/vscode-java/issues/1315](https://github.com/redhat-developer/vscode-java/issues/1315)

**Comment by ltorok** [comment]
... but it was super hidden

**Comment by testforstephen** [comment]
Yes, there is a context menu "Attach Source" for that.

<img width="821" alt="screen shot 2018-11-13 at 7 05 33 pm" src="https://user-images.githubusercontent.com/148698/48451159-1f79ca80-e777-11e8-8a9c-44a75a9b05b4.png">
