### ISSUE TITLE
Fix or allow for workaround with classic bug "Plugin execution not covered by lifecycle configuration"

### ISSUE THREAD

**Issue by lfvjimisola** [microsoft/vscode-maven#915]
**Describe the bug**

This is an old classic bug:

1. https://www.eclipse.org/m2e/documentation/m2e-execution-not-covered.html
1. https://stackoverflow.com/questions/6352208/how-to-solve-plugin-execution-not-covered-by-lifecycle-configuration-for-sprin 

**Expected behavior**

Not shown as a problem in the Problems tab. It looks as there is a solution for Eclipse (see 1 above).

**Screenshots**

![Screenshot from 2022-12-06 09-33-49](https://user-images.githubusercontent.com/85176191/205862866-4b38889d-b2f6-49d6-8999-9ade9f0a7c85.png)

**Comment by Eskibear** [comment]
the warnings are not reported by this extension. probably you should open the issue in https://github.com/redhat-developer/vscode-java/issues

**Comment by lfvjimisola** [comment]
Ok. I was not sure which one was correct. 50/50 chance and I, of course, got it wrong. Sorry.
