### ISSUE TITLE
Maven View in vscode explorer is hidden right after loading Maven Project

### ISSUE THREAD

**Issue by tarekahf** [microsoft/vscode-maven#916]
**Describe the bug**
The Maven View in VS Code Explore never shows by default when you load Maven Project in vs code.

**To Reproduce**
1. Open any Maven Project with pom.xml
2. Open any .java file to trigger the extension 
3. Wait until Java Projects view and build status settle down
4. See Java Projects view is loaded.
5. Try to locate the Maven View in Explore, you will not find it.
6. Attempt to run a Maven Goal using `ctrl-shift-p` and the Maven View will show. 

**Expected behavior**
Maven View in Explore should appear and not be hidden when the project has a `pom.xml` file right after the project is loaded and the build status is completed successfully.

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10 Enterprise
 - VS Code version: 1.73.1
 - Extension version: Maven for Java v0.40.1

**Additional context**
- The Project JRE is pointing to JDK 1.8 in the Workspace VS Code Settings.
- I see the Maven View will show when you launch vs code without opening the Maven Project. 
- JAVA_HOME is pointing to JDK 18
- M2_HOME is not set. As per my research, it is never required in the recent maven version.
- The command `mvn -version` shows the following
```
Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Maven home: C:\apps\maven
Java version: 18.0.1.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-18.0.1.1
Default locale: en_US, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by ayatoullah** [comment]
ctrl+shipf+p choose maven:switch to flat view and it will be shown in the tabs left

**Comment by lx21s** [comment]
To me it happenes if all of my `pom.xml` are within `.gitignore`d folders. So I first have to call any of the extentions command to make the view visible.
