### ISSUE TITLE
`maven.executable.options` does not apply to 'all' mvn commands

### ISSUE THREAD

**Issue by makspll** [microsoft/vscode-maven#917]
Having this setup:		
```json
"maven.executable.options": "-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true"
```
in order to allow dependencies to work on internal corporate maven proxy,

Still throws certificate errors by maven: "unable to find valid certification path to requested target", meaning that those commands used for installing dependencies are not applying the flags given above.

Same thing happens with custom environment variables, as I tried setting MAVEN_OPTS via `maven.terminal.customEnv`

**Comment by Eskibear** [comment]
https://github.com/microsoft/vscode-maven/blob/7467311317291c49519a54cf3d08073a40ce6a49/src/utils/mavenUtils.ts#L72

Both custom envs and options should be honored when executing the commands. You can open "Output" -> "Maven for Java" to see detailed logs, including the actual commands executed.

**Comment by makspll** [comment]
Upon further inspection it turns out it's not this exception that's generating the issue, but rather the redhat java extension, which is generating pom.xml file errors even after this extension is uninstalled
