### ISSUE TITLE
Documentation on tag hover duplicates with the XML extension's

### ISSUE THREAD

**Issue by fbricon** [microsoft/vscode-maven#918]
**Describe the bug**
When both vscode-maven and [Red Hat's XML extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml) are installed, you'll see duplicate documentation when hovering over pom.xml tags

**To Reproduce**
1. Install https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml
2. open a pom.xml
3. hover over a tag, eg. `<properties>`
4. See duplicate doc

**Expected behavior**
Ideally, there would be no documentation overlap when both extensions are installed.
vscode-maven could detect that `redhat.vscode-xml` is installed and avoid providing overlapping features. IMHO vscode-xml being truly specialized in everything XML, it should takes precedence when dealing with pure XML features.

**Screenshots**
<img width="626" alt="Screenshot 2022-12-09 at 11 38 29" src="https://user-images.githubusercontent.com/148698/206697294-86dc42ab-9987-423f-85ea-fde84080c623.png">

**Comment by Eskibear** [comment]
It makes sense.

**Comment by Eskibear** [comment]
available in pre-release `0.40.2022121203` now.

**Comment by fbricon** [comment]
@Eskibear thanks. Although the change doesn't listen to (un)installed extension events, but we can probably live without. Nothing a restart won't fix.

**Comment by Eskibear** [comment]
If we do want cover the case like install/uninstall, we can check existence of xml extension for every request. It looks a little bit wired but probably won't cause much performance degradation (requiring some verification).

As install/uninstall are not frequent operations, let's just live without it for the moment. We can cover it any time when it becomes necessary.
