### ISSUE TITLE
Maven settings.xml not working

### ISSUE THREAD

**Issue by AngelDark92** [microsoft/vscode-maven#923]
I could not tell you why, but all this worked as intended one month ago.
I just could not get the setting `"java.configuration.maven.userSettings": "./customSettings.xml"` to work under neither Workspace nor User in VS Code. I have also used the full path (eg. D:\SpringBoot and Angular\Workspace\apache-maven-3.8.6\conf\customSettings.xml).
The only way I could get it to download the custom repos was by using terminal and running `mvn -s customSettings.xml dependency:list`. I had already tried using global settings as well, always cleaning the project under Lifecycle>clean and rebuilding the whole java project with clean language server workspace every time I edited my settings.
By the look of it the update was trying to fetch the custom dependency from maven central even though the customSettings.xml was specified. 
I might be missing something but having it done on my desktop I am pretty sure the only thing to do is edit that setting...

**Comment by Eskibear** [comment]
The setting `java.configuration.maven.userSettings` doesn't belong to this extension. See https://github.com/redhat-developer/vscode-java#supported-vs-code-settings


Probably you should open the issue in https://github.com/redhat-developer/vscode-java/issues , better providing a sample project to stably reproduce it.

**Comment by AngelDark92** [comment]
Ok, I did not realise. Thanks for the heads up.
