### ISSUE TITLE
Cannot navigate to a dependency pom.xml by f12

### ISSUE THREAD

**Issue by phommy** [microsoft/vscode-maven#924]
**Describe the bug**
When navigate to dependency pom.xml, got wrong folder path. 

**To Reproduce**
1. Open a pom.xml file of a java project
2. On a dependencies\dependency node, F12 or ctrl+click 
3. Expected behavior: navigate to the dependency pom.xml. e.g. D:\maven_cache\com\sun\mail\all\1.5.0\all-1.5.0.pom
（see https://github.com/microsoft/vscode-maven/issues/428）. 
4. Actually behavior: naigate to C:\Program Files\Microsoft VS Code\com\sun\mail\all\1.5.0\all-1.5.0.pom , which does not exist.
5. In settings.xml of maven, localRepository = d:\maven_cache\ 

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: 1.74.2
 - Extension version: Maven for Java[0.40.2]

**Screenshots**
![error](https://user-images.githubusercontent.com/24478780/209922377-0ac02217-c9fe-4c18-8644-c14f0321e7e8.png)

**Comment by Eskibear** [comment]
It should be a regression introduced by:

https://github.com/microsoft/vscode-maven/commit/db028b3dc4ced9837ea6609bc51122d8ca1316d6#diff-a2b9078fc2f74c772f756ca0ab1fc23d5fe9b2a70c65c1cb3c666c559c7e3bf9R48

**Comment by Eskibear** [comment]
@phommy You can switch to pre-release version (0.40.2023011003) to verify the fix, please let me know if it works.

**Comment by phommy** [comment]
> @phommy You can switch to pre-release version (0.40.2023011003) to verify the fix, please let me know if it works.

@Eskibear it works.
