### ISSUE TITLE
installation through the java extension failed

### ISSUE THREAD

**Issue by owenyi** [microsoft/vscode-maven#926]
**Describe the bug**
Error occured while installing 'Maven for java' extension.

**To Reproduce**
1. Go to 'Extensions(Ctrl+Shift+X)'
2. Click on 'intall(Maven for java)'
3. See error

**Expected behavior**
I got the error message below.

Extract: EPERM: operation not permitted, open 'c:\Users\user\\.vscode\extensions\.db8b347c-26a7-41fa-b115-1fc6785cf215\resources\IndexData\index\_l_Lucene50_0.doc'

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: 1.74.2
 - Extension version : 0.40.2

**Screenshots**
![image](https://user-images.githubusercontent.com/67588446/211240384-d0c612bb-c813-4cc5-9757-a5000d239df7.png)

**Comment by Eskibear** [comment]
I cannot reproduce it.

The file should eventually be located in `.../.vscode/vscjava.vscode-maven-0.40.2/resouces/...`. The error looks like vscode was renaming the files after extracting them into a temp folder.
Is it possibly because of networking issue? Can you stably reproduce it?
