### ISSUE TITLE
Errors and warnings not updated after remedying source file issue

### ISSUE THREAD

**Issue by chris-miner** [microsoft/vscode-maven#939]
**Describe the bug**
I created an error in a file.  The mojo responsible for generating sources from this file reported errors and warnings.  These errors and warnings were displayed in the "problems" tab.  I fixed the issue, but the display was not updated.  I created a new error in the file and this was added to the list of problems.  Old fixed issues continued to be displayed.

**To Reproduce**
1. create an error in a source file
2. wait for the file to be processed via maven plugin
3. note the errors and warnings
4. fix the problem
5. notice that the errors and warnings are not updated to reflect the new status.

**Expected behavior**
I expected to see no errors listed for the repaired file

**Environments (please complete the following information as much as possible):**
 - OS: macos
 - VS Code version: 1.75.1
 - Extension version v0.40.4

**Screenshots**

**Additional context**
the mojo that reports errors is the antlr4-maven-plugin version 4.9.3
From the command line the errors are not reported after remedying the file.
I'm really not sure what the chain of events is that goes from running the mojo in maven and getting the output to show up in VS Code, so I don't know if this is a vs code problem, a maven plugin problem, or a problem with the underlying mojo.

**Comment by Eskibear** [comment]
Not sure whether the error is reported by this Maven extension. A screenshot of the "problems" tab containing the detailed error message would help me to check.

**Comment by chris-miner** [comment]
Here's a screen shot of the problems generated by my incorrect source file:
<img width="915" alt="Screen Shot 2023-02-19 at 08 20 50" src="https://user-images.githubusercontent.com/94078897/219957457-e11d12db-fd7d-4d1f-89d5-529ef44a6179.png">

After I correct the problem and save the file, the problems view is unchanged.  Here's the table view of those results:
<img width="1125" alt="Screen Shot 2023-02-19 at 08 24 26" src="https://user-images.githubusercontent.com/94078897/219957634-91e8651c-6e66-4ec8-870a-f65cf62249ad.png">

Notice that the warnings about 'implicit definition of token' are reported for the `pom.xml` file rather than the `Hello.g4` file.  The `pom.xml` file has nothing to do with tokens.  Also notice that the `pom.xml` warnings match the line number of the `Hello.g4` errors.

**Comment by chris-miner** [comment]
I found an issue on the vscode project which seems related:
[vscode.languages.getDiagnostics appears to return old diagnostics in some circumstances #54359](https://github.com/microsoft/vscode/issues/54359)

**Comment by Eskibear** [comment]
From the "Source" column, you can see none of the errors/warnings are reported by this extension. AFAIK those under `pom.xml` are reported by Java extension, that you might open an issue in https://github.com/redhat-developer/vscode-java
And those under `hello.g4` seem to be reported by some antlr extension?

BTW, the issue you found above is long time ago, that I don't think it's related.

**Comment by chris-miner** [comment]
Thanks!  I assumed errors+warnings from the maven mojo would bubble up through the maven extension to the vs code ui somehow.  I do know where the antlr ones come from — I disabled plugins until the errors went away.

I'll look for the source of the issue elsewhere.
