### ISSUE TITLE
How to configure maven2

### ISSUE THREAD

**Issue by coderfarmerps** [microsoft/vscode-maven#943]
**Describe the bug**
cannot run with maven2!
![image](https://user-images.githubusercontent.com/16918242/221797084-b9196493-d6d0-4760-96dc-88e3ae5c8d66.png)

**Comment by Eskibear** [comment]
It's not supported. We use [depgraph-maven-plugin](https://github.com/ferstl/depgraph-maven-plugin) to calculate dependencies. 

Any reason you are still using Maven 2?
