### ISSUE TITLE
maven explorer Profiles 

### ISSUE THREAD

**Issue by kukuxiahuni** [microsoft/vscode-maven#964]
**Describe the bug**
first i can not sure this is a bug. but in my vscode  I get different show. I hava two maven project, the one can show the profiles and the other not. sometimes `Background process terminated with code 127.`
![image](https://user-images.githubusercontent.com/3644294/231400878-1875436f-2e8f-4235-991c-f0f74b65447f.png)
![image](https://user-images.githubusercontent.com/3644294/231401942-aa2833b5-917c-42df-b645-22eed591c607.png)

How to fix them??

**Expected behavior**
can list the maybe problems or the notices.

**Environments (please complete the following information as much as possible):**
 - OS: Windows 10
 - VS Code version: 1.77.2
 - Extension version 0.41.0

**Comment by Eskibear** [comment]
When the error occurred, go to Output `Maven for Java`, see what was printed there.

**Comment by kukuxiahuni** [comment]
1. there are no errors in output；
2. only a warning "message": "Build path specifies execution environment JavaSE-1.8. There are no JREs installed in the workspace that are strictly compatible with this environment. ",



![image](https://user-images.githubusercontent.com/3644294/234496953-e9972e11-41b8-4ab7-ac15-a69ae0b5bab4.png)

**Comment by Eskibear** [comment]
so the content of `xxxx.profiles.txt` in your screenshot? this extension directly parse output from there.
BTW if you can stably reproduce it, a sample project can be shared, that would be more helpful.

**Comment by kukuxiahuni** [comment]
I think the code have a little problem。 
```public static parseProfilesOutput(project: MavenProject, output: string) : MavenProfile[] {
        const profiles: MavenProfile[] = [];
        const regexp = /Profile Id: (.*) \(Active: (true|false) , Source: (.*)\)/g;
        let match: RegExpExecArray | null;
        do {
            match = regexp.exec(output);
            if (match != null && match.length === 4) {
                const id = match[1];
                const active = match[2] === "true";
                const source = match[3];
                if (!profiles.find(p => p.id === id)) {
                    const profile = new MavenProfile(project, id, active, source);
                    profiles.push(profile);
                }
            }
        } while (match !== null);
        return profiles;
    }
```

![image](https://user-images.githubusercontent.com/3644294/234502307-4bb29b51-42ea-4a67-b5a7-a89bf4cf8cf9.png)
maybe there is an extra space。

`/Profile Id: (.*) \(Active: (true|false) , Source: (.*)\)/g`
`Profile Id: dev (Active: true, Source: pom)`

![image](https://user-images.githubusercontent.com/3644294/234503171-92bf42e1-1cfc-487a-a800-7feb536aeb65.png)

this is my test code 
```
var pattern = /Profile Id: (.*) \(Active: (true|false) , Source: (.*)\)/,
    str = 'Profile Id: dev (Active: true, Source: pom)';
   console.log(pattern.test(str));
```

may can 
```
var pattern = /Profile Id: (.*) \(Active: (true|false)(.*), Source: (.*)\)/,
    str = 'Profile Id: dev (Active: true, Source: pom)';
console.log(pattern.test(str));
```

**Comment by Eskibear** [comment]
Good catch.
Probably it's due to some changes in maven-help-plugin 3.4.0, released last month. see https://github.com/apache/maven-help-plugin/releases/tag/maven-help-plugin-3.4.0

Yes, we should update the regexp to make it more robust and you provided a good example. 

Talking about the implementation, instead of adding  `(.*)` , I would prefer to `\s?` indicating there can be an optional whitespace char.

Let us know if you are interested in creating a PR, otherwise we'll fix it on our own. /cc @testforstephen

**Comment by kukuxiahuni** [comment]
Wating for your fix.  i am newer in javascript, study hard. 

in my new project is ok. Maybe the old project created by idea, the new one created by vscode. but the `cit`/`crm` come from setting.xml. 
```
[INFO] --- help:3.3.0:all-profiles (default-cli) @ chaos ---
[INFO] Listing Profiles for Project: com.sankun.chatgpt:chaos:jar:0.0.1-SNAPSHOT
  Profile Id: cit (Active: true , Source: settings.xml)
  Profile Id: crm (Active: true , Source: settings.xml)
  Profile Id: native (Active: false , Source: pom)
  Profile Id: nativeTest (Active: false , Source: pom)
```

**Comment by Eskibear** [comment]
> [INFO] --- help:3.3.0:all-profiles (default-cli) @ chaos ---

That's because your new project is using maven-help-plugin 3.3.0.    

> Wating for your fix.

No problem. I'll invite @testforstephen to provide a quick fix.

**Comment by synckey** [comment]
Any plan to fix this?

**Comment by Eskibear** [comment]
@synckey I created PR #980 for this.

@testforstephen please take a look.

**Comment by synckey** [comment]
> @synckey I created PR #980 for this.
> 
> @testforstephen please take a look.

Really sweet for this

**Comment by kukuxiahuni** [comment]
How about this bug？
