### ISSUE TITLE
Resolving import with generated files

### ISSUE THREAD

**Issue by PaulBazin** [microsoft/vscode-maven#967]
**Describe the bug**
I have this use case where I generate java files with swagger in a mutli modules maven project.
When importing such generated class in another project, even tho `mvn clean install` works, VS Code is showing up a `The import cannot be resolve` error.

**To Reproduce**
1. Unzip the sample project [Tmp.zip](https://github.com/microsoft/vscode-maven/files/11333202/Tmp.zip)
2. Open the folder in VS Code
3. See the error in demo project src/main/java/com/example/frameOne.java

**Expected behavior**
Import is resolved.

**Environments (please complete the following information as much as possible):**
 - OS: Linux
 - VS Code version: 1.77.1
 - Extension version 0.41.0

**Comment by jdneo** [comment]
Add this line `<?m2e execute onConfiguration?>` can solve your problem.

![image](https://user-images.githubusercontent.com/6193897/234749193-1723dda4-58b2-41db-9255-ec1b109340d6.png)

**Comment by PaulBazin** [comment]
Thank you so much for your answer.
To understand why this solve the problem : vsCode-maven is based on some m2e librairies ?
Again thank you !

**Comment by jdneo** [comment]
VS Code Maven is not based on m2e, This extension is used to provide some handy features to run maven commands in VS Code.

It's `redhat.java` importing the project, and provide language related features.
