### ISSUE TITLE
Failed to calculate Effective POM. Please check output window 'Maven for Java' for more details.

### ISSUE THREAD

**Issue by Sujeet786456** [microsoft/vscode-maven#974]

**Comment by iwoodu** [comment]
I receive the same error.  Additional details below:

> Spawn {"command":"\"${config:maven.home}mvn.cmd\"","args":["-B","-Doutput=\"c:\\Users\\myId\\AppData\\Roaming\\Code\\User\\workspaceStorage\\f07e8dd5926fc63e6d7a5f2d488d1353\\vscjava.vscode-maven\\c89b0251f42f7fada3fa9249588b544b.epom\"","help:effective-pom","-f","\"c:\\Users\\myId\\Documents\\repos\\myId\\my-project-name\\pom.xml\""]}
> The filename, directory name, or volume label syntax is incorrect.

**Comment by testforstephen** [comment]
As you can see, the underlying implementation is calling the mvn command to retrieve the effective POM. Could you please try running the same command in the terminal manually to verify if it works?
