### ISSUE TITLE
Fail to disable profile because shell interprets the '!' character

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-maven#995]
This fails under MacOs on my box because the shell interprets the '!' character before it runs the command. Any way of tweaking this so that Bash and Zsh you could get it to use the Maven alternative syntax -P-disableThisProfile,enableThisProfile ?

_Originally posted by @JFK-DXML in https://github.com/microsoft/vscode-maven/issues/956#issuecomment-1713854639_
            

https://maven.apache.org/guides/introduction/introduction-to-profiles.html#deactivating-a-profile

Maybe we can use `-` instead of `!` to have better compatibility.

**Comment by panjiahao-pacvue** [comment]
@Eskibear @testforstephen 这个问题既然已经解决了，请问下个版本什么时候发布
