### ISSUE TITLE
Add support for externally provided "lifecycle-mapping-metadata.xml" file

### ISSUE THREAD

**Issue by vitalyla** [microsoft/vscode-maven#998]
## Suggestion

Add support for external provided file "lifecycle-mapping-metadata.xml" per M2E recommendations that allows configuration of lifecycle of Maven's plugins outside of any certain project and have it at system/user/workspace level.

## Use Cases

While working on Maven projects it is common that not all plugins undergo changes related to their lifecycle configuration per M2E recommendations, which prohibits execution of those plugins by IDE and as a result required artifacts are not get generated (e.g., generated code) causing compilation and build problems.

Current way to overcome the problem is to manually add relevant m2e annotation (m2e execute onConfiguration) in each "pom.xml" file directly, which is very cumbersome, error prone and problematic approach when working on multiple projects. The impact is bigger when certain files cannot be submitted back to source control system that leads to keeping copies locally creating maintenance overhead.

**Comment by barrycaceres** [comment]
this would be fantastic.... I keep getting told my pom.xml is not valid.

**Comment by testforstephen** [comment]
Moved to https://github.com/redhat-developer/vscode-java/issues/3393 since m2e is from Java language support extension.
